### ISSUE TITLE
Aufbau und Ablauf allgemein

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#1]
**Population:** Befragt werden die Studienberechtigten 2018 ca. 2,5 Jahre nach HZB. Je nach bisheriger Teilnahme an den vorherigen Wellen (bzw. der Panelmortalität) gibt es teils einen spezifischen Befragungsablauf siehe Variable "wave" im Issue Preloads & Hilfsvariablen). 

**Befragungszeitpunkt:** Feldstart der Befragung ist für Ende Januar 2021 geplant. Genaue Terminierung des Versands der Einladungen, Erinnerungen etc. folgt. 

**Befragungsaufbau:** Die Befragung findet ausschließlich als (responsive) Online-Erhebung statt. Die Befragung gliedert sich in sieben inhaltliche Module auf. Zusätzlich gibt es zwei Kalendarien (unterscheiden sich bezüglich des Erhebungszeitraums aufgrund bisheriger Teilnahme an Wellen) und zwei Episodenmodule (unterscheiden sich bezüglich des Erhebungszeitraums aufgrund bisheriger Teilnahme an Wellen). Die PVs für die 7 Module werden modulweise sukzessive als .doc an Zofar per Github (https://github.com/dzhw/studienberechtigte_2018.3b/issues/2) übermittelt und später unter Code weiterbearbeitet/korrigiert. Bitte in den codes in github Module auch einzeln anlegen.  Die Episodenmodule basieren im wesentlichen auf der SLC-inter-Befragung (Zeiträume und kleine Korrekturen überarbeiten Sebastian und Johann und übergeben die Episodenmodule dann). Am Ende der Befragung erfolgt eine AddOn-Befragung zur Adressaktualisierung. Die Befragungsblöcke/-module gliedern sich wie folgt:

- Modul 1: Einstieg

- Modul 2: Corona

- Modul 3: Schulabschluss

- Kalendarien (je nach Welle: Kalendarium A: Zeitraum Dez. 2019 bis Jan. 2021; Kalendarium B: Zeitraum Jan. 2018 bis Jan. 2021)

- Episodenmodule (je nach Welle: Epi-Modul A: Dez. 2019 bis Jan. 2021; Epimodul B: Jan. 2018 bis Jan. 2021)

- Modul 4: Ausbildungsintention

- Modul 5: Studium

- Modul 6: Gesundheit

- Modul 7: Soziodemografie

- AddOn-Befragung: Adressaktualisierung

**aktualisiertes Flowchart mit Befragungsübersicht (Stand 16.12.2020)**
[flowchart_FB_01-Dez_aktuell.pdf](https://github.com/dzhw/studienberechtigte_2018.3b/files/5702967/flowchart_FB_01-Dez_aktuell.pdf)

**Comment by heikQ** [comment]
aktualisertes flowchart, Stand 19.11., siehe oben: Zwischenseiten vor Kalendarium auch entsprechend benannt. Block "Episoden" umbenannt in "Kalendarium/Episoden"

**Comment by heikQ** [comment]
flowchart update, fehlende filterung bei Frage nach Kindern (Modul 7) ergänzt

**Comment by andreaschu** [comment]
**Hier die FlowCharts der Episodenmodule:**

[Episoden_Ausbildung (questionnaire9)](https://user-images.githubusercontent.com/30111489/102197450-78217180-3ec1-11eb-87e0-74d0773ecab3.png)
[Episoden-Schule questionnaire10)](https://user-images.githubusercontent.com/30111489/102197494-8b344180-3ec1-11eb-9f16-e76dd4b02ee2.png)
[Episoden_andereTätigkeiten (questionnaire11)](https://user-images.githubusercontent.com/30111489/102197483-88d1e780-3ec1-11eb-88ab-2236db408fae.png)
[Episoden_Arbeitslosigkeit (questionnaire12)](https://user-images.githubusercontent.com/30111489/102197491-8a9bab00-3ec1-11eb-89bf-e719c6e0004b.png)
[Episoden_Studium (questionnaire13)](https://user-images.githubusercontent.com/30111489/102197562-9edfa800-3ec1-11eb-99f8-0fa5d665583d.png)

[Episoden_nichtselbständige Erwerbstätigkeit (questionnaire14)]

zu groß für einen Upload, deswegen in der Cloud zum Downloaden (Passwort: **_epi(sch)_**)
[Episoden_selbständige Erwerbstätigkeit (questionnaire15)](https://myshare.dzhw.eu/index.php/s/u7a7knuHUDfc5Jr)

[Episoden_Weiterbildung (questionnaire16)](https://user-images.githubusercontent.com/30111489/102197556-9d15e480-3ec1-11eb-8af5-d0b6ef0f4faf.png)
[Episoden_Praktikum (questionnaire17)](https://user-images.githubusercontent.com/30111489/102197559-9dae7b00-3ec1-11eb-8b8f-2d60b1c4b34e.png)

**Comment by andreaschu** [comment]
**aktueller Stand der FlowCharts** 

[index](https://user-images.githubusercontent.com/30111489/102377926-85c01f80-3fc5-11eb-8d53-9896cc593dc1.png)
[Einstieg](https://user-images.githubusercontent.com/30111489/102377924-85278900-3fc5-11eb-83d6-f04590a9af83.png)
[Corona](https://user-images.githubusercontent.com/30111489/102377938-8789e300-3fc5-11eb-896b-76b142b7e908.png)
[Schulabschluss](https://user-images.githubusercontent.com/30111489/102377936-8789e300-3fc5-11eb-88b1-1c6cd73cf918.png)
[Ausbildung](https://user-images.githubusercontent.com/30111489/102377934-86f14c80-3fc5-11eb-9299-4ba4c1af29bd.png)
[Studium](https://user-images.githubusercontent.com/30111489/102377933-8658b600-3fc5-11eb-8bd4-31bcefc8ae0a.png)
[Gesundheit](https://user-images.githubusercontent.com/30111489/102377931-8658b600-3fc5-11eb-800f-e2b846c1bb22.png)
[SozDem](https://user-images.githubusercontent.com/30111489/102377930-85c01f80-3fc5-11eb-9cc0-7502d498fa76.png)
[Kalendarien](https://user-images.githubusercontent.com/30111489/102377928-85c01f80-3fc5-11eb-9c77-0b82ed719b82.png)
[Zwischenseiten](https://user-images.githubusercontent.com/30111489/102377939-88227980-3fc5-11eb-9b0c-2513f7e4fc3e.png)
