### ISSUE TITLE
[Episoden] Datumsseiten

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/studienberechtigte_2018.3b#10]
Bitte klären: 
1. Können wir im DropDown für die Jahresvariablen für PRELOADwave==1 alle AOs bis auf eine (inkl. MV/Default) ausblenden? 
2. Funktioniert dann die Javaskript-Lösung zur automatischen Auswahl von Monat/Jahr bei der Nutzung der Buttons "Beginn vor [Startdatum]" und "dauert noch an" noch? 
3. Ist es möglich, die Javaskript-Lösung anhand von PRELOADwave anzupassen? (Januar 2018 für wave 2-5, Januar 2020 für wave 1)?

**Comment by jocarstensen** [comment]
Gibt es hier etwas Neues?

**Comment by jocarstensen** [comment]
Bitte um Rückmeldung!

**Comment by andreaschu** [comment]
@jocarstensen 

zu 1: ja. Alle AOs können über Visible Conditions ausgeblendet werden. Dann erscheint eine DropDown-Liste mit nur einer Antwortmöglichkeit. Das können wir ggf. über JavaScript schöner machen.

zu 2: Ja, das haben wir getestet.

zu 3: ich bin mir nicht mehr sicher, was hier die Frage ist.

**Comment by jocarstensen** [comment]
Danke soweit.

Zu 3: Die Javascript-Lösung vom letzten Jahr sieht vor, dass bei Aktivierung der Checkbox für Beginn vor [h_enterdatum] automatisch das Enterdatum (z. B. Januar 2018) ausgewählt wird. Enterdatum unterscheidet sich ja aber für wave 1 und den Rest. Funktioniert die automatische Auswahl via Javascript auch für unterschiedliche Startdaten nach wave?

**Comment by jocarstensen** [comment]
Wie schon in Issue 29 geschrieben, brauchen wir hier noch immer eine Rückmeldung. Viktor hat damals die Lösung über Javascript gebaut. Der müsste Auskunft geben können.

**Comment by andreaschu** [comment]
Ja, das funktioniert weiterhin. Aber die Funktion muss angepasst werden. 

Deshalb hier noch mal zur Doku bzw. zum Verständnis:
Kannst Du das so bestätigen oder korrigieren?

-----
**Vorher war es:**
Wenn die Checkbox `vor h_enterdatum ` (z. B. emaa01a=="True") angeklickt wird, dann soll ausgewählt werden:
1. if cohort==1, dann: emaa01==ao1 (Januar) und emaa02==ao1 (2018)
2. if cohort== 2, dann: emaa01==ao7 (Juli) und emaa02==ao1 (2018)

Wenn die Checkbox `dauert an` (z. B. emaa03a=="True") angeklickt wird, dann soll ausgewählt werden:
1. emaa03==ao12 (Dezember) und emaa04==ao2 (2019)


-------------------
**Jetzt soll es sein:**
Wenn die Checkbox `vor h_enterdatum ` (z. B. emaa01a=="True") angeklickt wird, dann soll ausgewählt werden:
1. if wave==1, dann: emaa01==ao1 (Januar) und emaa02==ao1 **(2018)**
2. if wave!= 1, dann: emaa01==ao1 (Januar) und emaa02==ao1 **(2020)**

Wenn die Checkbox `dauert an` (z. B. emaa01?=="True") angeklickt wird, dann soll ausgewählt werden:
1. emaa03==ao12 (Dezember) und emaa04==ao2 (2019)

**Comment by jocarstensen** [comment]
Die Checkbox `dauert an` wäre emaa03a und die Bedingungen für wave sind falschrum (1. müsste wave!=1 sein und 2. wave==1). Aber ansonsten ist es so richtig. Dann klappt also alles und Ihr seid informiert. Das ist fein.

**Comment by andreaschu** [comment]
@dzhwmeisner könntest Du das entsprechend umsetzen?

Wenn die Checkbox vor h_enterdatum (z. B. emaa01a=="True") angeklickt wird, dann soll ausgewählt werden:
```
    if wave!=1, dann: emaa01==ao1 (Januar) und emaa02==ao1 (2018)
    if wave== 1, dann: emaa01==ao1 (Januar) und emaa02==ao1 (2020)
```

**Comment by dzhwmeisner** [comment]
ist impementiert und wird nach dem nächsten Rollout zur Verfügung stehen.

**Comment by jocarstensen** [comment]
@andreaschu @dzhwmeisner Wir brauchen die Anpassung des Referenzzeitraums auch noch für die Checkbox "vor h_enterdatum". Also bitte folgendes ändern:

von:
`if wave!=1, dann: emaa01==ao1 (Januar) und emaa02==ao1 (2018)`

in:
`if wave!=1, dann: emaa01==ao7 (Juli) und emaa02==ao1 (2018)`

**Comment by AliceFoelker** [comment]
@jocarstensen müsste es in der ersten Zeile nicht wave=1 heißen?
> 
> @andreaschu @dzhwmeisner Wir brauchen die Anpassung des Referenzzeitraums auch noch für die Checkbox "vor h_enterdatum". Also bitte folgendes ändern:
> 
> von:
> `if wave!=1, dann: emaa01==ao1 (Januar) und emaa02==ao1 (2018)`
> 
> in:
> `if wave!=1, dann: emaa01==ao7 (Juli) und emaa02==ao1 (2018)`

**Comment by andreaschu** [comment]
@dzhwmeisner kannst Du die zweite Bedingung noch mal anpassen?

**Comment by andreaschu** [comment]
@AliceFoelker nein, das ist die Version wie sie jetzt ist ("von:").

**Comment by dzhwmeisner** [comment]
Änderung ist im nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
fixed
