### ISSUE TITLE
Texte Index-Seiten & Datenschutzhinweise

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#101]
Nachfolgend die Texte für die Index-Seiten, diese variieren je nach preload Variable "wave" und bei wave 4,5 noch zusätzlich nach preload-Variable "incentive" (siehe flowchart). An den markierten/kommentierten Stellen in den Word-Dokumenten soll ein link auf die pdf "Datenschutzhinweise" gesetzt werden. Der link soll dabei einen neuen TAB bzw. ein neues Fenster mit der PDF öffnen.

**aktualisierte Indexseiten**
**Indexseite wave=1**
[index_wave1.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5771572/index_wave1.docx)

**Indexseite wave=2**
[index_wave2.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5771575/index_wave2.docx)

**Indexseite wave=3**
[index_wave3.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5771576/index_wave3.docx)

**Indexseite (wave=4 oder 5) UND (incentive=1)**
[index_wave4&5_incentive1.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5771577/index_wave4.5_incentive1.docx)

**Indexseite (wave=4 oder 5) UND (incentive=2)**
[index_wave4&5_incentive2.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5771578/index_wave4.5_incentive2.docx)

**verlinkte PDF mit Datenschutzhinweisen (für alle INDEX-Versionen identisch)**
[Datenschutzhinweise.pdf](https://github.com/dzhw/studienberechtigte_2018.3b/files/5763484/Datenschutzhinweise.pdf)

**Comment by AliceFoelker** [comment]
@christian-fr bei wave 5 erscheint kein Indextext. Bei wave 4 sind beide Texte 1x hohe und 1x niedrige Verlosung drin (vermutlich weil incentive=1 oder incentive=2 nicht zugeordnet sind, oder?)

**Comment by AliceFoelker** [comment]
@andreaschu @christian-fr bei den Indexseiten ist ein bisschen was durcheinander gekommen und es haben sich auch unsererseits ein paar Wörter geändert. Vermutlich ist es am einfachsten diese einfach nochmal neu reinzukopieren?! siehe aktualisierte Liste oben (Datenschutzhinweise sind identisch geblieben)

**Comment by andreaschu** [comment]
@AliceFoelker ich habe gerade eine Programmiervorlage für die Index-Seite erstellt (2cbee5b). Von nun an, bitte Änderungen immer hier einfügen. 
https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/index_page

Die Texte für wave==2 und wave==3 unterscheiden sich nicht, oder?

**Comment by andreaschu** [comment]
Ich habe die Änderungen vorgenommen. Beim nächsten Roll-Out können sie getestet werden.

Zu den Texten: Es ist ja nur eine Index-Seite. In der derzeitigen Testversion werden die Preload-Variablen noch als Variablen eingegeben. Du musst hier die Werte eintragen und dann die Seite neu laden bzw. auf weiter und zurück oder weiter ohne Einwilligung. Dann sollten die Einblendungen passen.

**Comment by AliceFoelker** [comment]
@andreaschu genau so habe ich es gemacht, nur eben bei wave 5 wurde die Landingpage nicht angezeigt. bei dem Rest hat es funktioniert.

**Comment by AliceFoelker** [comment]
#148

**Comment by andreaschu** [comment]
> @andreaschu genau so habe ich es gemacht, nur eben bei wave 5 wurde die Landingpage nicht angezeigt. bei dem Rest hat es funktioniert.

Was meinst Du damit genau? Welcher Teil fehlt hier? 
Bei mir wird das hier angezeigt:

![grafik](https://user-images.githubusercontent.com/30111489/103919107-f1eafa80-510f-11eb-9d78-dae1f52c14df.png)

**Comment by AliceFoelker** [comment]
@andreaschu komisch bei mir wie hier #148 siehe Screenshots

**Comment by andreaschu** [comment]
Siehe den Kommentar von eben gerade: https://github.com/dzhw/studienberechtigte_2018.3b/issues/148#issuecomment-756235835

**Comment by AliceFoelker** [comment]
fixed - zwecks Dokumentation lasse ich das Issue noch geöffnet
