### ISSUE TITLE
zwischen_cal_bd Befragungszeitraum falsch im Text

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#102]
tester19 wave 4
Wieso wird hier lediglich die Aktivität zwischen Juli 2018 und Dezember 2019 abgefragt bzw. angekündigt? Hier müsste es doch z.B. für wave 4  - Januar 2018 bis Dezember 2020 heißen oder? zwischen_cal_ad müsste dementsprechend auch noch getestet werden.
Das darauffolgende Kalendarium ist richtig. 
![grafik](https://user-images.githubusercontent.com/73596957/103527065-16ca3e00-4e82-11eb-839b-e84a224fb4be.png)

**Comment by christian-fr** [comment]
@AliceFoelker 
Wenn ich das richtig sehe, werden die vier pages von den folgenden Wellen angesprungen:

page | PRELOADwave 
---|---
zwischen_cal_am | `== 1`
zwischen_cal_ad | `== 1`
.|.
zwischen_cal_bm |`!= 1`
zwischen_cal_bd | `!= 1` 

Welche Daten (Anfang und Ende) sollen dort denn jeweils angezeit werden?

**Comment by AliceFoelker** [comment]
@christian-fr 
https://github.com/dzhw/studienberechtigte_2018.3b/issues/5#issue-744011686

> **Kalendarien**:
> Es werden zwei Kalendarien je nach subsample (Ansteuerung über preload- Variable "wave") mit unterschiedlichen Zeiträumen benötigt. Beide Kalendarien, Kategorien, Einleitungstext und Befüllung von Hilfsvariablen etc. sind bis auf die Zeiträume wie in der vorherigen slc-inter Befragung für das Kalendarium mit der prelaod-Variable cohort=2 (für 2018.3a) anzulegen.
> 
> Kalendarium A:
> Zeitraum: Januar 2020 bis Dezember 2020
> Kategorien: siehe slc-inter Befragung für cohort=2 (Kohorte 2018). Bitte auch Farbe/Muster der Kategorien wie in vorheriger Befragung.
> Sichtbar für subsample wave=1 (Preload-Variable)
> 
> Kalendarium B:
> Zeitraum: Januar 2018 bis Dezember 2020
> Kategorien: siehe slc-inter Befragung für cohort=2 (Kohorte 2018). Bitte auch Farbe/Muster der Kategorien wie in vorheriger Befragung.
> Sichtbar für subsample wave=2 or 3 or 4 or 5 (Preload-Variable)

**Comment by christian-fr** [comment]
Die Texte für die pages:

**zwischen_cal_am**, 
**zwischen_cal_ad**, 
**zwischen_cal_bm**,
**zwischen_cal_bd** 

sind geändert.

Ab nächstem Rollout verfügbar.
