### ISSUE TITLE
nstET: em(aa)12: ao's bündig anordnen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#104]
Ich glaube ich würde die ao's versuchen bündig anzuordnen bzw. einzurücken, siehe Screenshot. Was meinst du @jocarstensen 

![grafik](https://user-images.githubusercontent.com/73596957/103528752-c7d1d800-4e84-11eb-8584-03b46d2c7a42.png)

**Comment by jocarstensen** [comment]
Ja, wäre super wenn das ginge.

**Comment by christian-fr** [comment]
Die Texte werden dynamisch/responsiv umgebrochen und die jeweils einleitenden drei Punkte gehören zum Text.
Ein hängender Einzug, der sich an bzw. hinter den drei Punkten ausrichten würde, ist hier leider nicht möglich.
