### ISSUE TITLE
Studium: stu_10 Einblendung des Studienfachs raus

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#105]
tester19 wave 4
@heikQ obwohl ich bei staa04 mein Studienfach und Nebenfach eingegeben habe, erscheint dies auf Seite stu_10 nicht, da: Show q1 IF h_staktsfz01=1 Show q2 IF h_staktsfz01==MISSING. 

![grafik](https://user-images.githubusercontent.com/73596957/103533751-f86a3f80-4e8d-11eb-844b-3433b6dd6e67.png)

**Comment by AliceFoelker** [comment]
@andreaschu hier soll das letzte angegebene Studienfach eingeblendet werden, welches im Episodenmodul auf em(aa)04 eingegeben wurde. Auch wenn dort etwas eingetragen ist, wird hier nichts eingeblendet. Ich befürchte die Hilfsvariable h_staktsfz01 ist falsch?!

**Comment by andreaschu** [comment]
@AliceFoelker Du meinst st(aa)04, nicht em(aa)04, oder? 
Ich glaube, die Bedingung stimmte nicht. Ich habe sie geändert und hoffe es klappt damit. Kann nach dem nächsten Roll-Out getestet werden.

**Comment by AliceFoelker** [comment]
@andreaschu oh ja entschuldige. mit st(aa)04 hast du natürlich recht. Kannst du mir dann (wenn es funktioniert) bitte durchgeben, was du verändert hast, damit ich das auch bei uns im code ändern kann?

**Comment by andreaschu** [comment]
entschuldige, kann doch erst mit dem nächsten Roll-Out getestet werden.
Aber mir ist noch aufgefallen, dass h_staktsfz01 gar nicht auf staa04 gefüllt wird, sondern auf st0005, also in der Notschleife (oder in der letzten?). Also ist es vielleicht doch die falsche Hilfsvariable, die hier eingendet werden soll.

**Comment by AliceFoelker** [comment]
@andreaschu ja dass es die falsche Hilfsvariable ist vermute ich hier auch stark. (Ziel war es hier den zuletzt angegebenen Studiengang einzublenden). Die Umsetzung ist aber falsch.

**Comment by andreaschu** [comment]
ich weiß gar nicht, ob es nur ein zuletzt genannten Fach gibt. Auf Anhieb hab ich es nicht gefunden. Aber im Zweifel kennt sich @jocarstensen bei den Schleifen besser aus.

**Comment by andreaschu** [comment]
Änderung (eb665fc) ab nächstem Roll-Out verfügbar.
