### ISSUE TITLE
Studium: stu_24 Bed. gelöscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#106]
Ich komme, obwohl ich "nein, auf keinen Fall" angekreuzt habe nicht von der Seite
tester19 wave=4

![grafik](https://user-images.githubusercontent.com/73596957/103534083-81817680-4e8e-11eb-9b42-ca1c354f9fde.png)

**Comment by christian-fr** [comment]
Siehe [Programmiervorlage](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul05_Studium.md#_stu_24_): 
hier trifft keine der Bedingungen für die Transitions zu, deshalb kann die page nicht verlassen werden.

Weder
```
GOTO gsh_00 IF
(
	(
		bestwuw_183b =4 
		OR 
		bestwuw_183b =5
	) 
	AND 
	h_studever!=1
) 
OR 
(
	bestwuw_183b == MISSING 
	AND 
	sf_bestwuw_183b =1
)

```

noch 

```
GOTO stu_25 IF
stu_25 IF bestwuw_183b=1 
OR 
bestwuw_183b =2 
OR
bestwuw_183b =3
```

lassen sich im Fall Deines Test-Tokens erfüllen, da hier `h_studever==1` ist.

**Comment by AliceFoelker** [comment]
@heikQ da müssen wir noch mal drüber schauen

**Comment by heikQ** [comment]
@AliceFoelker wenn ich das richtig sehe, ist das AND h_studever!=1 in der ersten oben genannten Bedingung ja überflüssig und ohne müsste es ja dann gehen

**Comment by AliceFoelker** [comment]
@heikQ soll es dann komplett raus oder müsste es AND h_studever=0 heißen?

**Comment by heikQ** [comment]
@AliceFoelker musste m.e. ganz raus können, denn wer da 4 oder 5 sagt, bekommt ja keine nachfragen mehr und marschiert in Gesundheit, egal was auf h_studever ist

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
