### ISSUE TITLE
SozDem: strings PLZ ORT in mobiler Version verrutscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#107]
das sieht noch etwas uneinheitlich aus. Ich würde hier vermutlich bei ao1 ORT und PLZ nebeneinander anordnen. der String ist auch ein wenig zu nach am Doppelpunkt. Ich würde behaupten das gilt für fast alle Orts- und PLZ Angaben (z.B. auch v(aa)10; i(aa)06; em(aa)16. Egal ob quer oder hochkant

**edit: die meisten gefixten Seiten beziehen sich meist nicht auf die dazugehörigen Schleifen und Splits, bitte für alle Schleifen und Splits fixen**

@andreaschu hier kamen leider noch einige Seiten mit zerschossenen oder verrutschten PLZ und ORT strings dazu

- [x] msg_09
- [x] sc(aa)07
- [x] v(aa)10
- [x]  i[a]a06 
- [x] em[a] [a]16
- [x] st[a] [a]10 
- [x] o[a] [a]07
- [x] o[c] [a]05 
- [x] se[a] [a]25 
- [x] se[a] [a]33 
- [x] se[a] [c]49 
- [x] v [a] [b] 10
- [x] sc[a] [b]07 
- [x] st0011

![grafik](https://user-images.githubusercontent.com/73596957/103534924-189afe00-4e90-11eb-8720-d066ea86a8fa.png)
![grafik](https://user-images.githubusercontent.com/73596957/103539929-315be180-4e99-11eb-9b54-692dbf8f7b0b.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#170)  verfügbar

**Comment by vdick** [comment]
Vergisst biite nicht den Browser-Cache zu leeren

**Comment by vdick** [comment]
ab nächsten Rollout (#177 ) verfügbar

**Comment by andreaschu** [comment]
@AliceFoelker mit dem neuen Roll-Out müsste einmal der Cache geleert werden, damit das CSS neu geladen wird. Hast Du das gemacht?

**Comment by AliceFoelker** [comment]
@christian-fr ja habe ich sieht aber immernoch so aus

![grafik](https://user-images.githubusercontent.com/73596957/105377545-3778ee80-5c0b-11eb-95d6-9088a957c74c.png)

**Comment by christian-fr** [comment]
Ist geändert.  Ab nächstem Rollout verfügbar.

- [ ] [vaa10](https://presentation.dzhw.eu/SLC_2018_3b/vaa10.html]
- [ ] [vab10](https://presentation.dzhw.eu/SLC_2018_3b/vab10.html]
- [ ] [vac10](https://presentation.dzhw.eu/SLC_2018_3b/vac10.html]
- [ ] [vad10](https://presentation.dzhw.eu/SLC_2018_3b/vad10.html]
- [ ] [vae10](https://presentation.dzhw.eu/SLC_2018_3b/vae10.html]
- [ ] [vaz10](https://presentation.dzhw.eu/SLC_2018_3b/vaz10.html]
- [ ] [vba10](https://presentation.dzhw.eu/SLC_2018_3b/vba10.html]
- [ ] [vbb10](https://presentation.dzhw.eu/SLC_2018_3b/vbb10.html]
- [ ] [vbc10](https://presentation.dzhw.eu/SLC_2018_3b/vbc10.html]
- [ ] [vbd10](https://presentation.dzhw.eu/SLC_2018_3b/vbd10.html]
- [ ] [vbz10](https://presentation.dzhw.eu/SLC_2018_3b/vbz10.html]
- [ ] [vca10](https://presentation.dzhw.eu/SLC_2018_3b/vca10.html]
- [ ] [vcb10](https://presentation.dzhw.eu/SLC_2018_3b/vcb10.html]
- [ ] [vcc10](https://presentation.dzhw.eu/SLC_2018_3b/vcc10.html]
- [ ] [vcz10](https://presentation.dzhw.eu/SLC_2018_3b/vcz10.html]
- [ ] [vda10](https://presentation.dzhw.eu/SLC_2018_3b/vda10.html]
- [ ] [vdb10](https://presentation.dzhw.eu/SLC_2018_3b/vdb10.html]
- [ ] [vdz10](https://presentation.dzhw.eu/SLC_2018_3b/vdz10.html]
- [ ] [vea10](https://presentation.dzhw.eu/SLC_2018_3b/vea10.html]
- [ ] [vez10](https://presentation.dzhw.eu/SLC_2018_3b/vez10.html]
- [ ] [vza10](https://presentation.dzhw.eu/SLC_2018_3b/vza10.html]

**Comment by andreaschu** [comment]
Die hoffentlich vollständige Liste der obigen Anmerkung:
@vdick der Schleifenbeginn (...aa) ist oft schon gemacht. Ich hab es dennoch immer in der Liste drin.

- [ ] [emaa16](https://presentation.dzhw.eu/SLC_2018_3b/emaa16.html)
- [ ] [emab16](https://presentation.dzhw.eu/SLC_2018_3b/emab16.html)
- [ ] [emac16](https://presentation.dzhw.eu/SLC_2018_3b/emac16.html)
- [ ] [emad16](https://presentation.dzhw.eu/SLC_2018_3b/emad16.html)
- [ ] [emae16](https://presentation.dzhw.eu/SLC_2018_3b/emae16.html)
- [ ] [emaf16](https://presentation.dzhw.eu/SLC_2018_3b/emaf16.html)
- [ ] [emba16](https://presentation.dzhw.eu/SLC_2018_3b/emba16.html)
- [ ] [embb16](https://presentation.dzhw.eu/SLC_2018_3b/embb16.html)
- [ ] [embc16](https://presentation.dzhw.eu/SLC_2018_3b/embc16.html)
- [ ] [embd16](https://presentation.dzhw.eu/SLC_2018_3b/embd16.html)
- [ ] [embe16](https://presentation.dzhw.eu/SLC_2018_3b/embe16.html)
- [ ] [emca16](https://presentation.dzhw.eu/SLC_2018_3b/emca16.html)
- [ ] [emcb16](https://presentation.dzhw.eu/SLC_2018_3b/emcb16.html)
- [ ] [emcc16](https://presentation.dzhw.eu/SLC_2018_3b/emcc16.html)
- [ ] [emcd16](https://presentation.dzhw.eu/SLC_2018_3b/emcd16.html)
- [ ] [emda16](https://presentation.dzhw.eu/SLC_2018_3b/emda16.html)
- [ ] [emdb16](https://presentation.dzhw.eu/SLC_2018_3b/emdb16.html)
- [ ] [emdc16](https://presentation.dzhw.eu/SLC_2018_3b/emdc16.html)
- [ ] [emea16](https://presentation.dzhw.eu/SLC_2018_3b/emea16.html)
- [ ] [emeb16](https://presentation.dzhw.eu/SLC_2018_3b/emeb16.html)
- [ ] [emfa16](https://presentation.dzhw.eu/SLC_2018_3b/emfa16.html)
- [ ] [staa10](https://presentation.dzhw.eu/SLC_2018_3b/staa10.html)
- [ ] [stab10](https://presentation.dzhw.eu/SLC_2018_3b/stab10.html)
- [ ] [stac10](https://presentation.dzhw.eu/SLC_2018_3b/stac10.html)
- [ ] [stad10](https://presentation.dzhw.eu/SLC_2018_3b/stad10.html)
- [ ] [stae10](https://presentation.dzhw.eu/SLC_2018_3b/stae10.html)
- [ ] [stba10](https://presentation.dzhw.eu/SLC_2018_3b/stba10.html)
- [ ] [stbb10](https://presentation.dzhw.eu/SLC_2018_3b/stbb10.html)
- [ ] [stbc10](https://presentation.dzhw.eu/SLC_2018_3b/stbc10.html)
- [ ] [stbd10](https://presentation.dzhw.eu/SLC_2018_3b/stbd10.html)
- [ ] [stca10](https://presentation.dzhw.eu/SLC_2018_3b/stca10.html)
- [ ] [stcb10](https://presentation.dzhw.eu/SLC_2018_3b/stcb10.html)
- [ ] [stcc10](https://presentation.dzhw.eu/SLC_2018_3b/stcc10.html)
- [ ] [stda10](https://presentation.dzhw.eu/SLC_2018_3b/stda10.html)
- [ ] [stdb10](https://presentation.dzhw.eu/SLC_2018_3b/stdb10.html)
- [ ] [stea10](https://presentation.dzhw.eu/SLC_2018_3b/stea10.html)
- [ ] [seaa33](https://presentation.dzhw.eu/SLC_2018_3b/seaa33.html)
- [ ] [seab33](https://presentation.dzhw.eu/SLC_2018_3b/seab33.html)
- [ ] [seac33](https://presentation.dzhw.eu/SLC_2018_3b/seac33.html)
- [ ] [sead33](https://presentation.dzhw.eu/SLC_2018_3b/sead33.html)
- [ ] [seae33](https://presentation.dzhw.eu/SLC_2018_3b/seae33.html)
- [ ] [seba33](https://presentation.dzhw.eu/SLC_2018_3b/seba33.html)
- [ ] [sebb33](https://presentation.dzhw.eu/SLC_2018_3b/sebb33.html)
- [ ] [sebc33](https://presentation.dzhw.eu/SLC_2018_3b/sebc33.html)
- [ ] [sebd33](https://presentation.dzhw.eu/SLC_2018_3b/sebd33.html)
- [ ] [seca33](https://presentation.dzhw.eu/SLC_2018_3b/seca33.html)
- [ ] [secb33](https://presentation.dzhw.eu/SLC_2018_3b/secb33.html)
- [ ] [secc33](https://presentation.dzhw.eu/SLC_2018_3b/secc33.html)
- [ ] [seda33](https://presentation.dzhw.eu/SLC_2018_3b/seda33.html)
- [ ] [sedb33](https://presentation.dzhw.eu/SLC_2018_3b/sedb33.html)
- [ ] [seea33](https://presentation.dzhw.eu/SLC_2018_3b/seea33.html)
- [ ] [seaa49](https://presentation.dzhw.eu/SLC_2018_3b/seaa49.html)
- [ ] [seab49](https://presentation.dzhw.eu/SLC_2018_3b/seab49.html)
- [ ] [seac49](https://presentation.dzhw.eu/SLC_2018_3b/seac49.html)
- [ ] [sead49](https://presentation.dzhw.eu/SLC_2018_3b/sead49.html)
- [ ] [seae49](https://presentation.dzhw.eu/SLC_2018_3b/seae49.html)
- [ ] [seba49](https://presentation.dzhw.eu/SLC_2018_3b/seba49.html)
- [ ] [sebb49](https://presentation.dzhw.eu/SLC_2018_3b/sebb49.html)
- [ ] [sebc49](https://presentation.dzhw.eu/SLC_2018_3b/sebc49.html)
- [ ] [sebd49](https://presentation.dzhw.eu/SLC_2018_3b/sebd49.html)
- [ ] [seca49](https://presentation.dzhw.eu/SLC_2018_3b/seca49.html)
- [ ] [secb49](https://presentation.dzhw.eu/SLC_2018_3b/secb49.html)
- [ ] [secc49](https://presentation.dzhw.eu/SLC_2018_3b/secc49.html)
- [ ] [seda49](https://presentation.dzhw.eu/SLC_2018_3b/seda49.html)
- [ ] [sedb49](https://presentation.dzhw.eu/SLC_2018_3b/sedb49.html)
- [ ] [seea49](https://presentation.dzhw.eu/SLC_2018_3b/seea49.html)
- [ ] [scab07](https://presentation.dzhw.eu/SLC_2018_3b/scab07.html)
- [ ] [scac07](https://presentation.dzhw.eu/SLC_2018_3b/scac07.html)
- [ ] [scad07](https://presentation.dzhw.eu/SLC_2018_3b/scad07.html)
- [ ] [scae07](https://presentation.dzhw.eu/SLC_2018_3b/scae07.html)
- [ ] [scaz07](https://presentation.dzhw.eu/SLC_2018_3b/scaz07.html)
- [ ] [scaa07](https://presentation.dzhw.eu/SLC_2018_3b/scaa07.html)
- [ ] [st0010](https://presentation.dzhw.eu/SLC_2018_3b/st0010.html)
- [ ] [iaa06](https://presentation.dzhw.eu/SLC_2018_3b/iaa06.html)
- [ ] [iba06](https://presentation.dzhw.eu/SLC_2018_3b/iba06.html)
- [ ] [ica06](https://presentation.dzhw.eu/SLC_2018_3b/ica06.html)
- [ ] [ida06](https://presentation.dzhw.eu/SLC_2018_3b/ida06.html)
- [ ] [iea06](https://presentation.dzhw.eu/SLC_2018_3b/iea06.html)
- [ ] [iza06](https://presentation.dzhw.eu/SLC_2018_3b/iza06.html)
- [ ] [oaa07](https://presentation.dzhw.eu/SLC_2018_3b/oaa07.html)
- [ ] [oab07](https://presentation.dzhw.eu/SLC_2018_3b/oab07.html)
- [ ] [oca05](https://presentation.dzhw.eu/SLC_2018_3b/oca05.html)
- [ ] [vaa10](https://presentation.dzhw.eu/SLC_2018_3b/vaa10.html)
- [ ] [vab10](https://presentation.dzhw.eu/SLC_2018_3b/vab10.html)
- [ ] [vac10](https://presentation.dzhw.eu/SLC_2018_3b/vac10.html)
- [ ] [vad10](https://presentation.dzhw.eu/SLC_2018_3b/vad10.html)
- [ ] [vae10](https://presentation.dzhw.eu/SLC_2018_3b/vae10.html)
- [ ] [vaz10](https://presentation.dzhw.eu/SLC_2018_3b/vaz10.html)
- [ ] [vba10](https://presentation.dzhw.eu/SLC_2018_3b/vba10.html)
- [ ] [vbb10](https://presentation.dzhw.eu/SLC_2018_3b/vbb10.html)
- [ ] [vbc10](https://presentation.dzhw.eu/SLC_2018_3b/vbc10.html)
- [ ] [vbd10](https://presentation.dzhw.eu/SLC_2018_3b/vbd10.html)
- [ ] [vbz10](https://presentation.dzhw.eu/SLC_2018_3b/vbz10.html)
- [ ] [vca10](https://presentation.dzhw.eu/SLC_2018_3b/vca10.html)
- [ ] [vcb10](https://presentation.dzhw.eu/SLC_2018_3b/vcb10.html)
- [ ] [vcc10](https://presentation.dzhw.eu/SLC_2018_3b/vcc10.html)
- [ ] [vcz10](https://presentation.dzhw.eu/SLC_2018_3b/vcz10.html)
- [ ] [vda10](https://presentation.dzhw.eu/SLC_2018_3b/vda10.html)
- [ ] [vdb10](https://presentation.dzhw.eu/SLC_2018_3b/vdb10.html)
- [ ] [vdz10](https://presentation.dzhw.eu/SLC_2018_3b/vdz10.html)
- [ ] [vea10](https://presentation.dzhw.eu/SLC_2018_3b/vea10.html)
- [ ] [vez10](https://presentation.dzhw.eu/SLC_2018_3b/vez10.html)
- [ ] [vza10](https://presentation.dzhw.eu/SLC_2018_3b/vza10.html)

**Comment by vdick** [comment]
ab nächsten Rollout (#218 ) verfügbar

**Comment by AliceFoelker** [comment]
@vdick @andreaschu bei st0010 stimmt noch was nicht

![grafik](https://user-images.githubusercontent.com/73596957/105496526-e118b800-5cbd-11eb-9d77-b0a444e8a093.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#221 ) verfügbar

**Comment by AliceFoelker** [comment]
@andreaschu @vdick jetzt fehlt nur noch st0011
![grafik](https://user-images.githubusercontent.com/73596957/105505050-c566df00-5cc8-11eb-8fe8-7042e21595ff.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#221 ) verfügbar
