### ISSUE TITLE
Studium: stu_13 Leerzeichen einfügen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#110]
hier fehlen Leerzeichen
![grafik](https://user-images.githubusercontent.com/73596957/103536736-5e0cfa80-4e93-11eb-8dc3-8d7fd028590c.png)

**Comment by christian-fr** [comment]
Leerzeichen sind ergänzt. Ab nächstem Rollout verfügbar.
