### ISSUE TITLE
Studium: stu_16 & stu_20 Punkte nach aos oder nicht?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#111]
@heikQ stu_16: am Ende der ao1- ao3 wurden Punkte gesetzt. Bei stu_20 nicht. Wollen wir es einheitlich machen? Im KP ist es mal so mal so geschrieben. ich würde dazu tendieren die Punkte bei stu_20 zu setzen.

![grafik](https://user-images.githubusercontent.com/73596957/103537444-b5f83100-4e94-11eb-9ad8-41293185e028.png)

**Comment by heikQ** [comment]
@AliceFoelker ja, lass punkte setzen

**Comment by christian-fr** [comment]
Punkte sind hinzugefügt. Ab nächstem Rollout verfügbar.
