### ISSUE TITLE
neue Zwischenseiten austauschen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#113]
Neue Dateien der Zwischenseiten in 
https://github.com/dzhw/studienberechtigte_2018.3b/issues/25#issue-756389048

> **neues Layout der Zwischenseiten**
> [fertige Zwischenseiten (2).zip](https://github.com/dzhw/studienberechtigte_2018.3b/files/5764763/fertige.Zwischenseiten.2.zip)
> @christian-fr @andreaschu das Layout der Zwischenseiten hat sich geändert.

**Comment by christian-fr** [comment]
Sind durch die neuen  ersetzt. Ab nächstem Rollout verfügbar.
