### ISSUE TITLE
zwischen_cal_bd: Anweisung zum Ausfüllen auf IPhone 5 fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#114]
lt. SHK werden ihr die Anweisungen zum Ausfüllen auf ihrem IPhone 5 nicht angezeigt, auch nicht nach dem Drehen. tester150 wave2

![grafik](https://user-images.githubusercontent.com/73596957/103539009-8d256b00-4e97-11eb-9f1b-0a53d3186538.png)

**Comment by christian-fr** [comment]
@vdick @dzhwmeisner Ist offenbar ein Bug in WebKit für iOS: lange alt-Texte werden nicht angezeigt.


Als Workaround packe ich den alt-Text als Text unter die GIF-Animation. Ab nächstem Rollout verfügbar.
