### ISSUE TITLE
Episoden: sc0001 Doppelpunkt nach "zwar" + mehr Abstand in mobilVersion

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#115]
+ Kann man es dann auch in der mobilen Version etwas entzerren, bzw. den string nicht direkt an den Buchstaben setzen?
![grafik](https://user-images.githubusercontent.com/73596957/103539417-51d76c00-4e98-11eb-8286-ead087975cbc.png)

![grafik](https://user-images.githubusercontent.com/73596957/103539259-0329d200-4e98-11eb-9963-e4d64a020b9c.png)

**Comment by AliceFoelker** [comment]
@jocarstensen falls das mit dem Doppelpunkt geändert werden soll, müsste es noch im Code geändert werden, daran habe ich nicht rumgefummelt.

**Comment by jocarstensen** [comment]
Kann ich gern machen. Finde sowohl Doppelpunkt als auch Entzerren gut.

**Comment by christian-fr** [comment]
Doppelpunkt ist ergänzt.

**Comment by christian-fr** [comment]
Abstand ist eingefügt. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
der Doppelpunkt ist fixed @christian-fr jetzt ist der string aber etwas zu tief oder?
![grafik](https://user-images.githubusercontent.com/73596957/103555379-74757f00-4eb0-11eb-8556-7297f8fb4f4f.png)

**Comment by christian-fr** [comment]
Textfeld ist nun auch auf schmalen Bildschirmen auf gleicher Höhe.
Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@christian-fr Hochkant ist es immernoch iwie eingerückt und im Querformat iwie verrutscht. Bei der iPhoneX/XS  und iPad Version sieht es Top aus!
![grafik](https://user-images.githubusercontent.com/73596957/104447704-728c7980-559c-11eb-86ea-2af81d3fa78e.png)
![grafik](https://user-images.githubusercontent.com/73596957/104447749-80da9580-559c-11eb-94cf-c686ee8d32b0.png)
![grafik](https://user-images.githubusercontent.com/73596957/104447856-a9628f80-559c-11eb-93b5-0029b55df812.png)
