### ISSUE TITLE
Episoden: vaa23 Leerzeichen hinzufügen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#116]
@jocarstensen Hier würde ich nach Dezember 2020 ein Leerzeichen hinzufügen, evtl. auch nach den ... bei ao1 - ao4?
![grafik](https://user-images.githubusercontent.com/73596957/103540644-556bf280-4e9a-11eb-944e-189864070e00.png)

**Comment by jocarstensen** [comment]
Kann ich ändern, wenn es dadurch nicht inkonsistent wird. @AliceFoelker Hast Du darauf geachtet, ob und wie wir ansonsten einheitlich sind?

**Comment by AliceFoelker** [comment]
@jocarstensen ich bin bemüht es überall so einheitlich zu machen bzw. es anzugleichen. Beispiel:
![grafik](https://user-images.githubusercontent.com/73596957/103547926-4f2f4380-4ea5-11eb-8a38-c9444250e74a.png)

**Comment by jocarstensen** [comment]
ok, dann passe ich es an

**Comment by christian-fr** [comment]
Leerzeichen sind hinzugefügt. Ab nächstem Rollout verfügbar.
