### ISSUE TITLE
Episoden: em(aa)42 Leerzeichen entfernen?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#117]
@jocarstensen hier das Leerzeichen hinter dem Slash entfernen?
Darüber hinaus würde ich überlegen die Zahlen und Skalenendpunktbeschriftung zu tauschen damit es einheitlicher ist?!

![grafik](https://user-images.githubusercontent.com/73596957/103541164-46397480-4e9b-11eb-86af-4361d8d0a1e3.png)

**Comment by jocarstensen** [comment]
@AliceFoelker Ist das unabhängig von der Bildschirmgröße immer vertikal? Bei horizontalen Skalen macht es Sinn, die Labels vor den Zahlen zu haben. Aber wenn es immer vertikal ist, kann und sollten wir es ändern.

Ein anderer Punkt: Das Itemwording geht hier etwas unter, da als "is" formatiert. Außerdem ist es inkonsistent zu emaa43. @se-lang Was meinst Du? Auf horizontal drehen und formatieren wie emaa43?

**Comment by AliceFoelker** [comment]
@jocarstensen lt. dem code ist für alle Bildschirmgrößen >vertikal< eingetragen. Ich komme ehrlich gesagt mit euren codes noch nicht so ganz zurecht. Die sehen anders aus als unsere, weshalb ich da nicht rumfummel.

![grafik](https://user-images.githubusercontent.com/73596957/103548410-0deb6380-4ea6-11eb-8c11-280e640382ba.png)

**Comment by se-lang** [comment]
@AliceFoelker @jocarstensen Also generell meine ich, dass wir uns da sicher was bei gedacht haben. Zu den einzelnen Punkten:
- ja die Skala ist hier immer vertikal und das ist im Grunde nicht ganz konsequent insb. in Bezug auf emaa43, aber das ist meine ich Absicht. Auf mobilen Endgeräten sollte emaa43 als Karusell angezeigt werden. Entsprechend ist dann die Skala vertikal. Setzen wir emaa42 auf horizontal, wird sie immer horizontal angezeigt was dazu verführt in Landscape zu wechseln. Dann ist das Karusell auf emaa43 aber doof, weil es nicht ganz auf den Bildschirm passt (zumindest bei Smartphones). Insofern würde ich die Richtung eher nicht ändern (neben "never change a running system"). Außerdem könnte das auch noch häufiger vorkommen.
- Zahl hinter der Beschriftung war damals meine ich eine Entscheidung für eine einheitliche Lösung unabhängig von der Skalenausrichtung (auch weil u.A. hier die beiden Richtungen direkt hintereinander kommen, hab das aber nich überprüft). Das müsste man dann außerdem auch im restlichen Episodenmodul prüfen und ggf. anpassen.
- Formatierung der zweiten Teils des Fragetextes: Auch hier meine ich das war damals eine bewusste Entscheidung, weil das optisch vom restlichen Fragetext abgehoben werden sollte und es dafür nicht allzuviele Möglichkeiten gibt. @jocarstensen Bei emaa43 ist der zweite Teil des Fragetextes ("In Bezug auf...") auch als instruction formatiert, also genauso wie bei emaa42. Oder was meinst Du?

**Comment by jocarstensen** [comment]
@se-lang Zum dritten Punkt: Bei emaa43 ist nur der gemeinsame Teil der Items als is formatiert, der Rest als Item. Was ja bei einer Batterie auch logisch ist. Im Gegensatz dazu ist aber bei emaa42 das gesamte Item als is formatiert. Das finde ich gefährlich, weil is oft überlesen werden, und die Frage dann zu einer Globaladäquanzfrage würde.

Zu den anderen Punkten: Das sind gute Argumente. Vor dem Hintergrund würde ich für Belassen votieren.

**Comment by se-lang** [comment]
Ok, ich verstehe was du meinst. Im Grunde wäre es ok so wie es ist, wenn emaa42 Teil des Karusells von emaa43 wäre (dann wäre es äquivalent). Das geht aber wegen der unterschiedlichen Skalen nicht. 
@jocarstensen @AliceFoelker Nachdem das nicht in die Funktion des Fragebogens eingreift könnte man das denke ich ändern.

**Comment by jocarstensen** [comment]
Geht eine Batterie mit nur einem Item?

**Comment by AliceFoelker** [comment]
> 
> 
> Geht eine Batterie mit nur einem Item?

ich glaube >nein<, sicher bin ich mir aber nicht. eine unschöne, Pfusch-am-Bau-Variante wäre vielleicht 2 Items zu erstellen aber durch Einblendbedingungen nur eine einzublenden. z.B. wie hier: @jocarstensen meinst du sowas in der Art?
![grafik](https://user-images.githubusercontent.com/73596957/103641688-6c6e1b80-4f52-11eb-8fa8-7fd32ac07840.png)

**Comment by se-lang** [comment]
Denkt bitte dran, dass das nicht nur eine Stelle ist und wir da quasi am offenen Herzen operieren. Ich kann da gerne helfen, falls notwendig, würde aber für eine Minimalinvasive Lösung plädieren.
Batterie mit nur einem Item (falls das geht) ist insofern bisschen unschön, weil man die Steuerelemente des Karusells hat ohne, dass die irgendwas bewirken. Wie so oft die Frage nach dem kleineren Übel.

**Comment by jocarstensen** [comment]
@se-lang Ja, da hast Du Recht.

Eine Lösung wäre vielleicht noch, eine Leerzeile zwischen qt und is einzufügen. Da müsste mal jemand in den alten Screenshots gucken, ob das nicht eh schon immer so war. Wenn ich mich recht erinnere, war das letztes Jahr global gesteuert und aus Vergleichbarkeitsgründen sollte es dann jetzt auch so sein.

**Comment by AliceFoelker** [comment]
@jocarstensen @se-lang ok, also einfach **alles** so lassen?!

**Comment by jocarstensen** [comment]
Ja
