### ISSUE TITLE
Ausbildung: aus_04 Leerzeichen eingefügt

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#118]
@heikQ hier Leerzeichen vor ... setzen? Iwie ist es relativ uneinheitlich, ob dann vor den aos auch noch mal ... stehen.
![grafik](https://user-images.githubusercontent.com/73596957/103541410-ab8d6580-4e9b-11eb-9118-9005d357d2a5.png)

**Comment by heikQ** [comment]
@AliceFoelker im Frahetext kommt ein Leerzeichen zwischen dem letzten Wort und den Punkten. Bei den AO´s brauch es am Anfang ja eigentlich keins mehr

**Comment by christian-fr** [comment]
Ist übernommen, ab nächstem Rollout verfügbar.
