### ISSUE TITLE
Modul-Studium: Fehler in Transition (stu_06)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#12]
Fehler in PV: von stu_06 muss auf stu_24 gefiltert werden, nicht nach stu_25.

GOTO stu_24

**Comment by AliceFoelker** [comment]
@andreaschu wäre das jetzt das Vorgehen, wie ein Fehler kommuniziert wird und/ oder würde ich den Fehler jetzt selbst im Code ändern? Ich bin da noch etwas auf Anleitung angewiesen.

**Comment by andreaschu** [comment]
Grundsätzlich schon. Aber lass uns kurz telefonieren.

**Comment by andreaschu** [comment]
Ist korrigiert und kann getestet werden.

**Comment by AliceFoelker** [comment]
fixed
