### ISSUE TITLE
SozDem: msg_15 strings etwas entzerren

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#122]
hier ist der erste string ziemlich nah an dem Punkt zum ankreuzen. Nach Möglichkeit ein bisschen verkleinern.
+ ist es gewollt, dass die Punkte zum ankreuzen abwechselnd größer und mal kleiner sind?

![grafik](https://user-images.githubusercontent.com/73596957/103545152-771ca800-4ea1-11eb-8c3e-e8c0dab803ca.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#123 ) verfügbar

**Comment by AliceFoelker** [comment]
@christian-fr ich habe da ein bisschen gezoomt, darf das dann passieren?

![grafik](https://user-images.githubusercontent.com/73596957/103636626-8c014600-4f4a-11eb-93e4-d50c1ffc2465.png)

**Comment by christian-fr** [comment]
@AliceFoelker Ich kann den Fehler gerade nicht reproduzieren. Kannst Du die page nochmal aufrufen und dann mit `Strg + Shift + R` den CSS-Cache leeren und neu laden lassen?

**Comment by christian-fr** [comment]
@vdick 
Bitte die page mit Smartphone testen - das linke Textfeld lässt sich nicht auswählen, wenn das Smartphone hochkant gehalten wird.

**Comment by AliceFoelker** [comment]
@christian-fr Dieses Problem hat sich offenbar erledigt. Das sieht jetzt ordentlich aus
> @AliceFoelker Ich kann den Fehler gerade nicht reproduzieren. Kannst Du die page nochmal aufrufen und dann mit
> `Strg + Shift + R`
> den CSS-Cache leeren und neu laden lassen?


@vdick ABER dieser tritt bei mir auch auf. Wird das jetzt in diesem Issue weiterverfolgt oder soll ich ein neues dafür öffnen?

> @vdick
> Bitte die page mit Smartphone testen - das linke Textfeld lässt sich nicht auswählen, wenn das Smartphone hochkant gehalten wird.

**Comment by christian-fr** [comment]
> Wird das jetzt in diesem Issue weiterverfolgt oder soll ich ein neues dafür öffnen?

@AliceFoelker Wird hier weiter bearbeitet.

**Comment by vdick** [comment]
fixed, ab nächsten Rollout(#163 ) verfügbar
