### ISSUE TITLE
Fortschrittsbalken auch auf Zwischenseiten der Episoden

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#124]
Forschrittsbalken_4 
![grafik](https://user-images.githubusercontent.com/73596957/103551556-c87d6500-4eaa-11eb-84a5-ee359ba934a6.png)
kommt bitte noch auf folgende Seiten:
**zwischen_sc, zwischen_st, zwischen_v, zwischen_t, zwischen_i, zwischen_em, zwischen_u, zwischen_o**

https://github.com/dzhw/studienberechtigte_2018.3b/issues/75#issuecomment-747454316
> Zur Kennnisnahme: die einzigen pages **ohne Fortschrittsbalken** sind nun (Stand: 17.12.2020 14:57h):
> 
> `msg_21, zwischen_k, zwischen_sc, zwischen_st, zwischen_v, zwischen_t, zwischen_i, zwischen_em, zwischen_u, zwischen_o, zwischen_epi, debug, end`

**Comment by heikQ** [comment]
@AliceFoelker okies, können wir machen.

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@christian-fr ist fixed - entschuldige jetzt fehlt nur noch zwischen_epi mit demselben Balken
