### ISSUE TITLE
Studium: stu_07 Item 2 Skalenbeschriftung geändert

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#125]
ändern zu schwer/leicht - wie im Konstruktpapier
![grafik](https://user-images.githubusercontent.com/73596957/103552249-e4cdd180-4eab-11eb-901e-637268a70da8.png)

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
