### ISSUE TITLE
Fortschrittsbalken in Ausfüllhinweis anders

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#129]
zwischen_cal_ad
ist das in diesem Fall "egal"?
Davon abgesehen sind die Befragungszeiträume in den Einleitungstexten falsch - schon in #102 festgehalten (ist aber noch nichts passiert)
![grafik](https://user-images.githubusercontent.com/73596957/103638874-ce785200-4f4d-11eb-9b40-3a7aa31e913d.png)

**Comment by heikQ** [comment]
muss Dezember 2020 sein. Die gifs für die Ausfüllanweisung muss ich noch basteln. Das ist das alte oder?

**Comment by AliceFoelker** [comment]
> muss Dezember 2020 sein. Die gifs für die Ausfüllanweisung muss ich noch basteln. Das ist das alte oder?

ja und da es wave 1 ist Januar 2020 und Dezember 2020 aber das ist in einem anderen Issue.
Das sieht ganz so aus wie das alte, da dort noch die alten Fortschrittsbalken drin sind. @heikQ soll ich dann dieses Issue schließen oder noch drin lassen?

**Comment by heikQ** [comment]
Der Text kann ja bereits auf das richtige Datum gesetzt werden, gifs tauschen wir, wenn ich die habe
