### ISSUE TITLE
Kalendarium mobile Version fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#130]
iPhone5 tester 154 wave 1
lt. SHK kann im Kalendarium 1 eine Aktivität ausgewählt aber nicht eingetragen werden, da keine Zeitleiste vorhabenden ist

![grafik](https://user-images.githubusercontent.com/73596957/103643995-e8b62e00-4f55-11eb-98fc-266c57dd4d7c.png)

**Comment by andreaschu** [comment]
Sollte nun gefixt sein.

**Comment by AliceFoelker** [comment]
fixed
