### ISSUE TITLE
Episoden: sc(aa)19 fehlerhafte mobile Darstellung bei Note mit Komma

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#131]
iPhone5 tester 155 wave2
lt. SHK wird ihr beim Eintragen der Note als Dezimalzahl lediglich "..." angezeigt. Auch beim Testen mit einem anderen testertoken.

![grafik](https://user-images.githubusercontent.com/73596957/103644603-ebfde980-4f56-11eb-9f7c-0f5b3404f28b.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#123 ) verfügbar

**Comment by vdick** [comment]
sorry, erst ab  Rollout (#137  ) verfügbar
