### ISSUE TITLE
End: Befragungsabschluss/ Adressaktualisierung?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#132]
@heikQ Wie soll die Befragung letztlich abgeschlossen werden? derzeit so

![grafik](https://user-images.githubusercontent.com/73596957/103651343-bc081380-4f61-11eb-8e4e-119bd44b7082.png)
![grafik](https://user-images.githubusercontent.com/73596957/103651368-c4604e80-4f61-11eb-9a51-4dd0b6ad7f0b.png)

**Comment by andreaschu** [comment]
@AliceFoelker auch hierfür bitte eine PV schreiben. Vielen Dank!

**Comment by AliceFoelker** [comment]
@andreaschu ich habe die Info erhalten, dass das Befragungsende genauso wie in der letzten Befragung (2018.3b) ablaufen soll.
(Anmerkungen/ Adressaktualisierung etc.). Braucht ihr dann dafür noch mal eine extra PV?
