### ISSUE TITLE
Wiedereinstieg in Befragung nach Pause immer von vorn

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#133]
Wenn man langer Zeit aus der Befragung gekickt wird oder pausiert und zu einem anderen Zeitpunkt weitermachen will und sicher wieder neu einloggt, beginnt man wieder von vorn und nicht an der Stelle an der man aufgehört hat. Kann man das ändern?

**Comment by christian-fr** [comment]
Die Befragung, durch die ihr euch gerade klicken könnt, ist in einem Test-Modus: durch diesen können alle Seiten angesprungen werden, indem man die pagenamen einfach in der Adresszeile des Browsers eingibt.

Dieser Test-Modus geht damit einher, dass zwei Funktionen beeinträchtigt werden: wenn hintereinander mehrere pages gezielt aufgerufen werden, funktionieren Sprünge durch den "Zurück"-Button bspw. nicht immer korrekt - in der fertigen Befragung klappt das dann aber.
Ebenso wird im Test-Modus nach einem erneuten Login per Token immer wieder die Startseite angezeigt. In der fertigen Befragung landen die Befragten dann auf der zuletzt besuchten Seite.

**Comment by AliceFoelker** [comment]
@christian-fr danke für die ausführlich Erklärung
