### ISSUE TITLE
Episoden: em0001 Werkverträge = Werkstudenten?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#134]
@jocarstensen lt. Verena haben wir bei dem Begriff "Werkverträge" in der Vergangenheit immer wieder Überdurchschnittlich viele Werkstudenten gehabt. Ist das so gedacht? Wenn nein, dann vielleicht im Anleitungstext klarmachen?

**Comment by jocarstensen** [comment]
Ja, das Problem ist uns bewusst. Eine Änderung würde aber massiv in die Funktionalität (Weiterleitung in andere Module) eingreifen und damit die Vergleichbarkeit zu 2018.3b einschränken. So weitreichende Änderungen können wir für diese Erhebung am Epimodul nicht machen.
