### ISSUE TITLE
Episoden: i0001 wording

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#135]
@jocarstensen 
Das klingt etwas holprig oder?
![grafik](https://user-images.githubusercontent.com/73596957/103652127-ec9c7d00-4f62-11eb-9b58-56bc7a944e96.png)
Kann man auch die Erläuterung der Begrifflichkeit einfach eine Klammer direkt dahinter setzen?

Also: Damit meinen wir **keine** Anerkennungspraktika (auch Anerkennungsjahr oder Berufspraktikum genannt) zur staatlichen Anerkennung nach dem Studium.

auch das mit dem Anerkennungsjahr bzw. Praktikum hat sich im Bezug auf https://github.com/dzhw/studienberechtigte_2018.3b/issues/5#issuecomment-754004673 geklärt. 
Aber wäre es dann nicht sinnvoll das iwie in der Aktivitätenlegende mit aufzunehmen?

**Comment by jocarstensen** [comment]
Nein, bitte keine Änderungen am Wording oder der Aktivitätenliste wegen Vergleichbarkeit mit 2018.3a!

**Comment by AliceFoelker** [comment]
@jocarstensen achso, eine Sache noch: Wenn ich jedoch vom Kalendarium aus direkt in das Modul auf iaa01 gefiltert werde bleibt diese Info mit dem Anerkennungspraktikum aus, da ich ja nicht auf i0001 lande. Ist das ok so? so könnten ja dennoch Anerkennungspraktika mit reinrutschen.

**Comment by jocarstensen** [comment]
Ja, das ist leider unglücklich. Das müssen wir für eine Überarbeitung im Auge behalten, können es aber wegen der Vergleichbarkeit nicht berücksichtigen.
