### ISSUE TITLE
Episoden: em0048 zwei aos parallel auswählbar

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#136]
man kann sowohl eine Eingabe bei der Stundenzahl als auch "keine feste Arbeitszeit" ankreuzen. Was wird dann letztendlich gezählt? Soll das so oder soll nur eine Möglichkeit bestehen?

![grafik](https://user-images.githubusercontent.com/73596957/103653700-325a4500-4f65-11eb-9ac7-527cbe29f935.png)

**Comment by jocarstensen** [comment]
Wenn ich mich recht erinnere haben wir das Problem letztes Jahr schon recht ausführlich diskutiert und es war leider nicht anders möglich. Das wäre auch eine relativ gravierende Änderungen, die die Vergleichbarkeit mit 2018.3b einschränkt.

**Comment by AliceFoelker** [comment]
ok, damit close ich das Issue
