### ISSUE TITLE
Kalendarium - Hilfsvariablen werden nicht befüllt

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#138]
Obwohl Heiko und ich den **gleichen Browser** (Mozilla Firefox)  und schließlich auch den selben tester23 verwendet haben, bleiben in zwischen_k seine Hilfsvariablen leer während meine gefüllt wurden. Wir haben beide zuvor den cache gelöscht. Dementsprechend hat die Filterung des Kalendariums bei Heiko auch nicht funktioniert und er ist in jedem Episodenmodul gelandet. Was ist da passiert? siehe auch https://github.com/dzhw/studienberechtigte_2018.3b/issues/5#issuecomment-753820350

Alice:
![grafik](https://user-images.githubusercontent.com/73596957/103666884-80774480-4f75-11eb-8ad3-a6e7394f17f1.png)
![grafik](https://user-images.githubusercontent.com/73596957/103666813-689fc080-4f75-11eb-9308-a40f33797f25.png)

Heiko:
![grafik](https://user-images.githubusercontent.com/73596957/103666962-9ab12280-4f75-11eb-8bad-e4d0ed7af034.png)

Nachtrag Alice: Wenn ich z.B. im tester26 das Kalendarium befülle bleiben anschließend auf zwischen_k nun auch bei mir alle Hilfsvariablen leer. Bei tester27 hat es wieder funktioniert?!?!?!

**Comment by andreaschu** [comment]
Kann getestet werden.

**Comment by AliceFoelker** [comment]
Wenn ich das richtig sehe wird h_studakt nicht befüllt.
Auch h_erwerbever und akt werden nicht befüllt? 

die rot angekreuzten Hilfsvariablen werden im Kalendarium gar nicht befüllt oder? könnten also "theoretisch" raus?!
die Hilfsvariable für Praktikum kann ich weder auf zwischen_k noch auf hilfsvar finden.
![grafik](https://user-images.githubusercontent.com/73596957/104166875-bac06600-53fb-11eb-85ec-9b566d762d63.png)
![grafik](https://user-images.githubusercontent.com/73596957/104167008-ee02f500-53fb-11eb-918b-eb36c2a0b909.png)
![grafik](https://user-images.githubusercontent.com/73596957/104168114-cb71db80-53fd-11eb-9d13-164e1ee2744c.png)

**Comment by heikQ** [comment]
raus können sie nicht. Einige werden im Episodenmodul gefüllt.

**Comment by AliceFoelker** [comment]
ne ganz raus nicht. Aber zwischen_k ist ja dafür da die Befüllung aus dem Kalendarium zu prüfen oder? Und da werden diese Hilfsvariablen nicht gefüllt. Kann aber auch einfach drin bleiben. Dachte nur für die Übersicht.
**Wichtiger ist in jedem Fall, dass stud_akt usw. nicht befüllt werden.**
> 
> raus können sie nicht. Einige werden im Episodenmodul gefüllt.

**Comment by andreaschu** [comment]
h_studakt wird erst auf zwischen_st gefüllt.
h_erwerbakt wird im Episodenmodul befüllt, und zwar in em[a]a01 und em0004 (wird aber auch nicht für die Filterführung verwendet.
h_erwerbever wird im Epi-Modul Erwerbstätigkeit befüllt em0001, em[a]a01 und wird auch nicht für Filterung oder Einblendung verwendet.

**Comment by jocarstensen** [comment]
Ok, ich versuche mal, das eigentliche Problem nachzuvollziehen.
- h_studakt wird nicht befüllt --> Sollte laut HV-Liste auf zwischen_k befüllt werden, da ist aber kein Trigger
- h_erwerbakt und h_erwerbever werden nicht befüllt --> Werden laut HV-Liste nicht mehr benötigt.
- h_dualaus und h_auslandever --> werden nicht im Kalendarium befüllt.
- h_selbakt --> steht nicht in der HV-Liste. Macht auch im Kalendarium keinen Sinn, da dort nicht erhoben. Wo kommt die her? Wird die benötigt?
- staktsfz01 --> Wird nicht im Kalendarium gefüllt. Warum ist die in der Liste? Es gibt noch elf weitere Studienfach-HVs, aber ich wüsste nicht, warum die hier stehen müssen.

**Comment by jocarstensen** [comment]
@andreaschu h_studakt sollte laut HV-Liste auch schon aus dem Kalendarium befüllt werden. Also fehlt der Trigger auf zwischen_k.

**Comment by andreaschu** [comment]
@jocarstensen hm, das war beim letzten Mal auch nicht der Fall.

**Comment by AliceFoelker** [comment]
@jocarstensen das hast du alles richtig nachvollzogen bzw. zusammengefasst.
Warum szaktsfz01 auf zwischen_k ist kann ich auch nicht nachvollziehen. ABER auf **hilfsvar** machen die Studiengänge und Fächer für mich schon Sinn, da wir im weiteren verlauf mit Einblendungen arbeiten.


>     * staktsfz01 --> Wird nicht im Kalendarium gefüllt. Warum ist die in der Liste? Es gibt noch elf weitere Studienfach-HVs, aber ich wüsste nicht, warum die hier stehen müssen.

**Comment by jocarstensen** [comment]
@AliceFoelker Dann fehlen dort aber alle bis auf staktsfz01

> 
> 
> @jocarstensen das hast du alles richtig nachvollzogen bzw. zusammengefasst.
> Warum szaktsfz01 auf zwischen_k ist kann ich auch nicht nachvollziehen. ABER auf **hilfsvar** machen die Studiengänge und Fächer für mich schon Sinn, da wir im weiteren verlauf mit Einblendungen arbeiten.
> 
> > ```
> > * staktsfz01 --> Wird nicht im Kalendarium gefüllt. Warum ist die in der Liste? Es gibt noch elf weitere Studienfach-HVs, aber ich wüsste nicht, warum die hier stehen müssen.
> > ```

**Comment by AliceFoelker** [comment]
@jocarstensen wow oh man da hast du recht :-/ 
@andreaschu kannst du die noch rüber schieben? Damit die Studiengänge und -fächer gesammelt auf **hilfsvar** sind. (geht das noch mit der Übersicht?)

**Comment by jocarstensen** [comment]
@AliceFoelker Schreib doch besser einfach in #142, welche HV in der Liste noch fehlen. Die Studienfächer waren bis auf h_staktsfz01 bisher noch auf keiner der Seiten vorhanden.

**Comment by AliceFoelker** [comment]
@jocarstensen Halt Stop. Ich habe gerade entdeckt, dass auch h_staktsfz01 auf **hilfsvar** vorhanden ist. Das bedeutet, dass diese Hilfsvariable zusätzlich auf zwischen_k  auftaucht aber dort nichts bringt und theoretisch raus kann. 
Ich befürchte, dass es hier etwas unübersichtlich wird. 
![grafik](https://user-images.githubusercontent.com/73596957/104179271-dc294e00-540b-11eb-8be7-3380c76c90e2.png)

**Comment by andreaschu** [comment]
ich habe die Einblendungen der Hilfsvariaben auf zwischen_k verändert.
