### ISSUE TITLE
Episoden: nsET Jobs werden leicht übergangen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#139]
Ich habe eben im Kalendarium Jobben und nsET angegeben. Als dann das Modul em0001 angefangen hat, habe ich den kleinen Satz unten zu den Jobs total überlesen, woraufhin meine beiden Studentenjobs, die vor meiner nsET waren untergangen sind. Da im Anschluss nur gefragt wurde, ob seit der nsET noch andere nsET erfolgten, würde man dementsprechend "nein" anklicken, wenn die Jobs zeitlich davor waren. Was ich damit sagen will - dadurch, dass man nahezu zu jedem Eintrag im Kalendarium eigentlich ein extra Modul bekommt, fällt Jobben schnell unter den Teppich. Vermutlich lässt sich für diese Befragung daran nichts ändern, jedoch würde ich das für künftige vermutlich anders lösen oder es optisch zumindest so hervorheben, dass es nicht übersehen werden kann. (evtl. direkt als Klammer hinter die ao)

![grafik](https://user-images.githubusercontent.com/73596957/103671972-ec5cab80-4f7b-11eb-8d44-1f439459b374.png)

![grafik](https://user-images.githubusercontent.com/73596957/103671310-0944af00-4f7b-11eb-8513-fe0f0277c0ec.png)

**Comment by AliceFoelker** [comment]
@jocarstensen ich habe das Issue jetzt in die "Wiedervorlage" gepackt. Ich nehme an dass daran jetzt nichts getan werden kann - also dieses Issue schließen?

**Comment by jocarstensen** [comment]
Ja, Du nimmst richtig an.
