### ISSUE TITLE
stu_24: Klammerfehler in transition 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#14]
Bei der Weiterleitungs-Bedingung von stu_24 zu gsh_00 sind eine und- und eine oder-Bedingung in einer Klammer: 

`GOTO gsh_00 IF (bestwuw_183b =4 OR bestwuw_183b =5 AND h_studever!=1) OR (bestwuw_183b =MISSING AND sf_bestwuw_183b =1)`

umgesetzt habe ich es so:
`GOTO gsh_00 IF ((bestwuw_183b =4 OR bestwuw_183b =5) AND h_studever!=1) OR (bestwuw_183b =MISSING AND sf_bestwuw_183b =1)`

**Comment by AliceFoelker** [comment]
@andreaschu danke. Von stu_24 komme ich mit bestwuw_183b jedenfalls weiter. Oder wäre das jetzt mit Existenz von h_studever!=1 erst problmatisch geworden?

**Comment by andreaschu** [comment]
Ich habe es anders programmiert, als es in der PV steht. Es macht aber nur so Sinn, da _bestwuw_183b_ nicht den Wert 4 und 5 annehmen kann. 
Ich habe mir erlaubt, es in die PV zu übernehmen.
