### ISSUE TITLE
Kalendarien: Darstellung / Jahreszuordnung

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#140]
Die Variablen sind durch den Workaround den Jahren nicht identisch zugeordnet. Zumindest wird hier das, was bei cal1 für 2020 ausgefüllt wurde, bei cal25 für 2018 dargestellt (siehe screenshots).
Dadurch funktioniert evtl. auch die Füllung der Hilfsvariablen bei cal1 nicht richtig, wenn man es im cal1 ausfüllt.

Hier ist ein Kalendarium ausgefüllt, einmal bei cal1 und eimal bei cal25 geöffnet (token: tester26).

![Screenshot_2021-01-05 SLC_IntEr_18-3(6)](https://user-images.githubusercontent.com/30111489/103680794-fafc9000-4f86-11eb-9bcb-692a4d05a4bc.png)
![Screenshot_2021-01-05 SLC_IntEr_18-3(5)](https://user-images.githubusercontent.com/30111489/103680800-fb952680-4f86-11eb-9f45-8dcc77ccb1cd.png)

**Comment by AliceFoelker** [comment]
ja, glaube bei dem Tester haben Heiko und ich ein bisschen rumprobiert. wir haben dann die Kalendarien manuell angesteuert und für wave 1 wie gewollt cal1 ausgefüllt aber im Nachgang _versehentlich_ cal25 betrachtet. Dabei wurden dann die Daten, wie bei dir auch nicht in 2020 angezeigt, sondern alles in 2018. Wir haben es dann darauf geschoben, dass das ein Fehler ist, den man nur durch das manuelle ansteuern "hervorgerufen" hat und das außerhalb der Testversion gar nicht passieren kann.


ABER bei tester28 (wave1) werden die Hilfsvariablen auch nicht befüllt, auch wenn ich mich ganz normal durchklicke und das Kalendarium (cal1) ausfülle und mit cal25 nichts zu tun habe.

**Comment by heikQ** [comment]
bei mirn war das auch mit ganz normalen Durchklicken so und nicht nur, wenn ich direkt ansteuere

**Comment by andreaschu** [comment]
@AliceFoelker  und @heikQ wir sind dran und vermuten, dass mit hiermit auch die issues #130 und #138 verknüpft sind.

**Comment by andreaschu** [comment]
die Jahreszuordnung ist nun korrekt.
![grafik](https://user-images.githubusercontent.com/30111489/103912038-18f0fe80-5107-11eb-99c6-69da153b414f.png)

![grafik](https://user-images.githubusercontent.com/30111489/103912086-25755700-5107-11eb-8cc7-dd0c9fd43abd.png)
