### ISSUE TITLE
Sammel-Issue zur Wiedervorlage

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#141]
Hier können die Issues und Anmerkungen gesammelt werden, die bei dieser Welle keine Berücksichtigung finden werden - aber zur Wiedervorlage bei nächsten Befragungen nützlich sind:

**Comment by AliceFoelker** [comment]
#139
https://github.com/dzhw/studienberechtigte_2018.3b/issues/5#issuecomment-754004673
#134 
#135 
#136

**Comment by AliceFoelker** [comment]
Doku: diese Frage ist nach den Episoden gestellt. Wenn Studium im Vorfeld allerdings abgebrochen oder beendet wurde, sollten auch die Formulierungen zukünftig angepasst werden. Theoretisch von dem ganzen Studienmodul (nicht Episoden).

![grafik](https://user-images.githubusercontent.com/73596957/105706413-cb033580-5f11-11eb-8f93-f95bc62d4200.png)

**Comment by jocarstensen** [comment]
Wer geht denn da rein? Nicht nur Leute mit h_studakt==1?

**Comment by AliceFoelker** [comment]
ne, Leute mit h_studever=1, d.h. dann können Studiengänge durchaus entweder abgebrochen oder beendet worden sein.
> Wer geht denn da rein? Nicht nur Leute mit h_studakt==1?

**Comment by heikQ** [comment]
@jocarstensen @AliceFoelker Also hab gerade nochmal geschaut, theoretisch wäre es eine filtersetzung die wir noch ändern müssten auf stu_12 und würden dann alle mit stud_ever==1 aber h_studakt!=1 wie wave 4 und 5 nach stu_22 schicken. Und nur (wave =1 or wave= 3) ANS h_studakt==1 in stu_13. So wären es teils retropektive angaben halt. @jocarstensen sollen wir das noch ändern?

**Comment by jocarstensen** [comment]
Inhaltlich macht es wenig Sinn, das auf vergangene Studienepisoden zu beziehen und der Bezug ist auch unklar. Ich würde es gern ändern wenn sichergestellt ist, dass wir die Weiterleitung dann noch ausreichend testen können. Jetzt noch Fehler mit Hängenbleiben zu erzeugen, wäre sehr kritisch.

**Comment by heikQ** [comment]
haben den Filter eben durchgesprochen, Alice ändert das jetzt noch, so dass alle die nicht akutell im Studium sind, auch nicht in die Lehrlernumwelt marschieren, eigentlich ein einfacher Filter, insofern kann nicht viel schief gehen, testen müssen wir das dann natürlich

**Comment by jocarstensen** [comment]
#236

**Comment by AliceFoelker** [comment]
**Wiedervorlage:** angegebene Praxisphasen bei Praxispartnern (z.B. staa23) wurden in der Vergangenheit im weiteren Verlauf nicht z.B. zu Episoden ET weitergeleitet. Diskussion, ob für h_erwerb in Studium oder zwischen_st Trigger gersetzt werden, um im Weiteren zu Erfahren, wo/in welcher Branche diese Praxisstelle während des Studiums stattgefunden hat. Darüber hinaus gab es in 2018.3a relativ viele Fälle, die Praxisphasen unter "Sonstiges" bei "weitere Tätigkeiten" angegeben haben. Das könnte man für >future projects< nochmals diskutieren...

**Comment by AliceFoelker** [comment]
#115

**Comment by AliceFoelker** [comment]
1. Kalendarium iPad: wenn der agent user string - aus iwelchen Gründen - nicht mitgesendet wird, springt das Kalendarium für den Desktop an (mit den Erklärungen) - funktionieren tut es aber wie mobil. (bislang keine Lösung gefunden)
2. iPad-Ansicht: Viele aos waren überlappend und einige Seiten fehlerhaft. Diese müssen (bislang) manuell einzeln für alle Matrizen angeglichen werden. (Umbrüche! - keine 90 Grad Drehungen der aos). Kein Verlass auf die Screenshots. Diese geben nicht die echte Darstellung/Simulation wieder.
3. Ort/PLZ strings mobil: müssen für **alle** Schleifen und Splits angepasst werden, sonst sind sie zu klein und verrutscht
4. Allgemein: macht es offenbar Sinn die Issues der letzten Befragungen durchzusehen. Man hätte sich viele Probleme/ Anpassungen ersparen können.
