### ISSUE TITLE
Hilfsvariablencheck: Seite erstellen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#142]
@andreaschu @christian-fr Ist es möglich eine Seite im FB zu erstellen auf der alle Hilfsvariablen eingeblendet werden, womit geprüft werden kann, ob diese auch befüllt wurden? Wir haben da an eine von der Filterung unabhängige Seite gedacht, die wir manuell ansteuern können.
Prinzipiell wie zwischen_k nur mit allen Hilfsvariablen? z.B. Auch Studiengang, Fächer, Datum usw.?

**Comment by andreaschu** [comment]
ja, das wäre möglich. Welche Seite sollte das sein und welche Hilfsvariablen würden dabei noch fehlen?

**Comment by AliceFoelker** [comment]
@heikQ @jocarstensen da bräuchte ich jetzt etwas Hilfe. Bei uns wäre das ja theoretisch die Hilfsvariablenliste oder? fehlt dann noch was ?
[Hilfsvariablen.20201208.xlsx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5775904/Hilfsvariablen.20201208.xlsx)

**Comment by jocarstensen** [comment]
Die Variablen aus der Liste auf jeden Fall. Zusätzlich wären noch die h_calmis2018/h_calmis2019/h_calmis2020 hilfreich. Und eventuell noch die Variablen, die für deren Generierung herangezogen werden. Die habe ich aber gerade nicht auf dem Schirm. Wo werden die noch gebildet? auf zwischen_cal?

**Comment by andreaschu** [comment]
Oh weh, die Dokumentation...
Jetzt brauche ich mal Eure Hilfe. 
Kann mir jemand sagen, was die Hilfsvariablen h_calmis2018 und h_calmis2019 genau zählen sollten? 
h_alofam und h_nohaupt verstehe ich auch nicht ganz. 
no_haupt, ob Hauptepisoden (Schule, Ausbildung oder Erwerbstätigkeit) vorhanden sind?
h_alofam, ob Arbeitslosigkeit oder Familienarbeit vorhanden ist?

Die Liste der Hilfsvariablen, die auf zwischen_kal getriggert werden ist: 
h_calmis2018
h_calmis2019
h_calmis2020
h_nohaupt
h_alofam 
h_ausbakt
h_schule
h_studium
h_studever 
h_ausb 
h_ausbever 
h_fortb 
h_jobben
h_erwerb 
h_praktikum 
h_elternz 
h_alo
h_sonstiges

**Comment by jocarstensen** [comment]
Kannst Du das QML von zwischen_cal unter Code einstellen? Das liegt mir nicht vor uns ich würde gern die Trigger angucken.

**Comment by andreaschu** [comment]
@jocarstensen das XML für die Zwischenseiten ist [hier](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/questionnaire19.xml).

Wenn Du nur die Trigger willst, dann hier:
```
        <zofar:triggers>
            <zofar:variable variable="h_calmis2018" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(1,2,3,4,5,6,7,8,9,10),1,12) lt 6),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_calmis2019" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(1,2,3,4,5,6,7,8,9,10),13,24) lt 6),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_calmis2020" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(1,2,3,4,5,6,7,8,9,10),25,36) lt 6),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_schule" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(1))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_studium" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(2))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_studever" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(2))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_ausb" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(3))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_ausbakt" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(3),24,24) == 1),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_ausbever" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(3))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_fortb" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(4))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_jobben" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(5))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_erwerb" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(6))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_praktikum" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(7))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_elternz" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(8))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_alo" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(9))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_sonstiges" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(10))),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_nohaupt" value="zofar.ifthenelse((zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(1))),'1','0') == 0) and (zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(3))),'1','0') == 0) and (zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(6))),'1','0') == 0),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>
            <zofar:variable variable="h_alofam" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(8),1,24) ge 22) or (zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data1.value),zofar.list(9),1,24) ge 22),'1','0')" condition="zofar.asNumber(PRELOADwave)==1"/>

            <zofar:variable variable="h_calmis2018" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(1,2,3,4,5,6,7,8,9,10),1,12) lt 3),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_calmis2019" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(1,2,3,4,5,6,7,8,9,10),13,24) lt 6),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_calmis2020" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(1,2,3,4,5,6,7,8,9,10),25,36) lt 9),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_schule" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(1))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_studium" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(2))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_studever" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(2))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_ausbakt" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(3),24,24) == 1),'1','0')" condition="zofar.asNumber(PRELOADwave)==2"/>
            <zofar:variable variable="h_ausb" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(3))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_ausbever" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(3))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_fortb" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(4))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_jobben" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(5))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_erwerb" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(6))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_praktikum" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(7))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_elternz" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(8))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_alo" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(9))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_sonstiges" value="zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(10))),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_nohaupt" value="zofar.ifthenelse((zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(2))),'1','0') == 0) and (zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(3))),'1','0') == 0) and (zofar.ifthenelse((zofar.hasEpisodes(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(6))),'1','0') == 0),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
            <zofar:variable variable="h_alofam" value="zofar.ifthenelse((zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(8),1,24) ge 16) or (zofar.countTilesWithEpisodesInRange(zofar.decodeEpisodes(calendar183Data25.value),zofar.list(9),1,24) ge 16),'1','0')" condition="zofar.asNumber(PRELOADwave)!=1"/>
        </zofar:triggers>
```

**Comment by jocarstensen** [comment]
Ah, ok. Ich dachte, die Trigger wären auf zwischen_cal, die nicht in den Zwischenseiten enthalten ist. Aber die QML für die Zwischenseiten gab es schon unter Code. Könntest Du also auch wieder löschen, sorry.

**Comment by andreaschu** [comment]
Okay. 
Ja, die haben sich schon etwas verändert. Mich treibt gerade um, warum (z. B.) bei calmis2018 damals für die die erste Kohorte die Bedingung `lt 6` enthalten ist und bei der anderen Kohorte `lt 3` usw.. 

`[…] variable="h_calmis2018" […],zofar.list(1,2,3,4,5,6,7,8,9,10),1,12) lt 6),'1','0')" […]/>`

**Comment by jocarstensen** [comment]
Ist ein bisschen verwirrend, dass die Anpassungen aus questionnaire19.xml nicht auch in zwischenseiten.xml sind. Aber jetzt weiß ich es ja.

Mich treibt um, warum wave==1 dieselben Trigger bekommt wie wie wave!=1, wo doch beide unterschiedliche Referenzzeiträume haben. Sprich: h_calmis2018 und h_calmis2019 können für wave==1 nicht genauso gebildet werden wie für die anderen waves, da diese Jahre im Kalendarium nicht angezeigt werden dürften. Dasselbe gilt vermutlich auch für die anderen Trigger.

**Comment by jocarstensen** [comment]
Hier (https://github.com/dzhw/SLC-IntEr/issues/26) findet Ihr die Definition der HVs.

**Comment by jocarstensen** [comment]
Das mit lt 3 und lt 9 muss ein Fehler sein, das macht an dieser Stelle keinen Sinn.
Die Bedingung gibt an, dass mindestens 50 % der Monate in dem Jahr mit irgendeinem Episodentyp gefüllt sein müssen. Bei ganzen Jahren also lt 6. In IntEr begann der Referenzzeitraum für cohort==2 im Juli, somit waren <50 % lt 3. Bei ganzen Jahren muss es aber immer lt 6 sein.

**Comment by jocarstensen** [comment]
h_alofam: Die Bedingung gibt an, dass mindestens die gesamte Dauer in Monaten minus zwei (Toleranz) mit Arbeitslosigkeit oder Familientätigkeit gefüllt sein muss. Daher 22 (cohort 1) und 16 (cohort 2) in IntEr.

**Comment by heikQ** [comment]
jup, ansonsten die Hilfsvariablenliste aus der Excel-Datei im issue für die HV

**Comment by andreaschu** [comment]
> Das mit lt 3 und lt 9 muss ein Fehler sein, das macht an dieser Stelle keinen Sinn.
> Die Bedingung gibt an, dass mindestens 50 % der Monate in dem Jahr mit irgendeinem Episodentyp gefüllt sein müssen. Bei ganzen Jahren also lt 6. In IntEr begann der Referenzzeitraum für cohort==2 im Juli, somit waren <50 % lt 3. Bei ganzen Jahren muss es aber immer lt 6 sein.

Aah, jetzt verstehe ich. Dass es hier keinen Sinn mehr macht, war mir klar. Ich hatte nur den ursprünglichen Sinn nicht verstanden oder irgendwo gefunden. Könntet Ihr das mit der Erklärung, dass mindestens 50% der Monate gefüllt sein müssen, in die Hilfsvariablenliste übernehmen?

**Comment by jocarstensen** [comment]
Wir driften vom Thema ab. Ich erstelle ein neues Issue für die Trigger auf zwischen_k und hier können wir festhalten, dass wir auf der Hilfsvariablencheckseite folgende HVs wollen:
alle aus der von Alice verlinkten Excel
alle auf zwischen_k getriggerten HVs

**Comment by andreaschu** [comment]
guter Punkt! 
Dann hier nur noch die Idee, dass ich eine Testseite mache, die ich direkt an den Anfang stelle, die aber nur direkt angesteuert werden kann, damit ich nicht den Fragebogenverlauf kaputt mache. Ist das in Ordnung? 
Die Seite nenne ich dann **hilfsvar**.

**Comment by jocarstensen** [comment]
Ja, das passt dann.

**Comment by AliceFoelker** [comment]
@andreaschu Die Seite ist erstellt, danke. Hier fehlen jetzt aber noch einige aus 
[Hilfsvariablen.20201208.xlsx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5782776/Hilfsvariablen.20201208.xlsx)
z.B. h_staktma, h_stbaever, h_ausb20 und die Hilfsvariablen der Studiengänge/Fächer:

![grafik](https://user-images.githubusercontent.com/73596957/103917049-71c39580-510d-11eb-9c3d-8354265b7eb6.png)

**Comment by AliceFoelker** [comment]
@andreaschu der Rest dürfte jetzt auch drin sein, danke. Lasse das Issue als "Dokumentation" noch auf
