### ISSUE TITLE
Studium: stu_13 is und q tauschen und Doppelpunkte

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#143]
hier würde ich auf jeden Fall die is mit der q vertauschen. 

@heikQ auch beim Wording müssten wir evtl. noch Anpassungen vornehmen: z.B: 
is: In den nachfolgenden Fragen zu Ihrem Studiengang...
und ggf. das Wort "Liste" weglassen.
![grafik](https://user-images.githubusercontent.com/73596957/103773395-48323d80-502b-11eb-9975-75952bc9e2a2.png)

**Comment by heikQ** [comment]
die anleitung/kommentar muss vor "Studiengang" und statt "wählen Sie diese aus der Liste aus" schreiben wir einfach "wählen Sie diese bitte unten aus"....
