### ISSUE TITLE
Studium: stu_08 & stu_09

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#144]
Bei stu_09 ist eine >in< drin, die aber nicht im Code steht.
@heikQ hier sind ja einfach nur die Items von einer Fragestellung auf 2 Seiten verteilt. Soll dann die Fragestellung auch identisch sein? Hier weichen sie minimal voneinander ab.

![grafik](https://user-images.githubusercontent.com/73596957/103775652-aa407200-502e-11eb-9ae7-2ebd65c21732.png)
![grafik](https://user-images.githubusercontent.com/73596957/103775689-b88e8e00-502e-11eb-9405-2137fdda72ad.png)

**Comment by heikQ** [comment]
@AliceFoelker so lassen wegen zeitreihe

**Comment by AliceFoelker** [comment]
ok, dann also nur die >in< auf stu_09 entfernen

**Comment by AliceFoelker** [comment]
fixed
