### ISSUE TITLE
Episoden: em(aa)12 mobile version entzerren

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#145]
hier sind die aos optisch kaum voneinander getrennt. Könnt ihr das bitte entzerren?
![grafik](https://user-images.githubusercontent.com/73596957/103786741-10cc8c80-503d-11eb-9450-2ea5ac910fe8.png)

**Comment by vdick** [comment]
ab ächsten Rollout (#149 ) verfügbar

**Comment by AliceFoelker** [comment]
fixed
