### ISSUE TITLE
Ausfüllhinweise auf mobilenBilds. fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#147]
Die Ausfüllhinweise müssten noch an mobileBildschirme angepasst werden 
![grafik](https://user-images.githubusercontent.com/73596957/103894197-dae7e080-50ee-11eb-8f86-c77d87469a73.png)

**Comment by jocarstensen** [comment]
Macht es nicht Sinn, damit zu warten, bis die richtigen GIFs da sind?

**Comment by AliceFoelker** [comment]
@jocarstensen das stimmt, dasselbe "Problem" hatten wir allerdings auch mit den Zwischenseiten & bei der Aktualisierung der Zwischenseiten konnten sie dann direkt im richtigen Format ausgewechselt werden. Ich kann das aber auch erst mal wieder rausnehmen und dann wenn die neuen GIFs da sind und das Problem noch besteht wieder aufmachen

**Comment by jocarstensen** [comment]
@andreaschu Sag mal bitte, ob es sinnvoll ist, damit zu warten oder ob es egal ist.

**Comment by andreaschu** [comment]
@AliceFoelker und @jocarstensen ich verstehe das Problem nicht. Aus meiner Sicht, sind die Texte angepasst.
Vielleicht habe ich das Problem nicht verstanden, aber bitte bedenkt, dass es hier unterschiedliche Hinweisseiten für die Ansichten gibt, die je nach Bildschirmgröße angesteuert werden. 
![2020-12-15_17-42_questionnaire8](https://user-images.githubusercontent.com/30111489/102339298-3d890900-3f95-11eb-8fe7-dbc1d012cced.png)

Ich glaube, es macht Sinn, eine Programmiervorlage für die Kalendarien und diese Zwischenseiten anzulegen.

**Comment by AliceFoelker** [comment]
@andreaschu die Texte sind m.E. korrigiert und passen nun zu den jeweilig vorgesehenen Befragungszeiträumen. Bei dem Issue geht es eher um das GIF auf der Seite - nicht um die Filterung. Das wird auf mobilenBildschirmen nicht vollständig angezeigt. Weder Im Hoch- noch im Querformat (auch wenn ich zunächst in der mobilEinstellung über die Indexseite bin und somit die korrekte Zwischenseite angesteuert wurde).

**ABER** vermutlich macht es wirklich erst Sinn das _en datail_ zu besprechen wenn Heiko die neuen Gifs fertig hat?! (in der aktuellen Befragung sind die der letzten Befragung drin, weshalb auch dort die Zeitstrahlen der Befragungszeiträume nicht passen und bspw. die alten Fortschrittsbalken im Hintergrund sind).

**Comment by andreaschu** [comment]
@AliceFoelker worauf ich hinaus wollte war, dass in dem obigen Screenshot ist der Text für die Desktop-Version zu sehen, aber in der mobilen Darstellung. Das passte nicht zusammen, hat aber mglw. auch nichts mit dem eigentlichen Problem zu tun. Das wäre tatsächlich sinnvoller es mit aktuellen Gifs zu diskutieren.

**Comment by AliceFoelker** [comment]
@andreaschu dann schließeich das Issue  und erstelle ein neues wenn die neuen GIFS vorliegen
