### ISSUE TITLE
Indexseiten: Doppelte Überschrift& fehlende Einblendung

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#148]
wave 1
![grafik](https://user-images.githubusercontent.com/73596957/103915130-1690a380-510b-11eb-96d1-af0406d11a0e.png)

wave 2,3
![grafik](https://user-images.githubusercontent.com/73596957/103915225-388a2600-510b-11eb-8e60-6d60c8c775a5.png)

wave 4,5
keine Einblendung des Textes 8auch nach >weiter< + doppelte Überschrift
![grafik](https://user-images.githubusercontent.com/73596957/103915389-6ff8d280-510b-11eb-826f-df9ff7f32714.png)

**Comment by AliceFoelker** [comment]
#101

**Comment by andreaschu** [comment]
> wave 4,5
> keine Einblendung des Textes 8auch nach >weiter< + doppelte Überschrift

Ach so. Das liegt daran, dass die Einblendbedingung an die Preload-Variablen wave und incentive gebunden ist. Du **musst** hier auch bei Incentive etwas eingeben.

**Comment by AliceFoelker** [comment]
@andreaschu oh ja entschuldige, mein Fehler - dann passt das bis auf die doppelten Überschriften.

**Comment by AliceFoelker** [comment]
fixed
