### ISSUE TITLE
Modul SozDem: msg_02 aos abgeschnitten

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#15]
ao1 und ao11 sind abgeschnitten/ nicht lesbar

**Comment by andreaschu** [comment]
Bis eine Bildschirmbreite von 1126 geht es. Danach schon nicht mehr. Da die Skala lang ist und die Labels auch, kann man da nicht mehr viel machen. Bitte auch hier entscheiden, was passieren soll. Soll die Skala für alle vertikal dargestellt werden oder der Umbruch in vertikale Darstellung bei einer Bildschirmbreite von 1125 erfolgen?

**Comment by AliceFoelker** [comment]
@andreaschu 11er Skalen direkt vertikal für alle, danke.

**Comment by AliceFoelker** [comment]
im code geändert.
![grafik](https://user-images.githubusercontent.com/73596957/101781325-efd55200-3af7-11eb-9e25-460bee549712.png)
