### ISSUE TITLE
Fortschrittsbalken fehlt auf zwischen_epi

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#150]
Forschrittsbalken_4 noch auf zwischen_epi
![grafik](https://user-images.githubusercontent.com/73596957/103551556-c87d6500-4eaa-11eb-84a5-ee359ba934a6.png)

**Comment by christian-fr** [comment]
Fortschrittsbalken ist ergänzt. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
