### ISSUE TITLE
Kalendarium: InternetExplorer Aktivitätenauswahl nicht möglich

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#155]
Ich gehe die Befragung im Internetexplorer durch, allerdings kann ich im Kalendarium Aktivitäten auswählen, diese aber nicht im Kalendarium eintragen. Es geschieht nichts.

**Comment by andreaschu** [comment]
@dzhwmeisner kannst Du mal schauen, was da los ist?

**Comment by andreaschu** [comment]
@AliceFoelker meinst Du den InternetExplorer oder Edge? Mit Egde funktioniert es bei mir. 
Den InternetExplorer gibt es eigentlich nicht mehr, zumindest wird er nicht mehr aktualisiert und er wurde durch Edge ersetzt.

**Comment by AliceFoelker** [comment]
@andreaschu das sich da was getan hat habe ich gemerkt, aber ich habe den InternetExplorer aufgerufen und unseren internenLink eingefügt. Und dabei haben Eintragungen ins Kalendarium nicht funktioniert.

**Comment by AliceFoelker** [comment]
won't fix
