### ISSUE TITLE
Kalendarium. bug ansicht

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#156]
irgendwas stimmt jetzt nicht mehr, wave 1, testtoken 210, vor 30 min gings noch, cache war geleert
![calnanu](https://user-images.githubusercontent.com/52539440/104225010-1283bf00-5446-11eb-802e-16546ea336e4.JPG)

**Comment by andreaschu** [comment]
@all ich habe gestern beim Kalendarium einen Fehler eingebaut, der vor allem das cal1 betrifft. Ich melde mich, wenn das wieder getestet werden kann.

**Comment by andreaschu** [comment]
Jetzt sind die Label wieder da und die Version ist aktuell. Kann getestet werden.

**Comment by heikQ** [comment]
passt wieder, danke, erledigt, mache hier zu
