### ISSUE TITLE
Referenzzeitraum auf zwischen_cal_bd  (bm) ändern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#158]
**falls hier _nicht_ h_enterdatum eingeblendet wird**: Die Referenzzeiträume von cal25 (wave 2-5) haben sich geändert. Dementsprechend muss auch an dieser Stelle der Text angepasst werden: Juli 2018 statt Januar 2018.

![grafik](https://user-images.githubusercontent.com/73596957/104341543-343e7e00-54fa-11eb-954a-d536c978ca0f.png)

**Comment by andreaschu** [comment]
@AliceFoelker nun habe ich auch endlich mal eine PV für das Kalendariumsmodul erstellt. 
Siehe hier: https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/PV_kalendarien.md

Da ist der neue Referenzzeitraum noch nicht drin. Kannst Du das da an den entsprechenden Stellen noch ändern?

**Comment by andreaschu** [comment]
@AliceFoelker heißt das, dass hier auch das halbe Jahr ausgegraut werden soll? Wenn ja, müssen die Trigger hier wieder angepasst werden, oder?

**Comment by AliceFoelker** [comment]
fixed
![grafik](https://user-images.githubusercontent.com/73596957/104564111-d0779a80-564a-11eb-89c7-fd3fd3ed750f.png)
