### ISSUE TITLE
PV für Endseiten und Add-On

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#159]
@AliceFoelker ich habe den ersten Aufschlag für die Endseiten gemacht, etwa so wie sie das letzte Mal online ging. 
Siehe hier: https://github.com/dzhw/studienberechtigte_2018.3b/commit/3716c7d127d9d3aa49c77220448ee5c5314d2e5a

Bitte passe diese Programmiervorlage entsprechend der neuen Version an (z. B. braucht man nicht die beiden unterschiedlichen Texte und Links).

**Comment by AliceFoelker** [comment]
@andreaschu das war eine super Vorlage, danke dir! Ich habe im commit Seitennamen und die Textauswahl geändert und die einzublendende Zwischenseite angegeben. ich frage mich jetzt nur noch wo die Seite "end" (Vielen Dank für Ihre Anmerkungen rein soll). Muss dann noch der {Link zur SLC-IntEr18-3} (von Seite end_1 Zeile 64) für die Adressaktualisierung erneuert werden?

**Comment by andreaschu** [comment]
Prima. Damit können wir arbeiten.
Eine Sache noch. Jede Befragung benötigt mindestens eine Seite, die _index_ heißt und eine Seite die _end_ heißt. Index ist immer die erste und end, immer die letzte Seite. Deswegen geht die Namensänderung bei der allerletzten Seite (zu end_2) nicht.

**Comment by AliceFoelker** [comment]
ok, ich habe es (hoffentlich richtig) angepasst, allerdings gibt es jetzt noch zwei Seiten mit dem Namen _end_ das muss ich mir morgen noch mal ansehen. Die eine (Vielen Dank für Ihre Anmerkungen) kommt mir ein bisschen überflüssig vor. Wir können ja auch erstmal schauen wie es aussieht und ggf. nachjustieren.

**Comment by andreaschu** [comment]
Ja, das habe ich vielleicht etwas ungeschickt gelöst. Da ich keine zwei PVs machen wollte, habe ich die letzten Seiten der Hauptbefragung und die Add-On-Befragung in einer beschrieben. 

Das heißt, dass zwar beide (Hauptbefragung und Add-On) hier eine end-Seite brauchen, aber nur die Add-On-Befragung auch eine index-Seite.
Der Sprung geht hier direkt von dem Link auf der end_0 auf die index-Seite der Add-On.

Ja, die allerletzte Seite fand ich auch überflüssig.

**Comment by AliceFoelker** [comment]
@andreaschu kann ich dann die letzte Seite rausschmeißen und die Seite wo der Link für die Adressaktualisierung ist zu **end** machen? Dann müsste nur noch die Zwischenseite_8 als Grafik eingefügt werden.

**Comment by andreaschu** [comment]
@AliceFoelker ja, das kann ich machen. Die Graphik lasse ich lieber @christian-fr nächste Woche einfügen.

**Comment by christian-fr** [comment]
Die Grafik auf page **end_1** ist eingebaut. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@andreaschu Grafik ist nun drin. Had der Add on eigentlich auch eine Art Endseite? Wenn ja, kann die allerletzte Seite" Vielen Dank wir haben ihreAnmerkung erhalten" raus oder?
