### ISSUE TITLE
SozDem: msg_13 soft rangecheck fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#162]
wenn man 21 Kinder angibt :-) erfolgt ein Hinweis siehe Screenshot. Allerdings sollte ein Weiterkommen trotzdem möglich sein. Man kommt aber nicht von der Seite, es sei denn man ändert die Eingabe zu max. 9
![grafik](https://user-images.githubusercontent.com/73596957/104350648-afa52d00-5504-11eb-952e-e843f505f7e2.png)

**Comment by andreaschu** [comment]
@AliceFoelker wenn man ein Feld nach Gültigkeit prüft, dann müssen die Befragten einen gültigen oder keinen Wert eintragen. 
Die Alternative wäre es als Softforce einzubauen. Dann erscheint die Nachricht aber am Seitenende bzw. unter der Frage.

**Comment by AliceFoelker** [comment]
@andreaschu d.h. man kann in Rot daneben nicht nur lediglich einen Hinweis einblenden?! und wenn der "Hinweis" ohne Restriktionen verbunden sein soll muss es eine softforce sein?

**Comment by andreaschu** [comment]
@AliceFoelker ja, genau.

**Comment by AliceFoelker** [comment]
@andreaschu @heikQ wenn es keine andere Möglichkeit gibt, dann mache ich daraus eine SF. Ich versuche das im Code zu ändern.

**Comment by AliceFoelker** [comment]
@andreaschu Ich bin mir nicht sicher, ob ich das richtig umgesetzt habe. Kannst du mir da bitte Rückmeldung geben?
https://github.com/dzhw/studienberechtigte_2018.3b/commit/725207dc6ffa4c9b26736f196140421840b81f4f

**Comment by andreaschu** [comment]
@AliceFoelker was soll denn passieren, wenn die Angabe nicht korrekt ist, also wenn der Wert größer als 9 ist? Ich meine, mehr als 9 Kinder ist schon extrem unwahrscheinlich. 
Fehlende Werte sollen weiterhin ignoriert werden?

**Comment by AliceFoelker** [comment]
@andreaschu da hast du natürlich recht. Es ist super unwahrscheinlich ABER da soll keine Restriktion eingebaut sein, sondern lediglich der Hinweis erscheinen. Wenn jemand z.B. mit seiner Eingabe (10 Kinder) auf WEITER klickt sollte das ohne Weiteres möglich sein. Ich nehme an, dass es sich genauso mit fehlenden Werten verhält? @heikQ

**Comment by andreaschu** [comment]
@AliceFoelker mir ist gerade aufgefallen, dass wir hier - wenn es ein Nummernfeld bleiben soll - immer eine Fehlermeldung benötigen. Diese kann aber auch sein, dass sie einen Wert anstelle von Zeichen angeben sollen.

**Comment by AliceFoelker** [comment]
@andreaschu ich bin mir bzgl. dem höher setzen des Gültigkeitsbereichs nicht ganz sicher was du da genau meinst. Wie würde dann die Fehlermeldung lauten?

**Comment by andreaschu** [comment]
@AliceFoelker man könnte schreiben, dass sie eine Zahl eingeben sollen und den Wertebereich von 0 bis 99 lassen. Dann kann man zwei Zeichen eingeben und die Meldung kommt nur, wenn darin auch Sonderzeichen oder Buchstaben enthalten sind.

**Comment by AliceFoelker** [comment]
Das werde ich morgen mit @heikQ besprechen. Ich vermute aber, dass sich die Meldung, auch wenn es jetzt eine soft force statt ein soft range check ist, an dem Screenshot oben orientieren soll. D.h. alles was einen Wert größer 9 hat, soll eine soft force auslösen (mit dem Text wie oben), mehr aber nicht. @andreaschu du erhälst morgen Rückmeldung von mir.

**Comment by heikQ** [comment]
@andreaschu @AliceFoelker Bei der letzten slc-inter Befragung war es so, dass bei einer Eingabe >9 einfach der Hinweis kam die Angabe zu prüfen, man dann aber auch bei einer Angabe größer 9 weiter klicken konnte. So sollte es allein wegen Vergleichbarkeit möglichst wieder sein, wenn das geht. Klar sind mehr als neun Kinder verdammt unwahrscheinlich, aber eben nicht unmöglich.

**Comment by AliceFoelker** [comment]
@andreaschu auf mobil passiert übriegens auch das hier:
![grafik](https://user-images.githubusercontent.com/73596957/105154465-de756180-5b09-11eb-8c41-36f7777c0185.png)

**Comment by heikQ** [comment]
@andreaschu ja, war msg_08 und 0 bis 99 ist okay, soll wie in msg_08 damals sein. Danke

**Comment by AliceFoelker** [comment]
@andreaschu das heißt für die PV: Soft Rangecheck zu SF und den Wertebereich zu 0 bis 99 ändern?

**Comment by AliceFoelker** [comment]
@andreaschu @heikQ jetzt sind alle Eingaben bis 99 möglich ohne weiteren Hinweis. Also man kommt einfach weiter, wenn man 99 eingegeben hat. Ist das jetzt der letzte Stand, dass es so gewollt ist?

**Comment by dzhwmeisner** [comment]
> @andreaschu auf mobil passiert übriegens auch das hier:
> ![grafik](https://user-images.githubusercontent.com/73596957/105154465-de756180-5b09-11eb-8c41-36f7777c0185.png)

Bugfix wird im nächsten Rollout verfügbar sein.

**Comment by andreaschu** [comment]
der Hinweistext ist auch geändert auf: _Bitte geben Sie eine gültige Zahl ein!_ (wie letztes Mal.)
