### ISSUE TITLE
Kalendarium: mobile Ansicht Tiles fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#164]
in den verschiedenen mobilen iPhone Ansichten sind die Tiles optisch teilweise nicht voneinander getrennt.
edit: Ganz Links ist nirgens ein Rahmen
![grafik](https://user-images.githubusercontent.com/73596957/104437061-a1035800-558e-11eb-8838-e048b4920bd1.png)
![grafik](https://user-images.githubusercontent.com/73596957/104437118-b4aebe80-558e-11eb-8683-677494d125ed.png)
![grafik](https://user-images.githubusercontent.com/73596957/104437245-d3ad5080-558e-11eb-901b-c1daf795ceea.png)

**Comment by dzhwmeisner** [comment]
Fehler nicht reproduzierbar. 
![screenshot_cal1_Iphone5](https://user-images.githubusercontent.com/30229399/104730971-4b1fe300-573b-11eb-903f-9e1a6c861a43.png)
![screenshot_cal1_Iphone6](https://user-images.githubusercontent.com/30229399/104730975-4c511000-573b-11eb-9275-8447c07ab527.png)
![screenshot_cal1_IphoneXS](https://user-images.githubusercontent.com/30229399/104730978-4d823d00-573b-11eb-8fec-ce0adf78ebe0.png)

**Comment by dzhwmeisner** [comment]
Die Screenshot sind aufgenommen im SauceLabs- Device Simulator für IPhone5, IPhone6 und IPhone XS

**Comment by AliceFoelker** [comment]
@dzhwmeisner das sieht bei mir jetzt auch wieder gut aus. Scheint behoben zu sein
