### ISSUE TITLE
Kalendarium: Aktivitätenauswahl optisch verrutscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#165]
können wir hier Umbrüche rein machen? Damit das einheitlicher aussieht?
![grafik](https://user-images.githubusercontent.com/73596957/104437660-5d5d1e00-558f-11eb-85d7-2df727d9e8cc.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#163 ) verfügbar
