### ISSUE TITLE
Kalendarium mobil: durchgängige Epi. eintragen funkt. nicht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#166]
funktioniert bei euch das Eintragen der Aktivitätäten auf dem Handy (mobilen Version) durch das Wischen? Bei mir funktioniert es nur durch tippen. Ist bei 2,5 Jahren und einem durchgängigem Studium z.B. ziemlich mühselig. Galaxy S9

**Comment by jocarstensen** [comment]
Wischen geht meines Wisens nicht auf dem Smartphone. Stattdessen soll eigentlich folgende Funktionalität für Smartphones gegeben sein:
1x Tippen auf Start- und Endmonat: Ganzen Zeitraum markieren
2x Tippen: Einzelne Monate markieren

Falls das noch nicht umgesetzt ist, muss das noch passieren.

**Comment by AliceFoelker** [comment]
@andreaschu das funktioniert auf meinem Smartphone (S9) nicht wie in der Anleitung:
1x Tippen auf einen Monat markiert diesen Monat
2x Tippen auf einen Monat: 1. Tippen wählt den Monat an 2. Tippen wählt diesen wieder ab
Wenn ich z.b. Januar antippe und danach direkt Dez. dann sind auch nur diese beiden Monate ausgewählt.
> 
> Wischen geht meines Wisens nicht auf dem Smartphone. Stattdessen soll eigentlich folgende Funktionalität für Smartphones gegeben sein:
> jeweils 1x Tippen auf Start- und Endmonat: Ganzen Zeitraum markieren
> 2x Tippen: Einzelne Monate markieren
> 
> Falls das noch nicht umgesetzt ist, muss das noch passieren.

**Comment by dzhwmeisner** [comment]
Bugfix ist im nächsten Rollout verfügbar
