### ISSUE TITLE
Episoden: Studium/Ausbildung: Anpassung Referenzzeitraum nicht erfolgt

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#167]
tester192 wave=5 
Anpassung von h_enterdatum Juli 2018 in den Texten von allen Folgeseitenvon st(aa)01 im Studienepisodenmodul nicht erfolgt. z.B.: st(aa)04; 07; 09;10;21;23;42 (auf st(aa)47 hat es aber funktioniert). Das taucht ebenso im Ausbildungsmodul auf (den Rest habe ich noch nicht geprüft)
![grafik](https://user-images.githubusercontent.com/73596957/104565769-103f8180-564d-11eb-95dc-4925d0c546c8.png)

**Comment by andreaschu** [comment]
@AliceFoelker hier wird nicht das h_enterdatum eingeblendet, sondern die Eingabe von staa01 und staa02. Weißt Du, was Du da eingegeben hast?
Das ist natürlich inkonsequent, wenn man das da eingeben kann. Aber das geht wohl nicht anders.

**Comment by AliceFoelker** [comment]
@jocarstensen @andreaschu das ist tatsächlich etwas ungünstig, da ich "Beginn vor Juli 2018" angegeben hatte. Dann wird automatisch Januar 2018 ausgewählt, was im Folgenden dann dazu führt, dass überall Januar 2018 steht. :-/

**Comment by andreaschu** [comment]
Bei staa01, wo h_enterdatum verwendet wird, hat es geklappt.

![grafik](https://user-images.githubusercontent.com/30111489/104571506-75967100-5653-11eb-8ce6-11c7403b059c.png)

**Comment by AliceFoelker** [comment]
@andreaschu richtig, auf den darauffolgenden Seiten steht aber Januar 2018 wenn ich "Beginn vor Juli 2018" angebe. Das ist so bestimmt nicht gewollt oder @jocarstensen

**Comment by jocarstensen** [comment]
Das liegt am Javascript bei Selektion der Checkbox. Hab das in #10 angemerkt.

**Comment by AliceFoelker** [comment]
fixed
