### ISSUE TITLE
Episoden: Studium: st(aa)24

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#168]
Wenn man auf st(aa)04 keinen Stuudiengang auswählt, fängt die Liste auf st(aa)24 mit einem Komma an. @jocarstensen Änderungsbedarf?
![grafik](https://user-images.githubusercontent.com/73596957/104566465-e89ce900-564d-11eb-83ce-f96087c2eb68.png)

**Comment by jocarstensen** [comment]
@se-lang Das war letztes Jahr glaube ich auch schon ein bekannter aber nicht korrigierbarer, Fehler, oder? Dann können wir hier leider auch nichts mehr verbessern.

**Comment by se-lang** [comment]
Ja, das ist uns leider letztes Jahr auch schon aufgefallen. Theoretisch wäre der Fehler korrigierbar, allerdings nur mit sehr viel Aufwand und entsprechendem Risiko wieder andere Fehler einzubauen. Deswegen haben wir uns letztes Jahr dafür entschieden das nicht zu ändern. Wenn eine der anderen Informationen fehlt sollte alles funktionieren, nur beim Studiengang wäre die einzige Lösung, die mir einfällt, sehr kompliziert.
Empfehlung meinerseits wäre also das lieber nicht anzugehen.

**Comment by jocarstensen** [comment]
Check, also keine Änderung.
