### ISSUE TITLE
SozDem: msg_15 Skalenbeschriftung verrutscht mobilVersion

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#169]
Vater und Mutter stehen in der mobilVersion nicht über den Auswahlbuttons
![grafik](https://user-images.githubusercontent.com/73596957/104567349-f99a2a00-564e-11eb-9cfd-e4485047fb03.png)

**Comment by vdick** [comment]
sorry, mein Fehler.. 
fixed, ab nächsten Rollout(#170 ) verfügbar
