### ISSUE TITLE
Corona: cor_02 ao6 absetzen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#17]

**Comment by andreaschu** [comment]
Bis eine Bildschirmbreite von 1126 geht es. Danach schon nicht mehr. Da die Skala lang ist und die Labels auch, kann man da nicht mehr viel machen. Bitte auch hier entscheiden, was passieren soll. Soll die Skala für alle vertikal dargestellt werden oder der Umbruch in vertikale Darstellung bei einer Bildschirmbreite von 1125 erfolgen?

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#71 ) verfügbar

**Comment by AliceFoelker** [comment]
bei mir wird es noch nicht abgesetzt dargestellt
![grafik](https://user-images.githubusercontent.com/73596957/102500964-2b829580-407d-11eb-8b78-a28cc5f6d104.png)

**Comment by AliceFoelker** [comment]
fixed
