### ISSUE TITLE
SozDem: msg_20 Skalenbeschriftung verschoben 

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#171]
(1) ist bei allem was größer als 100% gezoomt ist verrutscht dargestellt

![grafik](https://user-images.githubusercontent.com/73596957/104607624-4f87c580-5681-11eb-8902-69967a988e50.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#170) verfügbar
