### ISSUE TITLE
Episoden: Studium (st(aa)24 überlappende aos in mobilVersion

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#172]
Galavy S9/ iPhone5 etc.
![grafik](https://user-images.githubusercontent.com/73596957/104732292-478d5b80-573d-11eb-9be2-7f9a5c62698c.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#177 ) verfügbar

**Comment by AliceFoelker** [comment]
fixed
