### ISSUE TITLE
Ist der Logout BUtton mit Beschriftung versehen?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#173]
Wird der Logout Button in der richtigen Befragung dann eigentlich mit einer Beschriftung versehen? Ich kann es auf den alten Screenshots von 18.3a nicht erkennen.

Screenshot aktuelle Befragung:
![grafik](https://user-images.githubusercontent.com/73596957/104744732-862b1200-574d-11eb-90e8-6ebd6fe752a5.png)

**Comment by andreaschu** [comment]
Der Logout-Button war mal ausgeschrieben, was aber auf mobilen Geräten zu eng war.
