### ISSUE TITLE
Studium: mas_03 "sonstiges" in mobilVersion 

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#174]
@andreaschu @heikQ soll das so aussehen? 
![grafik](https://user-images.githubusercontent.com/73596957/104753300-15d5be00-5758-11eb-96fd-818585860ffb.png)

**Comment by andreaschu** [comment]
@AliceFoelker ja, das offene Feld ist Teil des Items und ist dort oben platziert.
