### ISSUE TITLE
History-Datensatz

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#176]
@andreaschu Ist es möglich einen History-Datensatz mit folgenden Testern anzufertigen?:
tester: 200, 201, 30, 31, 220, 221, 222, 108, 110

**Comment by andreaschu** [comment]
https://myshare.dzhw.eu/index.php/s/zpI9CrUb1pZqPRl
passwort für den Download: studpanel18.3b
