### ISSUE TITLE
Feldvorbereitung

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#179]
Wir benötigen zur Feldvorbereitung noch:

- [x] den genauen Namen der Befragung
- [x] die Teilnehmer mit den Preloads panel-id, wave und incentive

**Comment by heikQ** [comment]
@andreaschu 
- Der Name der Befragung ist: Befragung der Studienberechtigten 2018
- Wie auch bei SLC inter ist es einfacher, wenn wir die wave und incentive preloads zuordnen und ihr uns eine Excel-Liste mit Token gebt und wir die entsprechenden Infos zu spielen und euch dann zurückschicken (id, wave, incentive). Die Token-Liste bitte per Email an Verena Jahn und mich im cc und nicht hier einstellen. Wir benötigen 24.000 Token. Bei den Token bitte folgende Zahlen/Buchstaben ausschließen: klein l, kleine und große i, kleine und große O, 0, ss, SS, sa, SA, HH, hh, 88
- Könnt ihr uns bitte schon den link schicken unter der die Befragung dann ins Feld geht? Wir müssen noch eine Umleitung auf diesen link durch Ruth dann setzen lassen für unsere schriftl. einladungen

**Comment by christian-fr** [comment]
@andreaschu als finalname nehmen wir: 
**studienberechtigte2018**

**Comment by andreaschu** [comment]
Der finale Link wäre dann: https://survey01.dzhw.eu/studienberechtigte2018

**Comment by andreaschu** [comment]
Zur Vorbereitung der Befragung bräuchten wir die Liste mit den Teilnehmer*innen (token und Preloads) am besten auch morgen (Donnerstag). Wenn das ein Problem ist, gebt uns bitte kurz bescheid.

**Comment by heikQ** [comment]
@andreaschu passt, ihr bekommt heute oder morgen Vormittag eine Excel-Datei mit ID (unsere Panel ID der Probanden, brauchen wir nur für Zuordnung), Token, wave, incentive. Die Email-Adresse der Befragten reicht nächste woche oder? Checken gerade noch die bounce adressen von der Ankündigung

**Comment by andreaschu** [comment]
Ja, die E-Mail-Adressen benötigen wir erst nächste Woche.
