### ISSUE TITLE
LIVE-Befragung für finale Testung

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#181]
Für eine finale, scharf gestellte Testung ist der 27.01. vorgesehen. Können wir mit dem Datum rechnen?

**Comment by andreaschu** [comment]
Ja. Wie heute mit @AliceFoelker besprochen, sollten wir mit dem Fragebogen diesen Donnerstag fertig werden, so dass wir es final bearbeiten, testen und ausrollen können.
