### ISSUE TITLE
SozDem: msg_04 (Big 5) überfiltern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#182]

**Comment by andreaschu** [comment]
sehe ich das richtig, dass msg_04 gar nicht mehr angesteuert werden soll?

**Comment by AliceFoelker** [comment]
@andreaschu richtig, ich hoffe ich habe das korrekt überfiltert

**Comment by andreaschu** [comment]
Ja, ist es. Ich wollte nur sicher gehen.

**Comment by AliceFoelker** [comment]
fixed
