### ISSUE TITLE
Indexseiten: kleine Textänderungen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#183]

**Comment by andreaschu** [comment]
beim nächsten Roll-Out verfügbar. 
Es gibt in deiner Version noch zwei Fehler (Mehrzahl, wo nur ein Gutschein vorhanden ist), die ich im QML direkt korrigiert habe.

**Comment by AliceFoelker** [comment]
@andreaschu da hast du recht. Ich habe es auch angepasst. Danke dir!
> 
> Es gibt in deiner Version noch zwei Fehler (Mehrzahl, wo nur ein Gutschein vorhanden ist), die ich im QML direkt korrigiert habe.

**Comment by AliceFoelker** [comment]
@andreaschu da ist jetzt noch ein kleiner Fehler in q451 bei der Aufzählung der Incentive (Sonos, dieses jeweils raus). im letzten commit geändert

**Comment by andreaschu** [comment]
habe ich rausgenommen. Ab nächstem Roll-Out verfügbar.
