### ISSUE TITLE
Episoden: Ausbildung v(aa)25 string zu klein&verschoben

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#184]
Die strings für die Noteneingabe aus v(aa,ba etc.)25 ist sehr klein und nah am Doppelpunkt (gerade für iPhones siehe 2. Screenshot). Kann man das global für alle abgefragten Notenabfragen ändern - also ein wenig größer machen und mehr Abstand zum Doppelpunkt? (im Studienmodul sind die strings bspw. ausreichend groß siehe st(aa)25.

![grafik](https://user-images.githubusercontent.com/73596957/105148205-635c7d00-5b02-11eb-91ce-0dc018916249.png)

**iPhone**
![grafik](https://user-images.githubusercontent.com/73596957/105148240-6eafa880-5b02-11eb-8399-d47c30b8139f.png)

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@andreaschu bei vaa25 ist der 2. string sehr nach am : komisch, denn bei vba25 sieht es gut aus. Das ist aber jetzt auch sehr pingelig von mir. Wenn nur "nice to have" kann hier zu.
![grafik](https://user-images.githubusercontent.com/73596957/105363180-0d6c0000-5bfc-11eb-9ca9-b71ff6df9cf4.png)

**Comment by christian-fr** [comment]
War ein Tippfehler im CSS-Code. Ist ab dem nächsten Rollout korrigiert.
