### ISSUE TITLE
Episoden: Studium: st(aa)07 Doppelpunkt und mehr Abstand zum string

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#185]
![grafik](https://user-images.githubusercontent.com/73596957/105151329-1a0e2c80-5b06-11eb-9451-6f225cc99069.png)

**Comment by christian-fr** [comment]
@AliceFoelker Meinst Du **st(aa)07**?

**Comment by AliceFoelker** [comment]
ja, sorry
> 
> @AliceFoelker Meinst Du **st(aa)07**?

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

Hier als Links zum anklicken, damit Du nicht so viel tippen musst (macht wie gesagt **rst ab dem nächstem Rollout** Sinn):

- [ ] [staa07](https://presentation.dzhw.eu/SLC_2018_3b/staa07.html)
- [ ] [stab07](https://presentation.dzhw.eu/SLC_2018_3b/stab07.html)
- [ ] [stac07](https://presentation.dzhw.eu/SLC_2018_3b/stac07.html)
- [ ] [stad07](https://presentation.dzhw.eu/SLC_2018_3b/stad07.html)
- [ ] [stae07](https://presentation.dzhw.eu/SLC_2018_3b/stae07.html)
- [ ] [stba07](https://presentation.dzhw.eu/SLC_2018_3b/stba07.html)
- [ ] [stbb07](https://presentation.dzhw.eu/SLC_2018_3b/stbb07.html)
- [ ] [stbc07](https://presentation.dzhw.eu/SLC_2018_3b/stbc07.html)
- [ ] [stbd07](https://presentation.dzhw.eu/SLC_2018_3b/stbd07.html)
- [ ] [stca07](https://presentation.dzhw.eu/SLC_2018_3b/stca07.html)
- [ ] [stcb07](https://presentation.dzhw.eu/SLC_2018_3b/stcb07.html)
- [ ] [stcc07](https://presentation.dzhw.eu/SLC_2018_3b/stcc07.html)
- [ ] [stda07](https://presentation.dzhw.eu/SLC_2018_3b/stda07.html)
- [ ] [stdb07](https://presentation.dzhw.eu/SLC_2018_3b/stdb07.html)
- [ ] [stea07](https://presentation.dzhw.eu/SLC_2018_3b/stea07.html)
- [ ] [st0008](https://presentation.dzhw.eu/SLC_2018_3b/st0008.html)

**Comment by AliceFoelker** [comment]
@christian-fr danke, das ist lieb
