### ISSUE TITLE
Episoden: Studium st(aa)09 aos fast überlappend (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#186]
![grafik](https://user-images.githubusercontent.com/73596957/105151530-5d689b00-5b06-11eb-8c54-77270cf721f4.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#191 ) verfügbar

**Comment by AliceFoelker** [comment]
st(aa)09 ist fixed @andreaschu das Problem besteht in jeder Schleife, d.h. auch st(ba)09, ca, da etc. 
ich bin iwie blind davon ausgegangen, dass Layout Probleme auch für die jeweiligen Schleifen immer gefixt wurde. (ich muss jetzt erstmal auch noch alte issues durchgehen) :-/

**Comment by andreaschu** [comment]
Da die Frage in Schleifen und Splits ist, betrifft das noch die Seiten:
sta[b]09 bis st[e][e]09
(In jeder Schleife die Seiten st[a]**a**09, st[a]**b**09, st[a]**c**09, st[a]**d**09 und st[a]**e**09 für alle Schleifen von st**a** bis st**e**)

**Comment by christian-fr** [comment]
Ist korrigiert. Ab nächstem Rollout verfügbar.

@AliceFoelker Hier die Links:
- [ ] [stab09](https://presentation.dzhw.eu/SLC_2018_3b/stab09.html)
- [ ] [stac09](https://presentation.dzhw.eu/SLC_2018_3b/stac09.html)
- [ ] [stad09](https://presentation.dzhw.eu/SLC_2018_3b/stad09.html)
- [ ] [stae09](https://presentation.dzhw.eu/SLC_2018_3b/stae09.html)
- [ ] [stba09](https://presentation.dzhw.eu/SLC_2018_3b/stba09.html)
- [ ] [stbb09](https://presentation.dzhw.eu/SLC_2018_3b/stbb09.html)
- [ ] [stbc09](https://presentation.dzhw.eu/SLC_2018_3b/stbc09.html)
- [ ] [stbd09](https://presentation.dzhw.eu/SLC_2018_3b/stbd09.html)
- [ ] [stca09](https://presentation.dzhw.eu/SLC_2018_3b/stca09.html)
- [ ] [stcb09](https://presentation.dzhw.eu/SLC_2018_3b/stcb09.html)
- [ ] [stcc09](https://presentation.dzhw.eu/SLC_2018_3b/stcc09.html)
- [ ] [stda09](https://presentation.dzhw.eu/SLC_2018_3b/stda09.html)
- [ ] [stdb09](https://presentation.dzhw.eu/SLC_2018_3b/stdb09.html)
- [ ] [stea09](https://presentation.dzhw.eu/SLC_2018_3b/stea09.html)
