### ISSUE TITLE
Ausbildung: aus_03 string abgeschnitten (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#187]
![grafik](https://user-images.githubusercontent.com/73596957/105152502-91908b80-5b07-11eb-976f-a60ba2fdfc3b.png)

**Comment by vdick** [comment]
ab nächsten Rollout( #191 ) verfügbar

**Comment by AliceFoelker** [comment]
fixed
