### ISSUE TITLE
Studium: stu_08 Abstand zwischen in & q verringern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#188]
ist es möglich den Abstand zwischen in und q zu verkleinern? auf dem Handy läd die Seite bei jeder Karussell Seite neu und man muss immer wieder etwas nach unten scrollen. Das kann schnell ermüdent werden, gerade bei so vielen Items.

![grafik](https://user-images.githubusercontent.com/73596957/105152960-25625780-5b08-11eb-9c69-32ac34570853.png)

**Comment by andreaschu** [comment]
ich habe einen Umbruch weggenommen. Beim nächsten Roll-Out verfügbar.
