### ISSUE TITLE
Studium: stu_13 strings verrutscht + zu nah am :

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#189]
![grafik](https://user-images.githubusercontent.com/73596957/105154182-90f8f480-5b09-11eb-92ab-4128f285c2b6.png)
![grafik](https://user-images.githubusercontent.com/73596957/105155223-a02c7200-5b0a-11eb-81a4-ab84b09540a4.png)
![grafik](https://user-images.githubusercontent.com/73596957/105155326-bf2b0400-5b0a-11eb-913d-3fccbb64bbe0.png)

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
