### ISSUE TITLE
Schulabschluss: reife_01 Transition wenn sf funktioniert nicht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#19]
Wenn ich die sf greift und ich die Frage nicht beantworten will bleibe ich auf der Seite hängen (statt reife_03). m.E. stimmt die Transition in der PV.

**Comment by andreaschu** [comment]
@AliceFoelker Ich kann den Fehler nicht reproduzieren.
Hast Du einen Token für mich, damit ich in die DB schauen kann, was da passiert ist?

**Comment by AliceFoelker** [comment]
@andreaschu klar, tester10

**Comment by andreaschu** [comment]
Fehler gefunden und (hoffentlich) korrigiert. Ab Roll Out #61 verfügbar.

**Comment by AliceFoelker** [comment]
fixed
