### ISSUE TITLE
Studium: stu_07 Polung konsistent?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#190]
iwie finde ich die erste ao nicht konsistent?! Wie siehst du das? Wie im Konstruktpapier lassen?

![grafik](https://user-images.githubusercontent.com/73596957/105155659-28ab1280-5b0b-11eb-9cf8-055c5a4e07ab.png)
**aus Konstruktpapier**
![grafik](https://user-images.githubusercontent.com/73596957/105155728-3a8cb580-5b0b-11eb-9caa-dc68acb6e5a5.png)

**Comment by heikQ** [comment]
@AliceFoelker Die PloPolung muss vermuitlich wie im Konstruktpapier sein. Ich finde das auch ungünstig, aber vermutlich eine psychologische Skala, die bauen gern mal so was ein. @jocarstensen Das Konstrukt testen wir für slc, soll es wie im Kontruktpapier bleiben? Die Pole sind dann allerdings tatsächlich etwas verwirrend. Oder drehen wir das erste Item von niederig  zu hoch, damit es in der Logik der anderen ist? Weiß nicht, wie sehr wir am Papier bleiben sollten.

**Comment by jocarstensen** [comment]
Das ist im Konstruktpapier falsch dargestellt. In der originalen Quelle ist Item 1 von niedrig bis hoch gepolt. Also bitte ändern! Ich passe es im Konstruktpapier an.

**Comment by andreaschu** [comment]
Ab nächstem Roll-Out verfügbar.
