### ISSUE TITLE
Zwischenseiten evtl. etwas größer? (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#193]
die Bilder der Zwischenseiten könnten eigentlich etwas größer oder? Auf dem Handy schwer lesbar
![grafik](https://user-images.githubusercontent.com/73596957/105158567-66f60100-5b0e-11eb-9f7f-e23f893ed0bd.png)

**Comment by heikQ** [comment]
würde da jetzt keine Zeit drauf verschwenden, dann müssen wir wieder testen, ob es nicht zu groß ist und richtig angezeigt wird. ist ja halbwegs lesbar
