### ISSUE TITLE
Episoden: Ausbildung: v(aa)10 sf greift nicht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#194]
man kommt weiter ohne eine Eingabe gemacht zu haben. SF wird nicht angezeigt. Laut PV soll das aber so oder?

**Comment by jocarstensen** [comment]
Welche PV meinst Du? Es gibt auf der vaa10 kein sf. Das beißt sich mit dem Rangecheck.

**Comment by AliceFoelker** [comment]
Dann schaue ich offenbar in der falschen PV, das war die einzige, die ich in den Ordnern auf Anhieb finden konnte:
"\\faust\Abtuebergreifend\Projekte\SLC\05_Aufstockung\01_AP_1_Episoden\01_Inhalte\Programmiervorlagen_Flussdiagramme\SLC_PV_Ausbildung_NACH_TEST_2018-08-28.docx"

![grafik](https://user-images.githubusercontent.com/73596957/105162169-8e4ecd00-5b12-11eb-9066-6dd604478413.png)

**Comment by jocarstensen** [comment]
Die ist von August 2018, aus dem ersten Test des Episodeninstruments. Seitdem ist das Episodenmodul zweimal überarbeitet worden. 

Es gibt für die Episoden nur aktuelle Flussdiagramme und keine PVs mehr. Für PVs ist es zu komplex.

**Comment by AliceFoelker** [comment]
oki sorry
