### ISSUE TITLE
Aktualisierung Datenschutzhinweise

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#195]
Wir mussten die Datenschutzhinweise aktualisieren. Bitte die auf den Indexseiten verlinkte Datei mit den Datenschutzhinweisen durch diese Version ersetzen:

[Datenschutzhinweise.pdf](https://github.com/dzhw/studienberechtigte_2018.3b/files/5841652/Datenschutzhinweise.pdf)

**Comment by andreaschu** [comment]
Bei den Datenschutzhinweisen sind nicht die Verwendung der Paradaten wie Bildschirmgröße, verwendetes Gerät und andere Infos aus dem UserAgentString abgedeckt. Soll das so sein?

**Comment by andreaschu** [comment]
Das neue Blatt ist eingefügt und ab dem nächsten Roll-Out verfügbar.

**Comment by jocarstensen** [comment]
Mein Kenntnisstand war, dass die Formulierung "Daten  zur  Art  und  Weise  der  Bearbeitung  des  Fragebogens" Paradaten allgemein abdeckt. @andreaschu Hast Du da andere Informationen?

**Comment by heikQ** [comment]
> Mein Kenntnisstand war, dass die Formulierung "Daten zur Art und Weise der Bearbeitung des Fragebogens" Paradaten allgemein abdeckt. @andreaschu Hast Du da andere Informationen?

In dem Sinne war es zumindest mit FDZ und DZHW-Datenschutzbeuaftragten abgeklärt

**Comment by andreaschu** [comment]
Okay. Es klingt für mich nur nach history-Daten. Bei anderen Erklärungen steht zudem noch "Informationen über das Endgerät". Aber wenn das abgeklärt ist, dann ist das okay für mich.
Also soll der UserAgentString rein, richtig?

**Comment by heikQ** [comment]
ja bitte. Insbesondere Endgerät mobil vs. Desktop wäre schon wichtig als info

**Comment by heikQ** [comment]
ich mach hier mal zu, ist ja erledigt
