### ISSUE TITLE
Episoden: Fort-Weiterbildung: t(aa)05 aos überlappend + : nach zwar (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#196]
![grafik](https://user-images.githubusercontent.com/73596957/105161749-04066900-5b12-11eb-8e72-71ca0f01b534.png)
![grafik](https://user-images.githubusercontent.com/73596957/105161879-2b5d3600-5b12-11eb-8d40-f23e51c791a5.png)

**Comment by christian-fr** [comment]
Doppelpunkte sind hinzugefügt, ein Großteil der CSS-Änderungen auch.

@AliceFoelker Wenn alles fertig ist, hier Links zum Testen:
- [ ] [taa05](https://presentation.dzhw.eu/SLC_2018_3b/taa05.html)
- [ ] [tba05](https://presentation.dzhw.eu/SLC_2018_3b/tba05.html)
- [ ] [tca05](https://presentation.dzhw.eu/SLC_2018_3b/tca05.html)
- [ ] [tda05](https://presentation.dzhw.eu/SLC_2018_3b/tda05.html)
- [ ] [tea05](https://presentation.dzhw.eu/SLC_2018_3b/tea05.html)

--------------------------

@vdick Habe so weit alles abgearbeitet, nur das **überlange Label, das aus der unit herausragt** nicht ("Taxifahrer(innen)-," siehe zweiten Screenshot oben) - kannst Du Dich darum kümmern?

**Comment by christian-fr** [comment]
@vdick Habe so weit alles abgearbeitet, nur das überlange Label, das aus der unit herausragt nicht ("Taxifahrer(innen)-," siehe zweiten Screenshot oben) - kannst Du Dich darum kümmern?
