### ISSUE TITLE
Ausbildung: aus_06 Karussell-Nummerierung abgeschnitten (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#197]
kann man da iwas tun?
![grafik](https://user-images.githubusercontent.com/73596957/105164591-98be9600-5b15-11eb-99cf-e4dd723c27b6.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#215 ) verfügbar

**Comment by AliceFoelker** [comment]
@andreaschu sind immernoch abgeschnitten aber rot?

![grafik](https://user-images.githubusercontent.com/73596957/105369796-2f1cb580-5c03-11eb-90cd-1f173cf02d8d.png)

**Comment by andreaschu** [comment]
@AliceFoelker das ist, glaube ich, noch nicht richtig ausgerollt, sondern erst mit dem nächsten Roll-Out verfügbar. Oder @vdick?

**Comment by vdick** [comment]
@AliceFoelker @andreaschu genau so ist es, es fehlt noch ein entscheidendes Element, sollte aber beim nächsten Mal dabaei sein

**Comment by andreaschu** [comment]
@AliceFoelker aktueller Stand (nicht ausgerollt) ist folgender:
Der sieht zwar okay aus, aber das könnte die Befragten irritieren, denke ich. Die Alternative ist, es ganz auszublenden und die Navigation nur über auto-forward zu lassen. Viktor versucht noch einen nichtnavigierbaren Anzeiger **6/31** einzubauen. Mehr geht nicht.

![image (4)](https://user-images.githubusercontent.com/30111489/105378965-a571e580-5c0c-11eb-9bb0-177245a27a3c.png)
