### ISSUE TITLE
Episoden: Studium st(ba)24 aos überlappend

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#198]
st(ba)24, ca,da etc. 

![grafik](https://user-images.githubusercontent.com/73596957/105187554-34123400-5b33-11eb-8c1c-3b15c5d5619b.png)

**Comment by andreaschu** [comment]
@christian-fr das betrifft die Seiten:
st[b]a24 bis st[e]a24 und st0025

**Comment by christian-fr** [comment]
Bei st0025 sehe ich keine Probleme.
Die anderen sind gefixt, ab nächstem Rollout verfügbar.

**Comment by andreaschu** [comment]
> Bei st0025 sehe ich keine Probleme.
Stimmt. Ich bin bei der Aufzählung nur nach Logik gegangen und wollte die Notschleife oder Endschleife nicht vergessen. Ich habe mir nicht alle Seiten angeschaut.
