### ISSUE TITLE
Upload der PVs

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#2]
Die hier übermittelten PVs bitte wie in der SLC-inter-Befragung in "code" anlgegen, damit wir Korrekturen u. Änderungen danach unter Code in github dort fortlaufend einpflegen können.

PV Modul 1:
[PV_Einstieg_20201104_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5546704/PV_Einstieg_20201104_ZOFAR.docx)

PV Modul 2: 
[PV_Corona_20201112_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5546714/PV_Corona_20201112_ZOFAR.docx)

PV Modul 3:
[PV_schulabschluss_20201026_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5546718/PV_schulabschluss_20201026_ZOFAR.docx)

PV Modul 4:
[PV_ausbildung_20201117_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5567112/PV_ausbildung_20201117_ZOFAR.docx)
@christian-fr 

PV Modul 5:
[PV_studium_20201120_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5573578/PV_studium_20201120_ZOFAR.docx)
@christian-fr 

PV Modul 6:
[PV_Gesundheit_20201120_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5572676/PV_Gesundheit_20201120_ZOFAR.docx)
@christian-fr 

PV Modul 7:
[PV_SozDem_20201123_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5583065/PV_SozDem_20201123_ZOFAR.docx)
@christian-fr

**Comment by christian-fr** [comment]
Module 1, 2 und 3 sind angelegt.

**Comment by heikQ** [comment]
Das ging schnell, danke. Gibt es bereits einen Link zum testen? Wir sehen zu, dass wir die weiteren Module dann auch einstellen.

**Comment by christian-fr** [comment]
Achso - der Code ist angelegt ([Modul01](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul01_Einstieg.md), [Modul02](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul02_Corona.md), [Modul03](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul03_Schulabschluss.md)).

Die Umsetzung der Module selbst ist schon begonnen, aber noch nicht fertig.

**Comment by AliceFoelker** [comment]
PV Modul 4:
[PV_ausbildung_20201117_ZOFAR.docx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5567062/PV_ausbildung_20201117_ZOFAR.docx)
@christian-fr

**Comment by AliceFoelker** [comment]
Modul04, Modul05 und Modul06 nachträglich hinzugefügt. Bitte dazu jeweilige Codes anlegen.
In Modul05 befinden sich noch 3 Kommentare mit Fragen bzw. Anmerkungen. ggf. Rücksprache gerne mit mir.
@christian-fr

**Comment by christian-fr** [comment]
Die neuen Programmiervorlagen sind im "Code"-Bereich in GitHub eingefügt.

**Comment by andreaschu** [comment]
Die folgenden Module sind gebaut und können getestet werden:

- [x] [Modul01_Einstieg](https://github.com/dzhw/studienberechtigte_2018.3b/commit/a953715e189f323379f1aae89e7cd110e7088302)
- [x] [Modul02_Corona](https://github.com/dzhw/studienberechtigte_2018.3b/commit/06d41fc474b7f1c0577d76ebcf8b6b3fcf7f53d6)
- [x] [Modul03_Schulabschluss](https://github.com/dzhw/studienberechtigte_2018.3b/commit/e9586823f7550ac130896b2bbe0ca6374a61beff)
- [x] [Modul04_Ausbildung](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul04_Ausbildung.md), commit: https://github.com/dzhw/studienberechtigte_2018.3b/commit/079424c6a2dafd7ef6d165ec785eaa76a9556e69
- [x] [Modul05_Studium](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul05_Studium.md), commit: https://github.com/dzhw/studienberechtigte_2018.3b/commit/079424c6a2dafd7ef6d165ec785eaa76a9556e69
- [x] [Modul06_Gesundheit](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul06_Gesundheit.md), commit: https://github.com/dzhw/studienberechtigte_2018.3b/commit/079424c6a2dafd7ef6d165ec785eaa76a9556e69
- [x] [Modul07_SozDem](https://github.com/dzhw/studienberechtigte_2018.3b/commit/4f102f959cde63eaf163dd60cd39d86078fa1953)

**Zugang ist:**
https://presentation.dzhw.eu/SLC_2018_3b/
**Token:** _tester1 - tester100_

PRELOADwave kann für das erste Testen auf der index-Seite eingegeben werden.

**FlowCharts** (zum Testen der programmierten Transitionen)
[index](https://user-images.githubusercontent.com/30111489/100613302-9b222200-3314-11eb-9cfd-b39d2506d2cd.png)
[Einstieg](https://user-images.githubusercontent.com/30111489/100613288-98bfc800-3314-11eb-98a7-9bbc175b4de2.png)
[Corona](https://user-images.githubusercontent.com/30111489/100613290-99585e80-3314-11eb-81d9-a8c4935d1a62.png)
[Schulabschluss](https://user-images.githubusercontent.com/30111489/100613293-99f0f500-3314-11eb-92d9-88d32832dda0.png)
[Ausbildung](https://user-images.githubusercontent.com/30111489/100613294-99f0f500-3314-11eb-80d0-7031bb3cfd21.png)
[Studium](https://user-images.githubusercontent.com/30111489/100613296-99f0f500-3314-11eb-9dc5-93f9a0e5a133.png)
[Gesundheit](https://user-images.githubusercontent.com/30111489/100613297-9a898b80-3314-11eb-82c6-323b17bcbf55.png)
[SozDem](https://user-images.githubusercontent.com/30111489/100613298-9a898b80-3314-11eb-9fa9-22c5427154f4.png)

**Comment by andreaschu** [comment]
Ich habe wieder ein [Wiki](https://github.com/dzhw/studienberechtigte_2018.3b/wiki) erstellt für die wichtigsten Infos (z.B. Link, Token, Zeitplan etc.)
Für Fehlerrückmeldungen bitte je ein Issue pro Problem.
Dieses Issue schließe ich damit. Es kann ja weiterhin aufgerufen werden.

**Comment by heikQ** [comment]
Zeitplan hab ich im Wiki ergänzt
