### ISSUE TITLE
SozDem: msg_03 falsche Skallierung

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#20]
11 Antwortoptionen nicht 7

**Comment by andreaschu** [comment]
@vdick kannst Du mal gucken, ob Du den Abstand zur Skala noch verändern kannst? Ansonsten würde ich bei width<=767 in eine vertikale Skalenansicht übergehen.

![grafik](https://user-images.githubusercontent.com/30111489/101666464-89482980-3a4e-11eb-8256-3c1cd4f83f50.png)

**Comment by AliceFoelker** [comment]
@andreaschu von horizontal zu vertikal geändert
