### ISSUE TITLE
Episoden: selb. ET se(aa,ba, etc.)41 & 25 & 17 fehlerhafte Darstellung (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#200]
überlappende strings und aos sowie sehr wenig Abstand zwischen den Fragen
![grafik](https://user-images.githubusercontent.com/73596957/105208146-a5a8ad00-5b48-11eb-93cd-230dd8369ef9.png)

**Comment by AliceFoelker** [comment]
@andreaschu wie kann ich jeweils verdeutlichen, wenn ich alle Folgeseiten bzw. Schleifen meine? z.B. seaa41, seba41 etc.? Denn wenn iwo ein Fehler ist, dann ist er ja meist überall

**Comment by andreaschu** [comment]
@AliceFoelker am besten indem Du immer den variablen Teil in eckige Klammern schreibst, also entweder [a]a01 für Schleifen oder a[a]01 für Splits.

**Comment by andreaschu** [comment]
@vdick Seiten 
- [ ] se[a]a41 bis se[e]a41
- [ ] se[a]a25 bis se[e]a25
- [ ] se[a]a17 bis se[e]a17

**Comment by andreaschu** [comment]
@vdick entschuldige, das betrifft auch hier die Schleifen und Splits. Also in jeder Schleife auch die Splits [a] bis [e]. Deswegen hier noch mal die Splits dazu:

- [ ] se[a][**a**]41 bis se[e][**e**]41
- [ ] se[a][**a**]25 bis se[e][**a**]25
- [ ] se[a][**a**]17 bis se[e][**a**]17 und 
- [ ] sezz17

**Comment by vdick** [comment]
fixed, ab nächsten Rollout(#207 ) verfügbar

**Comment by AliceFoelker** [comment]
@andreaschu @vdick strings sind gefixt aber nun leider unten überall etwas verschoben
![grafik](https://user-images.githubusercontent.com/73596957/105371185-a30b8d80-5c04-11eb-8f2b-6d1694b478a5.png)

**Comment by andreaschu** [comment]
- [ ] [seaa17](https://presentation.dzhw.eu/SLC_2018_3b/seaa17.html)
- [ ] [seab17](https://presentation.dzhw.eu/SLC_2018_3b/seab17.html)
- [ ] [seac17](https://presentation.dzhw.eu/SLC_2018_3b/seac17.html)
- [ ] [sead17](https://presentation.dzhw.eu/SLC_2018_3b/sead17.html)
- [ ] [seae17](https://presentation.dzhw.eu/SLC_2018_3b/seae17.html)
- [ ] [seba17](https://presentation.dzhw.eu/SLC_2018_3b/seba17.html)
- [ ] [sebb17](https://presentation.dzhw.eu/SLC_2018_3b/sebb17.html)
- [ ] [sebc17](https://presentation.dzhw.eu/SLC_2018_3b/sebc17.html)
- [ ] [sebd17](https://presentation.dzhw.eu/SLC_2018_3b/sebd17.html)
- [ ] [seca17](https://presentation.dzhw.eu/SLC_2018_3b/seca17.html)
- [ ] [secb17](https://presentation.dzhw.eu/SLC_2018_3b/secb17.html)
- [ ] [secc17](https://presentation.dzhw.eu/SLC_2018_3b/secc17.html)
- [ ] [seda17](https://presentation.dzhw.eu/SLC_2018_3b/seda17.html)
- [ ] [sedb17](https://presentation.dzhw.eu/SLC_2018_3b/sedb17.html)
- [ ] [seea17](https://presentation.dzhw.eu/SLC_2018_3b/seea17.html)
- [ ] [seaa25](https://presentation.dzhw.eu/SLC_2018_3b/seaa25.html)
- [ ] [seab25](https://presentation.dzhw.eu/SLC_2018_3b/seab25.html)
- [ ] [seac25](https://presentation.dzhw.eu/SLC_2018_3b/seac25.html)
- [ ] [sead25](https://presentation.dzhw.eu/SLC_2018_3b/sead25.html)
- [ ] [seae25](https://presentation.dzhw.eu/SLC_2018_3b/seae25.html)
- [ ] [seba25](https://presentation.dzhw.eu/SLC_2018_3b/seba25.html)
- [ ] [sebb25](https://presentation.dzhw.eu/SLC_2018_3b/sebb25.html)
- [ ] [sebc25](https://presentation.dzhw.eu/SLC_2018_3b/sebc25.html)
- [ ] [sebd25](https://presentation.dzhw.eu/SLC_2018_3b/sebd25.html)
- [ ] [seca25](https://presentation.dzhw.eu/SLC_2018_3b/seca25.html)
- [ ] [secb25](https://presentation.dzhw.eu/SLC_2018_3b/secb25.html)
- [ ] [secc25](https://presentation.dzhw.eu/SLC_2018_3b/secc25.html)
- [ ] [seda25](https://presentation.dzhw.eu/SLC_2018_3b/seda25.html)
- [ ] [sedb25](https://presentation.dzhw.eu/SLC_2018_3b/sedb25.html)
- [ ] [seea25](https://presentation.dzhw.eu/SLC_2018_3b/seea25.html)
- [ ] [seaa41](https://presentation.dzhw.eu/SLC_2018_3b/seaa41.html)
- [ ] [seab41](https://presentation.dzhw.eu/SLC_2018_3b/seab41.html)
- [ ] [seac41](https://presentation.dzhw.eu/SLC_2018_3b/seac41.html)
- [ ] [sead41](https://presentation.dzhw.eu/SLC_2018_3b/sead41.html)
- [ ] [seae41](https://presentation.dzhw.eu/SLC_2018_3b/seae41.html)
- [ ] [seba41](https://presentation.dzhw.eu/SLC_2018_3b/seba41.html)
- [ ] [sebb41](https://presentation.dzhw.eu/SLC_2018_3b/sebb41.html)
- [ ] [sebc41](https://presentation.dzhw.eu/SLC_2018_3b/sebc41.html)
- [ ] [sebd41](https://presentation.dzhw.eu/SLC_2018_3b/sebd41.html)
- [ ] [seca41](https://presentation.dzhw.eu/SLC_2018_3b/seca41.html)
- [ ] [secb41](https://presentation.dzhw.eu/SLC_2018_3b/secb41.html)
- [ ] [secc41](https://presentation.dzhw.eu/SLC_2018_3b/secc41.html)
- [ ] [seda41](https://presentation.dzhw.eu/SLC_2018_3b/seda41.html)
- [ ] [sedb41](https://presentation.dzhw.eu/SLC_2018_3b/sedb41.html)
- [ ] [seea41](https://presentation.dzhw.eu/SLC_2018_3b/seea41.html)
- [ ] [sezz17](https://presentation.dzhw.eu/SLC_2018_3b/sezz17.html)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#218 ) verfügbar
