### ISSUE TITLE
Schulabschluss: reife_02 aos dicht aneinander (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#201]
![grafik](https://user-images.githubusercontent.com/73596957/105201216-e7cdf080-5b40-11eb-93e2-4214a0f9720b.png)

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@andreaschu @christian-fr können wir das für das iPhone5/6 noch ein wenig auseinander ziehen, oder meint ihr das reicht so?

![grafik](https://user-images.githubusercontent.com/73596957/105372645-19f55600-5c06-11eb-87e8-55dec67ab8dd.png)

**Comment by andreaschu** [comment]
hätte wohl eine niedrigere Priorität, oder?

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#218 ) verfügbar
