### ISSUE TITLE
Episoden: Studium: st(aa)25 sehr enge aos (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#203]
st(aa, etc.) für jede Schleife)
![grafik](https://user-images.githubusercontent.com/73596957/105204271-49dc2500-5b44-11eb-91ad-c0b5c9170357.png)

**Comment by andreaschu** [comment]
@AliceFoelker kannst Du bitte nicht benutzerdefinierte Ansichten melden, sondern nur bestimmte Geräte?
