### ISSUE TITLE
Add-On Layout.

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#206]
Die Label sind nicht auf der Linie mit den offenen Feldern und die Felder sind sehr klein.
Vielleicht ist es gut das CSS von der letzten Befragung zu kopieren.

![grafik](https://user-images.githubusercontent.com/30111489/105331927-5019e200-5bd4-11eb-8a55-8f4503618c75.png)

**Comment by christian-fr** [comment]
Ist geändert und bereits neu ausgerollt.
