### ISSUE TITLE
SozDem: msg_16 (mobil) Karussell ungünstig bei Fragestellung

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#208]
ich finde das Karussell an dieser Stelle ziemlich ungünstig. Man muss alle Seiten durchblättern um sich überhaupt ein Bild zu verschaffen und dann müsste man theoretisch auswählen. Bei Items ist das m.E. ok weil jede Frage beantwortet werden muss, hier allerdings nicht?! @heikQ wie siehst du das?

![grafik](https://user-images.githubusercontent.com/73596957/105340699-86f4f580-5bde-11eb-89c2-72f84f938902.png)

**Comment by heikQ** [comment]
@AliceFoelker stimmt, Karussell geht hier gar nicht, so kann man die Frage nicht beantworten. Wenn es nicht anders geht machen wir dropdown-menüs erst für Vater und dadrunter für Mutter

**Comment by andreaschu** [comment]
Wir können das Karussell nicht nach den Überschriften/Kategorien umbrechen lassen. Alternativ können wir in Abhängigkeit von der Variable width unterschiedliche Varianten einblenden: die Matrix für größere Bildschirme und zwei einzelne Multiple Choice Fragen untereeinander für kleinere Bildschirme. Da bleibt die Unschärfe des Medienwechsels, weil die Variable auf der Index-Seite gesetzt wird. Wechsler sind aber nur von einem kleinen Prozentsatz zu erwarten.

**Comment by heikQ** [comment]
> Matrix für größere Bildschirme und zwei einzelne Multiple Choice Fragen untereinander für kleinere Bildschirme.

@andreaschu @AliceFoelker Okay, dann machen wir das so, dann bleiben auch die Merhfachao

**Comment by AliceFoelker** [comment]
@andreaschu muss ich dafür iwas in der PV ändern?
> > Matrix für größere Bildschirme und zwei einzelne Multiple Choice Fragen untereinander für kleinere Bildschirme.
> 
> @andreaschu @AliceFoelker Okay, dann machen wir das so, dann bleiben auch die Merhfachao

**Comment by andreaschu** [comment]
Ab nächstem Roll-Out verfügbar.

**Comment by andreaschu** [comment]
> @andreaschu muss ich dafür iwas in der PV ändern?

Korrekt wäre, wenn in der PV noch eine Variante rein kommt, mit zwei einfachen MultipleChoice mit denselben Variablennamen, Fragetexten etc. und der Einblendbedingung über width>=768 (Matrix) bzw. width<768 (kleine Anzeige).

**Comment by AliceFoelker** [comment]
@andreaschu dann muss ich kurz grübeln wie ich das praktisch umsetze.

> > @andreaschu muss ich dafür iwas in der PV ändern?
> 
> Korrekt wäre, wenn in der PV noch eine Variante rein kommt, mit zwei einfachen MultipleChoice mit denselben Variablennamen, Fragetexten etc. und der Einblendbedingung über width>=768 (Matrix) bzw. width<768 (kleine Anzeige).
