### ISSUE TITLE
SozDem: msg_15 Bereich für offene Angaben verschoben

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#21]
Der Bereich für die offene Antwort bei Item 7 ist verschoben und zu klein.
Könnte man außerdem ao1 Vater und ao2 Mutter ein wenig weiter nach oben schieben? so ist es etwas eng.

**Comment by andreaschu** [comment]
@vdick kannst Du hier bitte noch mal dein Bestes versuchen?
@AliceFoelker der Platz für die offenen Antworten ist bei dem Frage-Typ sehr schwierig, da das Feld entweder zu klein ist, oder in die andere Skala übergeht. Responsiv passiert bei dem Fragetyp auch nichts. Eine Alternative wäre die Frage in zwei Fragen aufzuteilen (je eine SingleChoice für Mutter und Vater), ggf. auch nur für kleinere Bildschirme.

**Comment by AliceFoelker** [comment]
Huch hier ist noch einiges mehr schief gegangen. @heikQ wollen wir es hier so machen wie Andrea es vorgschlagen hat mit 2 getrennten Seiten für Mutter und Vater? Oder hast du eine andere Idee? So kann es jedenfalls nicht bleiben.

![grafik](https://user-images.githubusercontent.com/73596957/101751887-2055c580-3ad1-11eb-95b7-4c5c5a8561d2.png)

**Comment by heikQ** [comment]
bitte einfach wieder so, ging 2018.2 ja auch:
![image](https://user-images.githubusercontent.com/52539440/101780869-658cee00-3af7-11eb-9347-627451a93876.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (issue #61) verfügbar.
@heikQ so einfach geht es leider nicht. Der Screenshot bzw. das Design gehört noch zu einer alten( **nicht responsiven**) Version von Zofar

**Comment by AliceFoelker** [comment]
fixed
