### ISSUE TITLE
h_studakt

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/studienberechtigte_2018.3b#210]
@andreaschu Könnt Ihr bitte nochmal checken, an welchen Stellen h_studakt Verwendung findet? Laut unseren Recherchen dürfte es neben dem Triggern auf zwischen_k nur noch auf _msg_06_ auftauchen.

**Comment by andreaschu** [comment]
Den Trigger auf zwischen_k habe ich doch wieder rausgenommen, weil es letztes Mal dort auch nicht getriggert wurde.

Es wird auf zwischen_st getriggert und auf msg_06 für Einblendung verwendet, mal abgesehen von der Anzeige auf hilfsvar und zwischen_k. Aber die Anzeigen sind ja nur für Testzwecke da.

**Comment by jocarstensen** [comment]
> Den Trigger auf zwischen_k habe ich doch wieder rausgenommen, weil es letztes Mal dort auch nicht getriggert wurde.

Entschuldigung, ich meinte zwischen_st

**Comment by jocarstensen** [comment]
#213 ähem... hust...

**Comment by jocarstensen** [comment]
Zur Erklärung: Wenn jemand ein einmal angegebenes Studium wieder gelöscht hat, wurde h_studever zwar angepasst, h_studakt aber nicht. Das soll durch den Commit korrigiert werden.

**Comment by andreaschu** [comment]
Beim nächsten Roll-Out verfügbar.

**Comment by AliceFoelker** [comment]
funktioniert

**Comment by AliceFoelker** [comment]
@andreaschu hier scheint es offenbar doch noch ein problem zu geben. wir vermuten, dass h_studakt nicht aus dem Kalendarium befüllt wird. Das ist aber gerade schwierig zu testen, da wir die Hilfsvariablen nicht einsehen können. Kannst du da vielleicht noch mal nachsehen?
@jocarstensen @heikQ
