### ISSUE TITLE
Corona: cor_03 & cor_04 & cor_05 sonstiges string in Karussell sehr klein(mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#211]
der string ist ziemlich klein. Ich befürchte das kann man nicht global für alle offenen Angaben der Karussells lösen?! @andreaschu 
![grafik](https://user-images.githubusercontent.com/73596957/105349553-2966a600-5bea-11eb-9640-79b6e45eb09f.png)

**Comment by andreaschu** [comment]
@AliceFoelker das ist schwierig, weil nicht viel Platz ist. Wenn wir es sehr groß machen würden, dann würde es sich ggf. überlappen. der Bildschirm gekippt bietet hier auch mehr Eingabeplatz. 
Zudem ist die Antwortmöglichkeit nicht ganz konsistent. Denn wenn es ein **sonstiges** gibt, dann brauch man ja nicht mehr _ja/nein/trifft nicht zu_ angeben. Ich würde davon ausgehen, dass nicht häufig etwas eingetragen wird.

**Comment by AliceFoelker** [comment]
@heikQ @jocarstensen sieht nicht besonders gut aus, aber so lassen?

**Comment by jocarstensen** [comment]
Ich sehe auch das Problem der Inkonsistenz, das Andrea oben beschrieben hat. Ich habe aber für beides keine Idee.

**Comment by AliceFoelker** [comment]
@andreaschu @jocarstensen wenn es für das Sontiges-Problem und dem Karussell jetzt keine Lösung gibt, dann mache ich hier zu. Wenn jemand Angaben machen möchte kann er/sie das ja tun.

**Comment by jocarstensen** [comment]
@AliceFoelker Warte doch bitte noch Heikos Votum am Montag ab.

**Comment by heikQ** [comment]
mir fällt da auch keine gute lösung ein. würde es wohl so lassen
