### ISSUE TITLE
Episoden: ET: em[a][a]40 sonstiges string klein und nah am : (mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#212]
Its es möglich den string für alle Seiten (Schleifen/Splits) etwas größer und mit mehr Abstand zum Doppelpunkt auszurichten?
(Der  Screenshot ist von einer SHK iPhone, S9 sieht es genauso aus)
![grafik](https://user-images.githubusercontent.com/73596957/105350443-7a2ace80-5beb-11eb-8e87-47d4ad139eaa.png)

**Comment by andreaschu** [comment]
Die gesamte Liste (die Seite 40 gibt es nicht in jedem Split):
- [ ] [emaa40](https://presentation.dzhw.eu/SLC_2018_3b/emaa40.html)
- [ ] [emba40](https://presentation.dzhw.eu/SLC_2018_3b/emba40.html)
- [ ] [emca40](https://presentation.dzhw.eu/SLC_2018_3b/emca40.html)
- [ ] [emda40](https://presentation.dzhw.eu/SLC_2018_3b/emda40.html)
- [ ] [emea40](https://presentation.dzhw.eu/SLC_2018_3b/emea40.html)
- [ ] [emfa40](https://presentation.dzhw.eu/SLC_2018_3b/emfa40.html)
- [ ] [em0040](https://presentation.dzhw.eu/SLC_2018_3b/em0040.html)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#215 ) verfügbar

**Comment by andreaschu** [comment]
Weitere Fälle mit zwei SingleChoice auf einer Seite:
@vdick für Dich: [em[]28.txt](https://github.com/dzhw/studienberechtigte_2018.3b/files/5851259/em.28.txt)
Und zum Abhaken:
- [ ] [em0028](https://presentation.dzhw.eu/SLC_2018_3b/em0028.html)
- [ ] [emaa28](https://presentation.dzhw.eu/SLC_2018_3b/emaa28.html)
- [ ] [emab28](https://presentation.dzhw.eu/SLC_2018_3b/emab28.html)
- [ ] [emac28](https://presentation.dzhw.eu/SLC_2018_3b/emac28.html)
- [ ] [emad28](https://presentation.dzhw.eu/SLC_2018_3b/emad28.html)
- [ ] [emae28](https://presentation.dzhw.eu/SLC_2018_3b/emae28.html)
- [ ] [emaf28](https://presentation.dzhw.eu/SLC_2018_3b/emaf28.html)
- [ ] [emba28](https://presentation.dzhw.eu/SLC_2018_3b/emba28.html)
- [ ] [embb28](https://presentation.dzhw.eu/SLC_2018_3b/embb28.html)
- [ ] [embc28](https://presentation.dzhw.eu/SLC_2018_3b/embc28.html)
- [ ] [embd28](https://presentation.dzhw.eu/SLC_2018_3b/embd28.html)
- [ ] [embe28](https://presentation.dzhw.eu/SLC_2018_3b/embe28.html)
- [ ] [emca28](https://presentation.dzhw.eu/SLC_2018_3b/emca28.html)
- [ ] [emcb28](https://presentation.dzhw.eu/SLC_2018_3b/emcb28.html)
- [ ] [emcc28](https://presentation.dzhw.eu/SLC_2018_3b/emcc28.html)
- [ ] [emcd28](https://presentation.dzhw.eu/SLC_2018_3b/emcd28.html)
- [ ] [emda28](https://presentation.dzhw.eu/SLC_2018_3b/emda28.html)
- [ ] [emdb28](https://presentation.dzhw.eu/SLC_2018_3b/emdb28.html)
- [ ] [emdc28](https://presentation.dzhw.eu/SLC_2018_3b/emdc28.html)
- [ ] [emea28](https://presentation.dzhw.eu/SLC_2018_3b/emea28.html)
- [ ] [emeb28](https://presentation.dzhw.eu/SLC_2018_3b/emeb28.html)
- [ ] [emfa28](https://presentation.dzhw.eu/SLC_2018_3b/emfa28.html)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#218 ) verfügbar
