### ISSUE TITLE
Gif´s für die Zwischenseiten der Kalendarien

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#214]
Wir haben die neuen gifs für die zwischen_cal Seiten fertig. Bitte mit den alten austauschen. Der Alternativtext, der angezeigt wird, falls ein gif nicht geladen wird, soll bleiben, aber wie bei slc-inter eben nur angezeigt werden, falls die gifs nicht dargestellt werden.

Hier als zip-Datei: 
[GIFs.zip](https://github.com/dzhw/studienberechtigte_2018.3b/files/5849783/GIFs.zip)

Und einzeln (weiß nicht, ob github hier was komprimiert beim hochladen, daher das zip)
1. wave 1, dektop, Seite: zwischen_cal_ad
![wave1_desktop](https://user-images.githubusercontent.com/52539440/105361170-b5cc9500-5bf9-11eb-9708-2a8eadbcd824.gif)

2.  wave 1, mobil, Seite: zwischen_cal_am
![wave1_mobil](https://user-images.githubusercontent.com/52539440/105361249-c977fb80-5bf9-11eb-8028-4ec037ce5d8e.gif)

3. wave 2-5, desktop, Seite: zwischen_cal_bd
![wave2-5_desktop](https://user-images.githubusercontent.com/52539440/105361348-e57b9d00-5bf9-11eb-841d-1da09d0f20e2.gif)

4. wave 2-5, mobil, Seite: zwischen_cal_bm
![wave2-5_mobil](https://user-images.githubusercontent.com/52539440/105361470-ff1ce480-5bf9-11eb-9c55-f8bec8522bd3.gif)

**Comment by christian-fr** [comment]
> Der Alternativtext, der angezeigt wird, falls ein gif nicht geladen wird, soll bleiben, aber wie bei slc-inter eben nur angezeigt werden, falls die gifs nicht dargestellt werden.

@heikQ Das wird wohl nicht auf allen Plattformen funktionieren. Alternativtexte sind laut HTML-Spezifikation zwar Pflicht und sind auch grundsätzlich in allen Browsern implementiert. Leider gibt es aber offenbar seit Jahren einen Bug in der Browserengine **WebKit** [(siehe auch hier)](https://github.com/dzhw/studienberechtigte_2018.3b/issues/114#issuecomment-753992750) durch den bei langen Alt-Texten einfach gar nichts angezeigt wird. Das betrifft nach unserem derzeitigen Wissensstand wohl Safari auf MacOS und mutmaßlich alle Apple Mobilgeräte.

**Comment by heikQ** [comment]
ok

**Comment by andreaschu** [comment]
Ab nächstem Roll-Out verfügbar.

**Comment by AliceFoelker** [comment]
habe wave 1 & 4 mobil und desktop auf firefox getestet - hat funktioniert. Müsste aber vermutlich noch mal auf Safari oder so erfolgen?!

**Comment by heikQ** [comment]
@AliceFoelker Safari funzt, gerade getestet
