### ISSUE TITLE
Einstieg: beg_04 Hinweis für Karussell? mobil

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#219]
funktioniert das Karussell in der mobil-Version eigentlich intuitiv oder wäre da vielleicht ein Hinweis sinnvoll?
was sagen da die Werte aus der Vergangenheit?
![grafik](https://user-images.githubusercontent.com/73596957/105464175-66d23e80-5c91-11eb-900a-c0f50aac4936.png)

**Comment by andreaschu** [comment]
@AliceFoelker bei den SingleChoice-Matrizen gibt es ein Auto-forwarding. Beim Kalendarium (cal25) direkt wäre es evtl. sinnvoll.

**Comment by jocarstensen** [comment]
Beim Kalendarium steht das in der Ausfüllanweisung (GIFs).

**Comment by AliceFoelker** [comment]
@jocarstensen @heikQ Sollen wir beim ersten Vorkommen einen Hinweis hinzufügen? Mit fällt aber gerade auch keine gute Formulierung ein...z.B. Hinweis: Blättern zwischen den Frage- und Antwortoptionen über die Pfeile unten links und rechts?

War aber auch nur so eine Idee, wenn das schon immer so lief ohne Ausfüllhinweis dann kann hier zu.

**Comment by jocarstensen** [comment]
Das ist mit Autoforwarding m.E. nicht notwendig.

**Comment by jocarstensen** [comment]
@AliceFoelker Warte doch bitte noch Heikos Votum am Montag ab.
