### ISSUE TITLE
Modul 5, Seite stu_10

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#22]
Code gefixed: Fragetext q2 gelöscht, nur noch ein Fragetext ohne vc´s

**Comment by andreaschu** [comment]
Die zweite Frage ist gelöscht.

@heikQ könntest Du in Zukunft bei Anpassungen der Programmiervorlage den Commit mit angeben, damit wir nicht so lange suchen müssen (gerade, wenn es komplexer als das hier ist)?
Den Commit findest Du hier: 
![grafik](https://user-images.githubusercontent.com/30111489/101661655-d32e1100-3a48-11eb-9ad2-0e7f745d1556.png)
oder hier:
![grafik](https://user-images.githubusercontent.com/30111489/101661825-07a1cd00-3a49-11eb-8314-b0be29732333.png)

**Comment by AliceFoelker** [comment]
fixed
