### ISSUE TITLE
Text für Ausfüllhinweis ändern (wave 1 mobil)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#220]
für wave 1 mobil sollen lediglich 4 Ausfüllhinweispunkte angezeigt werden. Den 5. bitte für diese wave rausnehmen.
![grafik](https://user-images.githubusercontent.com/73596957/105485380-136de980-5cad-11eb-927f-b7c1be48be1d.png)

**Comment by andreaschu** [comment]
Ab nächtsen Roll-Out verfügbar
