### ISSUE TITLE
Endseite: end Grafik nicht an mobil Bilds. angepasst

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#223]
das ist komisch. Sonst hatte es immer funktioniert. Ich bin auch über die relevanten Seiten für die Bildschirmauflösung gegangen!

![grafik](https://user-images.githubusercontent.com/73596957/105677560-4c47d180-5eec-11eb-8440-080a4c4a81cf.png)

**Comment by andreaschu** [comment]
oh, das ist passiert, weil ich die Endseiten angepasst hatte. Wird korrigiert.

**Comment by christian-fr** [comment]
Bin dran.

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
