### ISSUE TITLE
Logout-Button für Live-Version rausnehmen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#224]

**Comment by andreaschu** [comment]
@AliceFoelker ist das schon ein Arbeitsauftrag an uns, oder noch Diskussion?

**Comment by AliceFoelker** [comment]
@andreaschu ist ein Arbeitsauftrag :-)

**Comment by christian-fr** [comment]
Ist erledigt. Ab nächstem Rollout verfügbar.
