### ISSUE TITLE
Studium: stu_13 wording (derzeitig) raus

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#226]
das Wort müsste noch raus. Ist das noch möglich?
![grafik](https://user-images.githubusercontent.com/73596957/105704418-0fd99d00-5f0f-11eb-97c7-a3630a85a46b.png)

**Comment by andreaschu** [comment]
@AliceFoelker es ist schon ausgerollt, aber wenn wir es noch mal ausrollen müssen, dann ist es  geändert.
