### ISSUE TITLE
Produktivbefragung

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#227]
Die Befragung ist nun produktiv erreichbar unter: …
bzw. unter den DirectLinks in der Tabelle [Testtoken_produktiv.xlsx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5866469/Testtoken_produktiv.xlsx).

Hierbei sollte auch der Sprung zur Add-On funktionieren.

**Comment by AliceFoelker** [comment]
tester1-5: Alice

**Comment by andreaschu** [comment]
@heikQ, @AliceFoelker und @jocarstensen für das Ausrollen der letzten Änderungen auf dem Produktivsystem warten wir auf das GO von Euch. Dafür sollte nun aber alles stehen.

**Comment by AliceFoelker** [comment]
@andreaschu wir geben unser GO für das Ausrollen auf dem Produktivsystem.

**Comment by andreaschu** [comment]
Die Befragung ist wieder online.
