### ISSUE TITLE
Fehler in Triggern auf zwischen_k

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/studienberechtigte_2018.3b#228]
Falsche Anpassung bei den Triggern auf zwischen_k für wave==1
nohaupt wurde (u.A.) durch Schule statt Studium getriggert

**Comment by andreaschu** [comment]
habe ich eingebaut. es kann jetzt getestet werden.

**Comment by AliceFoelker** [comment]
@jocarstensen @heikQ bislang hat es in jeder meiner Durchgänge gepasst, wenn euch auch nichts aufgefallen ist schließe ich hier

**Comment by heikQ** [comment]
von mir aus kann zu
