### ISSUE TITLE
Einstieg: Mobile Version beg_04 it2 keine Skallierungspunkte

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#23]
mit dem Smartphone hat Item 2 keine Zahlen bei den Skallierungen sehr gut **(1), (2), (3), (4**) sehr schlecht **(5)**, Item 1 und 3 haben das schon und das fällt beim Blättern auf.

**Comment by andreaschu** [comment]
@christian-fr oder @vdick kann sich beg_04 mal einer ansehen?

**Comment by AliceFoelker** [comment]
@andreaschu ja, Skalenbeschriftung gefixt ABER in der mobilen Version sind die dick markierten Textstellen nicht dick.

**Comment by vdick** [comment]
@andreaschu bin dabei

**Comment by AliceFoelker** [comment]
fixed
