### ISSUE TITLE
transition check

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#230]
@jocarstensen und @se-lang 
Könnt ihr noch mal auf die Liste der Transition gucken. Die gelb markierten kamen mir komisch vor. Aber ich kann das nicht ganz einschätzen.
[2021-01-25_SLC_2018_3b_all_transitions_002.xlsx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5872358/2021-01-25_SLC_2018_3b_all_transitions_002.xlsx)

Als Lesehilfe: Die Liste enthält die Seiten auf denen die transitions sind (source) und die Seiten zu denen die transitions führen (target). Geordnet ist es nach dem Gesamt-QML, das nicht unbedingt in der richtigen Reihenfolge erstellt ist. Hieraus ergibt sich die distance (mit '-' wenn target im QML vor source vorkommt). index gibt die Position der transition auf der Seite an (0 = erste transition).

**Comment by jocarstensen** [comment]
Die gelb markierten Fälle waren auch im letzten Jahr schon vorhanden. Die dürften auch nach Flussdiagramm kein Problem sein. Wenn @se-lang ebenfalls bestätigt, kann hier zu.

**Comment by andreaschu** [comment]
Ja, ich hatte auch so etwas in Erinnerung, aber nicht mehr genau und wollte euch lieber noch mal fragen.

**Comment by se-lang** [comment]
Auch von mir alles gut, kann keinen Fehler entdecken.
