### ISSUE TITLE
Episoden: emaa47 wording

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#236]
fehlt hier nicht ein "im"?

![grafik](https://user-images.githubusercontent.com/73596957/105961763-3ae2fe80-607f-11eb-8809-ec64674d2cd3.png)

**Comment by heikQ** [comment]
und aber auch mit ohne "bei zu" oder?

**Comment by AliceFoelker** [comment]
Ne das ist der Arbeitgeber.... etwas ungünstig gewählt
![grafik](https://user-images.githubusercontent.com/73596957/105965294-84cde380-6083-11eb-9a15-355ee4e54238.png)

> 
> und aber auch mit ohne "bei zu" oder?

**Comment by se-lang** [comment]
Ich empfinde das als üblichen Sprachgebrauch (gut hab vermutlich auch ich formuliert...) auch wenn ganz korrekt da vllt. ein "im" rein müsste. Wäre m.E. eher was für #141
