### ISSUE TITLE
Add-On strings verrutscht Desktop

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#237]
mobil sieht es gut aus
![grafik](https://user-images.githubusercontent.com/73596957/105993368-9ecced80-60a6-11eb-97a2-4e52c24c4fdc.png)

**Comment by andreaschu** [comment]
ist korrigiert.
![grafik](https://user-images.githubusercontent.com/30111489/106037886-8aedaf80-60d7-11eb-8940-4a203d3a455f.png)
