### ISSUE TITLE
verschobene ao's auf iPad und Tablet

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#238]
bisher auf beg_01 und msg_03 entdeckt. 
![grafik](https://user-images.githubusercontent.com/73596957/106138304-3ea07f00-616c-11eb-8f00-e0f0cf9f82fd.png)

**Comment by andreaschu** [comment]
sollte gefixt sein. Die Seite (produktiv) aktualisieren mit strg+shift+r.

**Comment by AliceFoelker** [comment]
@andreaschu bei mir ist das Problem noch nicht behoben (auch nach aktualisieren nicht)

**Comment by andreaschu** [comment]
- [ ] [beg_01](https://presentation.dzhw.eu/SLC_2018_3b/beg_01.html)
- [ ] [stu_01](https://presentation.dzhw.eu/SLC_2018_3b/stu_01.html)
- [ ] [stu_03](https://presentation.dzhw.eu/SLC_2018_3b/stu_03.html)
- [ ] [stu_02](https://presentation.dzhw.eu/SLC_2018_3b/stu_02.html)
- [ ] [stu_04](https://presentation.dzhw.eu/SLC_2018_3b/stu_04.html)
- [ ] [stu_05](https://presentation.dzhw.eu/SLC_2018_3b/stu_05.html)
- [ ] [stu_06](https://presentation.dzhw.eu/SLC_2018_3b/stu_06.html)
- [ ] [stu_07](https://presentation.dzhw.eu/SLC_2018_3b/stu_07.html)
- [ ] [msg_03](https://presentation.dzhw.eu/SLC_2018_3b/msg_03.html)

**Comment by andreaschu** [comment]
Die Seiten können getestet werden. Ggf. einmal Strg+Shift+r drücken, da nur das CSS angepasst wurde.
