### ISSUE TITLE
überlappende aos auf iPad

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#239]
bitte sagt mir, dass das ein Fehler der Simulation ist, die Überlappungen waren bei einem Samsung Tablet, auf den Screenshots und bei vorherigen Tests nicht zu sehen....quer ist alles gut aber hochkant...

beg_04; cor_01; stu_08,09;stu_12, stu_16;stu_18; stu_19; stu_20... weiter traue ich mich gar nicht zu schauen.

![grafik](https://user-images.githubusercontent.com/73596957/106139272-84117c00-616d-11eb-83d9-b87b9df8ed19.png)
![grafik](https://user-images.githubusercontent.com/73596957/106139344-98557900-616d-11eb-99db-46ab953bfa1d.png)

**Comment by andreaschu** [comment]
- [ ] [beg_04](https://presentation.dzhw.eu/SLC_2018_3b/beg_04.html) 
- [ ] [cor_01](https://presentation.dzhw.eu/SLC_2018_3b/cor_01.html)
- [ ] [stu_08](https://presentation.dzhw.eu/SLC_2018_3b/stu_08.html)
- [ ] [stu_09](https://presentation.dzhw.eu/SLC_2018_3b/stu_09.html)
- [ ] [stu_12](https://presentation.dzhw.eu/SLC_2018_3b/stu_12.html)
- [ ] [stu_16](https://presentation.dzhw.eu/SLC_2018_3b/stu_16.html)
- [ ] [stu_18](https://presentation.dzhw.eu/SLC_2018_3b/stu_18.html)
- [ ] [stu_19](https://presentation.dzhw.eu/SLC_2018_3b/stu_19.html)
- [ ] [stu_20](https://presentation.dzhw.eu/SLC_2018_3b/stu_20.html)

**Comment by andreaschu** [comment]
Die Seiten können getestet werden. Ggf. einmal Strg+Shift+r drücken, da nur das CSS angepasst wurde.

**Comment by AliceFoelker** [comment]
@andreaschu hier sind die aos jetzt hockant, können wir da stattdessen Umbrüche reinmachen?
![grafik](https://user-images.githubusercontent.com/73596957/106259416-7caaab00-621f-11eb-8f5b-d5f40bb7bda0.png)

**Comment by andreaschu** [comment]
@AliceFoelker nein. Die drehen sich, wenn die Befragten den Bildschirm kippen.

**Comment by jocarstensen** [comment]
@andreaschu Ich bin mir nicht sicher, ob hier ein Missverständnis vorliegt. Wir haben gestern darum gebeten, die Zeilenumbrüche so einzustellen, dass sich die AOs nicht überlappen. Jetzt sind sie auf diesen Seiten um 90 Grad gedreht, was nicht abgesprochen war und auch sehr unvorteilhaft ist.

**Comment by andreaschu** [comment]
@jocarstensen in dem Fall müssen wir jede Matrix einzeln angehen. Dann sehe ich für Montag auch schwarz.

**Comment by jocarstensen** [comment]
@andreaschu So hatte ich es bei unserem Gespräch gestern aber verstanden. Es geht um 11 Fragen. Bei denen einfach die AOs zu kippen wirkt extrem unprofessionell und erschwert die Lesbarkeit stark. Ist also m.E. keine Option.

Wie wurde das denn letztes Jahr gemacht?

**Comment by andreaschu** [comment]
> Wie wurde das denn letztes Jahr gemacht?

Da wurde das Layout individuell für jede Matrix angepasst.

**Comment by andreaschu** [comment]
Die Seiten wurden angepasst und können getestet werden:
- [ ] [beg_04](https://https://presentation.dzhw.eu/SLC_2018_3b/beg_04.html)
- [ ] [cor_01](https://https://presentation.dzhw.eu/SLC_2018_3b/cor_01.html)
- [ ] [cor_03](https://https://presentation.dzhw.eu/SLC_2018_3b/cor_03.html)
- [ ] [aus_04](https://https://presentation.dzhw.eu/SLC_2018_3b/aus_04.html)
- [ ] [aus_06](https://https://presentation.dzhw.eu/SLC_2018_3b/aus_06.html)
- [ ] [stu_09](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_09.html)
- [ ] [stu_09](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_09.html)
- [ ] [stu_10](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_10.html)
- [ ] [stu_12](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_12.html)
- [ ] [stu_15](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_15.html)
- [ ] [stu_16](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_16.html)
- [ ] [stu_18](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_18.html)
- [ ] [stu_19](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_19.html)
- [ ] [stu_20](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_20.html)
- [ ] [stu_21](https://https://presentation.dzhw.eu/SLC_2018_3b/stu_21.html)
- [ ] [mas_01](https://https://presentation.dzhw.eu/SLC_2018_3b/mas_01.html)
- [ ] [mas_02](https://https://presentation.dzhw.eu/SLC_2018_3b/mas_02.html)
- [ ] [mas_03](https://https://presentation.dzhw.eu/SLC_2018_3b/mas_03.html)
- [ ] [gsh_02](https://https://presentation.dzhw.eu/SLC_2018_3b/gsh_02.html)
- [ ] [msg_01](https://https://presentation.dzhw.eu/SLC_2018_3b/msg_01.html)
- [ ] [msg_05](https://https://presentation.dzhw.eu/SLC_2018_3b/msg_05.html)
- [ ] [msg_06](https://https://presentation.dzhw.eu/SLC_2018_3b/msg_06.html)

**Comment by AliceFoelker** [comment]
aos überlappen nicht mehr
