### ISSUE TITLE
Einstieg: Mobile Version: beg_01 Skalenbeschriftung abgeschnitten

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#24]
Bei der mobilen Version ist **sehr zufrieden (1)** abgeschnitten. Auch wenn der Bildschirn gekippt/quer ist.

**Comment by andreaschu** [comment]
@AliceFoelker hier würde ab einer Bildschirmbreite von kleiner 778 die vertikale Version angezeigt werden. Wäre das so okay? Oder soll hier für alle die Skala vertikal werden?

**Comment by christian-fr** [comment]
Ist umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
