### ISSUE TITLE
SozDem: msg_16 (iPad)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#246]
auch die Kästchen komisch aus
![grafik](https://user-images.githubusercontent.com/73596957/106307495-ba2f2880-625f-11eb-8ede-de0684156ff3.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
aos nun über den Kästchen
