### ISSUE TITLE
Corona: cor_01 2. ao (Umbruch Zahl nach unten)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#249]
nice to have: könnte man hier bei der 2. ao. die (2) in die gleiche Zeile wir die restlichen schieben?
![grafik](https://user-images.githubusercontent.com/73596957/106431346-6abe4780-646d-11eb-82dc-b3d31c699e47.png)

**Comment by andreaschu** [comment]
@AliceFoelker nein, die Umbrüche passieren automatisch nach vorhandenem Platz.
