### ISSUE TITLE
Zwischenseiten 

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#25]
**Zwischenseiten:**
Zwischenseite_1: wave 1-5 (beg_00)
Zwischenseite_2: wave 1-5 (cor_00)
Zwischenseite_3: **wave 1-3 (Episodenzwischenseite); wave 4,5 (reife_00)**
Zwischenseite_4: wave 1-5 (aus_00)
Zwischenseite_5: wave 1-5 (stu_00)
Zwischenseite_6: wave 1-5 (gsh_00)
Zwischenseite_7: wave 1-5 (msg_00)
Zwischenseite_8: wave 1-5 direkt nach msg_20 **(vermutlich dafür neue Seite msg_21 erstellen)**

**neues Layout der Zwischenseiten**
[fertige Zwischenseiten (2).zip](https://github.com/dzhw/studienberechtigte_2018.3b/files/5764763/fertige.Zwischenseiten.2.zip)
@christian-fr @andreaschu das Layout der Zwischenseiten hat sich geändert.

**Comment by christian-fr** [comment]
Ist umgesetzt, nach dem nächsten Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@andreaschu @christian-fr ist fixed, das Issue würde ich aber dennoch auflassen zwecks Übersicht.
