### ISSUE TITLE
Episoden: em[a][a]12 mehr Platz zwischen den aos

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#251]
![grafik](https://user-images.githubusercontent.com/73596957/106438415-c3461280-6476-11eb-9e34-330d737e7264.png)

**Comment by jocarstensen** [comment]
@AliceFoelker @andreaschu Das betrifft dann vermutlich alle em**12. Also zusätzlich noch

- [ ] emab12
- [ ] emac12
- [ ] emad12
- [ ] emae12
- [ ] emaf12
- [ ] emba12
- [ ] embb12
- [ ] embc12
- [ ] embd12
- [ ] embe12
- [ ] emca12
- [ ] emcb12
- [ ] emcc12
- [ ] emcd12
- [ ] emda12
- [ ] emdb12
- [ ] emdc12
- [ ] emea12
- [ ] emeb12
- [ ] emfa12
- [ ] em0012
