### ISSUE TITLE
Episoden: se[a][a]06 mobil ao sehr dicht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#253]
![grafik](https://user-images.githubusercontent.com/73596957/106449181-fe9b0e00-6483-11eb-98d8-cae8b8a55c23.png)

**Comment by andreaschu** [comment]
@vdick das müsste folgende Seiten betreffen:

- [ ] seaa06
- [ ] seab06
- [ ] seac06
- [ ] sead06
- [ ] seae06
- [ ] seba06
- [ ] sebb06
- [ ] sebc06
- [ ] sebd06
- [ ] seca06
- [ ] secb06
- [ ] secc06
- [ ] seda06
- [ ] sedb06
- [ ] seea06
- [ ] sezz06

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#255 ) verfügbar
