### ISSUE TITLE
Erstellung Produktivbefragung

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#256]
@andreaschu sobald das letzte Issue (#251) behoben ist, kann die Produktivbefragung erneut aufgesetzt werden.

**Comment by heikQ** [comment]
@andreaschu ist es absehbar, wann wir mit einer Produktivbefragung einschließlich des issue #251 rechnen können, damit wir den Versand der Einladungsschreiben timen können?

**Comment by heikQ** [comment]
Da das letzte Issue gefixed wurde und ok ist, vielen Dank, bitte produktiv Befragung aufsetzen. Nochmal die Nachfrage, wann ist etwa damit zu rechnen?

**Comment by andreaschu** [comment]
Die produktive Version ist aktuell.

**Comment by AliceFoelker** [comment]
@andreaschu wir sind die Produktivbefragung durchgegangen und geben hiermit unser GO für die Befragung. @christian-fr Die Einladungs-Mails der verschiedenen Waves können dann theoretisch heute auch raus. Muss sonst noch etwas in die Wege geleitet werden?

**Comment by andreaschu** [comment]
@AliceFoelker für heute ist es bei uns zu spät. Wir machen das morgen früh.
