### ISSUE TITLE
Terminplanung E-Mail-Versand

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#257]
@heikQ kannst Du den Zeitplan im [Wiki](https://github.com/dzhw/studienberechtigte_2018.3b/wiki#zeitplan) noch mal aktualisieren, damit wir eine aktuelle Übersicht der geplanten Termine haben?

**Comment by andreaschu** [comment]
Ich habe mir gestern den Bounce-Mail-Report genauer angesehen und diese [Auswertung](https://github.com/dzhw/studienberechtigte_2018.3b/files/5932238/Auswertung_BounceMails.pdf) teilweise bereits direkt weitergegeben. Ich lade es hier noch mal hoch, damit es an zentralerer Stelle verfügbar ist.

**Comment by heikQ** [comment]
@andreaschu Termine hab ich im Wiki angepasst, im Prinzip alles um eine Woche verschoben
