### ISSUE TITLE
Token-Lieferung 10.02.2021

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#258]
@andreaschu Heiko hat den Zeitplan im Wiki aktualisiert. Als nächstes steht die Lieferung der Token für die Erinnerungsmails auf dem Plan. Wann können wir am Mittwoch damit rechnen?

**Comment by andreaschu** [comment]
ich nehme an, dass die auf den gwinter transferiert werden sollen, richtig? dann erst nachmittags, da thomas immer später kommt. 
ist geklärt, welche token exportiert werden sollen? (nur die, die beendet haben oder die, die nicht beendet haben? oder was anderes?)

**Comment by AliceFoelker** [comment]
@andreaschu Die Datei sollte Token, wave und lastpage enthalten.

**Comment by AliceFoelker** [comment]
@andreaschu im vorherigen Kommentar findest du eine Korrektur hinsichtlich der benötigten Token. Außerdem eine Bitte die Liste mit den jeweiligen Token (unabhängig von Thomas) sobald sie fertig ist an Verena zu senden. Wann wäre das morgen (10.02) möglich?
