### ISSUE TITLE
Fortschrittsbalken

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#26]
**Fortschrittsbalken:**
Fortschrittsbalken_1: Indexseiten
Fortschrittsbalken_2: wave 1-5 Modul01 (Einstieg) (beg_)
Fortschrittsbalken_3: wave 1-5 Modul02 (Corona) (cor_)
Fortschrittsbalken_4: **wave 1-3 Episodenmodul; wave 4,5 Modul03 (Schulabschluss) (reife_) + Episodenmodul**
Fortschrittsbalken_5: wave 1-5 Modul04 (Ausbildung) (aus_)
Fortschrittsbalken_6: wave 1-5 Modul05 (Studium) (stu_)
Fortschrittsbalken_7: wave 1-5 Modul06 (Gesundheit) (gsh_)
Fortschrittsbalken_8: wave 1-5 Modul07 (SozDem) (msg_)
[fertige Fortschrittsbalken.zip](https://github.com/dzhw/studienberechtigte_2018.3b/files/5637853/fertige.Fortschrittsbalken.zip)

**Comment by christian-fr** [comment]
Ist umgesetzt. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
Modul04: Ausbildung fehlt noch, der Rest ist eingefügt.

**Comment by christian-fr** [comment]
Die Fortschrittsbalken sind überarbeitet. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed - für die Übersicht lasse ich das Issue auf

**Comment by AliceFoelker** [comment]
Der Fortschrittsbalken im Episodenmodul fehlt noch.
