### ISSUE TITLE
Nachversand 1. Erinnerung

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#262]
@andreaschu bitte ein Nachversand der Bounce-Mails der 1. Erinnerung vornehmen.

**Comment by andreaschu** [comment]
@AliceFoelker wenn sich die Adressen nicht verändern, bringt ein Nachversand nichts. Das steht in keinem sinnvollen Verhältnis zum Aufwand, insbesondere, da es sich um vier getrennte Schreiben handelt. Zur Info, ich habe gestern einen Nachversand der Bounces gemacht (für den Pretest). Davon kamen 99% direkt wieder zurück.
Es war zudem auch nicht vorgesehen. Zumindest ist es nicht im Zeitplan enthalten.

**Comment by heikQ** [comment]
@andreaschu @AliceFoelker mittlerweile auch zu spät, da Montag die 2. Erinnerung kommt. Insofern lassen wir den Nachversand der bounce einladungen der 1. Erinnerung jetzt. Ich mach hier mal zu.
