### ISSUE TITLE
Lieferung Rücklaufreport nach Wave

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#269]
@andreaschu um einen Überblick der wave-Rückläufe zu erhalten bräuchten wir, wie Mi angefragt, einen Rücklaufreport nach wave. Ist das möglich? LG

**Comment by andreaschu** [comment]
Das geht nur über eine DB-Abfrage. Hier das Ergebnis.

wave | finished | participated
-- | -- | --
1 | 2126 | 235
2 | 0 | 1
3 | 3346 | 472
4 | 1517 | 1124
5 | 75 | 46
