### ISSUE TITLE
Einstieg: beg_05 mobile Ansicht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#27]
mobile Ansicht Galaxy S9: aos sehr eng fast schon überlappend (hochkant)
![grafik](https://user-images.githubusercontent.com/73596957/101364083-77298800-38a2-11eb-9c46-99be90646dbb.png)

**Comment by vdick** [comment]
nach nächstem Rollout verfügbar

**Comment by AliceFoelker** [comment]
Das sieht leider immer noch so aus
![grafik](https://user-images.githubusercontent.com/73596957/102327802-8b4a4500-3f86-11eb-85c8-cbd34d2f4bc5.png)

**Comment by vdick** [comment]
@AliceFoelker hast du den Cache im Browser gelöschtt?

**Comment by AliceFoelker** [comment]
@vdick ja habe ich noch mal, an der Ansicht hat sich ein wenig was getan, aber den Abstand zwischen den aos würde ich trotzdem noch größer wählen. Ist das möglich?

![grafik](https://user-images.githubusercontent.com/73596957/102332573-8f796100-3f8c-11eb-9ab0-12ab8b1e75b4.png)

**Comment by vdick** [comment]
@AliceFoelker alles klar und es ist möglich ;) Es ist immer einwenig schwierig einzuschätzen, wie groß der Abstand werden soll..

**Comment by AliceFoelker** [comment]
@vdick sehr gut! pls make it happen :-)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
fixed
