### ISSUE TITLE
Studium: stu_11 Skalenausrichtung geändert

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#28]
Mobile Ansicht Galaxy S9: hier sind die Beschriftungen der aos überlappend (quer sowie hochkant)
![grafik](https://user-images.githubusercontent.com/73596957/101364808-485fe180-38a3-11eb-89d9-3728749adf7c.png)

**Comment by andreaschu** [comment]
@AliceFoelker für alle vertikal oder nur für kleinere Bildschirme?

**Comment by AliceFoelker** [comment]
für alle 11er Skalen vertikale ao. Bin dabei das jetzt nach und nach überall in den Codes zu ändern. 
vermute dass es letztes mal in den codes nicht angepasst wurde, da ich mit den alten gearbeitet habe und dort alles horizontal angelegt war. @andreaschu

**Comment by christian-fr** [comment]
Ist geändert. So weit ich das sehen kann, sind alle anderen 11er Skalen (**aus_05, msg_02, msg_03**) nun auch vertikal.

**Comment by AliceFoelker** [comment]
fixed
