### ISSUE TITLE
h_enterdatum auf beg_00 bleibt bei wave5 leer

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#29]
dort müsste theoretisch Januar 2018 stehen, stattdessen bleibt es leer
auch nach weiter und zurück, würde für die Einblendungen im Episodenmodul Probleme machen

![grafik](https://user-images.githubusercontent.com/73596957/101368574-9840a780-38a7-11eb-9462-261673b12e60.png)

**Comment by jocarstensen** [comment]
Das ist ein Preload, der für die Tester definiert worden sein müsste. In den Episoden wären da "nur" Einblendungen von betroffen. Warum der fehlt, kann ich nicht sagen.

**Comment by AliceFoelker** [comment]
Ja, genau für die bereits programmierten Module macht es keinen Unterschied, um so mehr allerdings für die Einblendungen der Episoden. @jocarstensen hatte dich nur assigned, damit du es siehst - falls die Episoden vor einem Fix hochgeladen werden.

**Comment by andreaschu** [comment]
Der Fehler ist behoben. Jetzt klappt es aus meiner Sicht.
Da das zur Einblendung in den Episodenmodulen verwendet wird, sollte auch die Frage 3 aus Issue 10 beantwortet sein, oder?
https://github.com/dzhw/studienberechtigte_2018.3b/issues/10#issuecomment-739969190

**Comment by jocarstensen** [comment]
Nein, die Frage 3 aus Issue 10 betrifft die Funktionalität der Javascript-Auswahl in Abhängigkeitet des Startdatums der Wave. Kannst Du dazu Viktor fragen?

**Comment by AliceFoelker** [comment]
das Problem mit dem h_enterdatum der Preloads ist gefixt. @jocarstensen @andreaschu kann ich dieses Issue schließen oder wg. Frage 3 aus Issue 10 noch geöffnet lassen?

**Comment by jocarstensen** [comment]
Meinetwegen kann es zu. Ist ja in Issue 10 vorhanden...
