### ISSUE TITLE
Benötigte Preload-Variablen

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#3]
Für die Steuerung der Befragung werden folgende Preload-Variablen benötigt:

**preloadcohort**
Beschreibung: Wird nur zur Steuerung im episodenmodul benötigt
Werte: Variable fix auf den Wert 2 für alle Teilnehmer*innen setzen

**wave**
Beschreibung: Zuordnung der Subsample bzw. Kohorten, Werte werden später über Token bzw. unsere Ident.-Nummern der Teilnehmer*innen zugewiesen. Bitte für die Testung Tokens mit den Werten 1-5 auf der Variablen anlegen.
Werte:
1= Teilnehmer*in aus 2018.3a mit Rücklauf), 
2=Teilnehmer*in aus 2018.3a ohne Rücklauf), 
3= nur Teilnehmer*in aus 2018.2 aber nicht Proband*in aus 2018.3a
4=(nur 2018.1 teilgenommen bzw. 2018.2 gleich zu Beginn abgebrochen) und (nicht aus Hessen/Berlin)
5=(nur 2018.1 teilgenommen bzw. 2018.2 gleich zu Beginn abgebrochen) und (aus Hessen/Berlin)

**incentive**
Beschreibung: In den subsamplegruppen 4 und 5 (wave=4 or 5)  variiert die Höhe der Incentives. Wird benötigen daher eine preload-Variable, mit der wir auf den entsprechenden Incentive-Topf auf der Landingpage leiten. Für die Testung bitte Häfte der Testtoken mit preload-Variable incentive=1 und die andere Hälfte mit incentive=2 anlegen.
Werte:
1=kleiner Incentive Topf
2=großer Incentive Topf

**h_enterdatum**
Beschreibung: String-Variable die den Bezugszeitraum für das Episodenmodul bestimmt
Strings:
"Januar 2020" if wave=1
"Januar 2018" if wave=2 or 3 or 4 or 5

**h_exitdatum**
Beschreibung: Das Ende des Bezugszeitraums in der Form "Jahr*100+Monat". Nicht als String, sondern numerisch
Werte:
202012 = fix für alle Teilnehmer*innen

**h_exitlabel**
Besachreibung: Das Ende des Bezugszeitraums als _string_ (analog zu exitdatum).
Strings:
"Dezember 2020" fix für alle Teilnehmer*innen

**Comment by andreaschu** [comment]
die Preload-Variablen _cohort_ und _wave_ sind angelegt. Die Variablen h_* sind technisch keine Preloads, sondern Hilfsvariablen und werden in der Befagung generiert. Sie sind aber auch angelegt und werden auf einzelnen Zwischenseiten angezeigt.

Bei incentive habe ich noch Fragen:
- wave=1 - wave= 3 bekommen kein Incentive? Irgendwas sollte in der Variable stehen. Ich habe sie in der Tabelle als 0 definiert (siehe unten)
- Habe ich das richtig verstanden? Es soll die Hälfte von wave==4 den Wert 1 und die andere Hälfte den Wert 2 bekommen. Dasselbe bei wave==5, oder? (siehe gelbe Markierung)

Die  Ident.-Nummern kommt ebenfalls als Preload _panel_ in die Befragung, oder?

![grafik](https://user-images.githubusercontent.com/30111489/100626963-b6962880-3326-11eb-8789-2d1b5b599dcf.png)

**Comment by heikQ** [comment]
@andreaschu jup, danke. Genau so. Zumindest jetzt fürs Testen, nachher werden wir dann Teilnehmer aus 4 u. 5 zufallsbasiert auf die incentive-Töpfe 1 und 2 zuweisen. wave 1-3 haben immer den gleichen topf, da ist Wert 0 also immer okay und konstant.

**Comment by jocarstensen** [comment]
Bitte h_enterdatum für wave!=1 in "Juli 2018" ändern statt "Januar 2018"

**Comment by christian-fr** [comment]
Folgende Preloads sind nun geladen:


token | panel | cohort | wave | incentive | panel
-- | -- | -- | -- | -- | --
tester1-tester40 | 1...40 | 2 | 1 | 0 | 1
tester41-tester80 | 41...80 | 2 | 2 | 0 | 1
tester81-tester120 | 81...120 | 2 | 3 | 0 | 1
tester121-tester140 | 121...140 | 2 | 4 | 1 | 1
tester141-tester160 | 141...160 | 2 | 4 | 2 | 1
tester161-tester180 | 161...180 | 2 | 5 | 1 | 1
tester181-tester200 | 181...200 | 2 | 5 | 2 | 1

[2021-01-18_Preloads_test.xlsx](https://github.com/dzhw/studienberechtigte_2018.3b/files/5831089/2021-01-18_Preloads_test.xlsx)

**Comment by christian-fr** [comment]
Auf der page **index** wurden die Eingabefelder für _incentive_ und _wave_ entfernt.
