### ISSUE TITLE
SozDem: msg_02/03/20 mobile Ansicht fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#30]
S9 Galaxy (auch quer fehlerhaft)
Beispiel:
![grafik](https://user-images.githubusercontent.com/73596957/101496305-e6b67a80-3969-11eb-974b-27f63ba213ae.png)

**Comment by andreaschu** [comment]
siehe #34

**Comment by andreaschu** [comment]
@AliceFoelker immer vertikal oder nur für kleine Bildschirme?
@christian-fr bitte mit dem Workaround noch auf eine Antwort warten.

**Comment by AliceFoelker** [comment]
@andreaschu von horizontal zu vertikal geändert

**Comment by christian-fr** [comment]
Ist umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@christian-fr @andreaschu war das bei dem letzten Rollout schon dabei? Da sehe ich noch keine Veränderung.

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
#58

**Comment by AliceFoelker** [comment]
fixed
