### ISSUE TITLE
SozDem: msg_12 mobile Ansicht fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#31]
Galaxy S9: Aos nicht ausreichend voneinander getrennt
![grafik](https://user-images.githubusercontent.com/73596957/101496692-5a588780-396a-11eb-80fa-b638d551adce.png)

**Comment by vdick** [comment]
Nach nächstem Rollout verfügbar

**Comment by andreaschu** [comment]
@vdick geht da noch was mit dem Abstand?

![Screenshot_2020-12-16 SLC_IntEr_18-3](https://user-images.githubusercontent.com/30111489/102385790-8f01ba00-3fce-11eb-9d19-56e1c9e5ce41.png)

**Comment by vdick** [comment]
@andreaschu klaro, fixed! Ab nächsten Rollout( #71 )  verfügbar

**Comment by AliceFoelker** [comment]
fixed
