### ISSUE TITLE
SozDem: msg_13 mobile Ansicht + Desktop fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#32]
Galaxy S9: string von ao1 verrutscht:
![grafik](https://user-images.githubusercontent.com/73596957/101496872-955abb00-396a-11eb-8bdd-f17cf05f66cd.png)

**Comment by vdick** [comment]
Nach nächstem Rollout verfügbar

**Comment by andreaschu** [comment]
@vdick das sieht aus meiner Sicht nicht anders aus. Kannst du noch mal schauen?
![Screenshot_2020-12-15 SLC_IntEr_18-3_msg_13](https://user-images.githubusercontent.com/30111489/102228114-9ea7d280-3eea-11eb-95ed-3021a301716b.png)

**Comment by vdick** [comment]
@andreaschu ähm.. mit welchem Browser hast du es getestet?

**Comment by andreaschu** [comment]
firefox

> 
> 
> @andreaschu ähm.. mit welchem Browser hast du es getestet?

**Comment by vdick** [comment]
@andreaschu alles klar, ich checke es noch einmal

**Comment by vdick** [comment]
fixed, ab nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
@vdick @andreaschu da hat sich was getan aber in der mobilen Version (S9) müsste trotzdem noch ein wenig nachjustiert werden
![grafik](https://user-images.githubusercontent.com/73596957/102383465-dd618980-3fcb-11eb-8994-edad07ee3857.png)

**Comment by dzhwmeisner** [comment]
Im nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
die mobile Version ist noch fehlerhaft
![grafik](https://user-images.githubusercontent.com/73596957/103515059-41aa9700-4e6e-11eb-895b-9ea9d12e69e8.png)
