### ISSUE TITLE
Studium: stu_01 bis stu_06 mobile Ansicht fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#33]
Galaxy S9: hier wird im Hochformat eine falsche Skallierung angezeigt:
Beispiel:
![grafik](https://user-images.githubusercontent.com/73596957/101497159-f5516180-396a-11eb-9146-822e735722aa.png)

**Comment by andreaschu** [comment]
siehe #34

**Comment by andreaschu** [comment]
@AliceFoelker immer vertikal oder nur für kleine Bildschirme?
@christian-fr bitte mit dem Workaround noch auf eine Antwort warten.

**Comment by christian-fr** [comment]
Ist auf den pages **stu_01** bis **stu_06** umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
