### ISSUE TITLE
gesundheit: gsh_01 mobile Ansicht fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#34]
Galaxy S9: Skallierung im Hochformat falsch dargestellt
![grafik](https://user-images.githubusercontent.com/73596957/101497515-5b3de900-396b-11eb-8e16-1524bcf1fe84.png)

**Comment by andreaschu** [comment]
@christian-fr könntest Du hier den Workaround mit der vertikalen Darstellung programmieren?

**Comment by andreaschu** [comment]
@AliceFoelker immer vertikal oder nur für kleine Bildschirme?
@christian-fr bitte mit dem Workaround noch auf eine Antwort warten.

**Comment by christian-fr** [comment]
Ist umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
