### ISSUE TITLE
Modul 1 Einstieg: Fehler und Überarbeitungsbedarf (I)

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#35]
(gestestet mit Firefox)

- [ ] Seite beg_04: Darstellung der Antworten ist völlig zerschossen 
![beg_04](https://user-images.githubusercontent.com/52539440/101655862-61eb5f80-3a42-11eb-84ab-e31c1b5e43a3.PNG)

- [ ] Seite beg_05: Wenn ein Item angekreuzt wurde, lässt sich nur noch umkreuzen, die Antwort allerdings nicht wieder ganz rausnehmen, bitte so umsetzen, dass Probanden auch die Möglichkeit haben, ihre Antwort ganz rauszunehmen und damit dann auch „keine Angabe“/Antwortverweigerung machen können, auch wenn sie zunächst was angekreuzt hatten. Gilt im Prinzip für alle single-choice Fragen.

**Comment by andreaschu** [comment]
@christian-fr oder @vdick kann sich beg_04 mal einer ansehen?

**Comment by andreaschu** [comment]
>  Seite beg_05: Wenn ein Item angekreuzt wurde, lässt sich nur noch umkreuzen, die Antwort allerdings nicht wieder ganz rausnehmen, bitte so umsetzen, dass Probanden auch die Möglichkeit haben, ihre Antwort ganz rauszunehmen und damit dann auch „keine Angabe“/Antwortverweigerung machen können, auch wenn sie zunächst was angekreuzt hatten. Gilt im Prinzip für alle single-choice Fragen.

Ich habe es gerade in #38 kommentiert. Das geht nicht und war auch noch nie so. Deswegen gibt es hier eine Ausweichkategorie.

**Comment by andreaschu** [comment]
ich schließe das Issue mal, weil es in #38 und in #23 behandelt wird.
