### ISSUE TITLE
Modul 2 Corona: Fehler und Überarbeitungsbedarf (I)

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#36]
(getestet mit Firefox)

- [x] Seite cor_01: Reihenfolge der Skala-Beschriftungen geändert, siehe Aktualisierung im entsprechenden Code

> Seiten cor_03, cor_04 und cor_05: Abstände zwischen den Antwortoptionen kleiner machen und nicht über ganze Zeilenbreite ziehen. Zeilenhöhe für die Antworten bitte verringern, so sieht es unnötig viel aus und es muss viel gescrollt werden. Text der antwortoption "sonstiges, und zwar" bitte ohne Umbruch in eine Zeile
> ![cor_03t](https://user-images.githubusercontent.com/52539440/101659865-cc9e9a00-3a46-11eb-9eb2-90b9ba068b09.PNG)

edit: wurde zu Issue #37

> Seite cor_06: Wenn ein Item angekreuzt wurde, lässt sich nur noch umkreuzen, die Antwort allerdings nicht wieder ganz rausnehmen, bitte so umsetzen, dass Probanden auch die Möglichkeit haben ihre Antwort ganz rauszunehmen und damit dann auch „keine Angabe“/Antwortverweigerung machen können, auch wenn sie zunächst was angekreuzt hatten.

edit: wurde zu Issue #38

**Comment by andreaschu** [comment]
@heikQ bitte mache nur ein Issue pro Problem oder Commit, damit wir die Issues abzuarbeiten sind.

**Comment by AliceFoelker** [comment]
@heikQ @andreaschu kann dieses Issue eigentlich geschlossen werden? Sind wenn ich das oben richtig interpretiere sind die Probleme in anderen Issues geöffnet worden?
