### ISSUE TITLE
Modul 2 Corona: Abstände zwischen den Antwortoptionen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#37]
Seiten cor_03, cor_04 und cor_05: 
- [x] Abstände zwischen den Antwortoptionen kleiner machen und nicht über ganze Zeilenbreite ziehen. 
- [x] Zeilenhöhe für die Antworten bitte verringern, so sieht es unnötig viel aus und es muss viel gescrollt werden. 
- [ ] Text der antwortoption "sonstiges, und zwar" bitte ohne Umbruch in eine Zeile

![cor_03t](https://user-images.githubusercontent.com/52539440/101659865-cc9e9a00-3a46-11eb-9eb2-90b9ba068b09.PNG)

**Comment by vdick** [comment]
Vom letzten Punkt möchte ich dringend abraten. Sollte das Label in einer Zeile dargestellt werden, würde das Eingabefeld recht klein ausfallen

**Comment by vdick** [comment]
Nach nächstem Rollout verfügbar

**Comment by heikQ** [comment]
fixed
