### ISSUE TITLE
cor_06: deselektierbare RadioButtons

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#38]
aus Issue #36 extrahiert:
Seite cor_06: Wenn ein Item angekreuzt wurde, lässt sich nur noch umkreuzen, die Antwort allerdings nicht wieder ganz rausnehmen, bitte so umsetzen, dass Probanden auch die Möglichkeit haben ihre Antwort ganz rauszunehmen und damit dann auch „keine Angabe“/Antwortverweigerung machen können, auch wenn sie zunächst was angekreuzt hatten.

Antwort: Es sollte bekannt sein, dass wir hier nur eine Ausweichkategorie hinzufügen können. Wenn wir das machen sollen, bitte einen Vorschlag in die Programmiervorlage hinzufügen.

**Comment by heikQ** [comment]
nein, bitte keine ausweichkategorie, das geht wegen der Zeitreihe nicht, würde die antwortoptionen verändern im Zeitvergleich. Dann besser so lassen. ich mach zu.
