### ISSUE TITLE
Studium: stu_11 Skalierung unterschiedlich

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#39]
Firefox: Anordnung der Skalenpunkte nicht einheitlich & "(-5) unterdurchschnittlich" abgeschnitten
![grafik](https://user-images.githubusercontent.com/73596957/101749084-9f48ff00-3acd-11eb-9c57-44d52e2b6207.png)

**Comment by andreaschu** [comment]
@AliceFoelker immer vertikal oder nur für kleine Bildschirme?

**Comment by AliceFoelker** [comment]
![grafik](https://user-images.githubusercontent.com/73596957/101783833-0630dd00-3afb-11eb-82ce-270268a8ca50.png)
 @andreaschu 
bereits in #28 aufgeführt bzw. erläutert also geclosed
