### ISSUE TITLE
Corona: cor_02 Range

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#40]
Wenn ao6 (in keinem dieser Bereiche) angekreuzt wird, sollte keine andere ao ankreuzbar sein (so wissen wir letztendlich nicht was korrekt wäre) oder @heikQ ?
![grafik](https://user-images.githubusercontent.com/73596957/101749814-75440c80-3ace-11eb-9af8-6fadfed18f78.png)

@andreaschu muss/kann ich das im Code ändern?

**Comment by andreaschu** [comment]
die Kategorie ist auf 'exclusive' gesetzt

**Comment by AliceFoelker** [comment]
wie kann ich es dann lösen? av: entweder ao1-ao5 ODER ao6. Beides soll nicht möglich sein?

**Comment by AliceFoelker** [comment]
fixed
