### ISSUE TITLE
SozDem: msg_19 strings verrutscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#41]
Firefox: hier sind die offenen Angaben und das Komma verrutscht 
@heikQ wollen wir die 2 offenen Angaben bei >nicht Deutsch sondern< lieber durch ein "und" oder "oder" trennen?
![grafik](https://user-images.githubusercontent.com/73596957/101750735-b5f05580-3acf-11eb-8512-96a637df2445.png)

**Comment by heikQ** [comment]
Soll bitte wieder so aussehen und getrennt durch den Slash, ging 2018.2 ja auch:
![image](https://user-images.githubusercontent.com/52539440/101780433-d7b10300-3af6-11eb-873a-a775c1537dc0.png)

**Comment by dzhwmeisner** [comment]
Im nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
hier ist noch das Komma statt dem Slash drin + die digitale Version ist fehlerhaft
![grafik](https://user-images.githubusercontent.com/73596957/103515636-618e8a80-4e6f-11eb-9365-d9f66db8fbcb.png)

**Comment by AliceFoelker** [comment]
hier hat etwas noch nicht geklappt:

![grafik](https://user-images.githubusercontent.com/73596957/103534664-9ad6f280-4e8f-11eb-85d0-b4cae1118d20.png)

![grafik](https://user-images.githubusercontent.com/73596957/103534626-872b8c00-4e8f-11eb-9a06-ea34d2e09b72.png)

**Comment by AliceFoelker** [comment]
@christian-fr jetzt ist der Sklah drin aber die strings sind noch verrutscht

![grafik](https://user-images.githubusercontent.com/73596957/103651268-9f6bdb80-4f61-11eb-90a1-3c4d51be988b.png)

**Comment by vdick** [comment]
Hallo @AliceFoelker womit und in welcher Auflösung ist das aufgetreten ? Kann es gerade nicht reproduzieren..

**Comment by AliceFoelker** [comment]
@vdick firefox und der normalen Bildschirmauflösung bei allem was bei Zoom über 80% liegt (ich weiß ehrlich gesagt nicht genau ob das deine Frage beantwortet und wenn nein, wo ich die passende Antwort finde):

die Mobilversion sieht auch noch so aus:
![grafik](https://user-images.githubusercontent.com/73596957/103654540-4e121b00-4f66-11eb-8e66-77af2ca33ccf.png)

**Comment by vdick** [comment]
@AliceFoelker magst du morgen kurz durchrufen?

**Comment by AliceFoelker** [comment]
@vdick yes! passt dir eine bestimmte Uhrzeit?

**Comment by vdick** [comment]
@AliceFoelker 10 Uhr, sofern es dir passt? Bis dahin dürfte ich mit Rollout etc fertig sein

**Comment by AliceFoelker** [comment]
@heikQ Viktor und ich haben wegen des Problems der unterschiedlichen Höhen der strings von msg_19 geredet. Er sagt, dass die letzte Befragung (dein Screenshot) nicht respronsiv war und der Slash zwischen den strings nicht so ohne Weiteres eingesetzt werden kann, ohne dass dieser offenbar die strings beeinträchtigt. Er schlägt vor, den Slash entweder wegzulassen oder wir nehmen die unterschiedlichen Höhen in Kauf. Wie siehst du das?
> 
> @christian-fr jetzt ist der Sklah drin aber die strings sind noch verrutscht
> 
> ![grafik](https://user-images.githubusercontent.com/73596957/103651268-9f6bdb80-4f61-11eb-90a1-3c4d51be988b.png)

**Comment by heikQ** [comment]
@AliceFoelker @vdick wir nehmen die leicht unterschiedliche Höhe in Kauf. Wichtiger ist, dass man sieht, dass es zwei Felder sind.

**Comment by AliceFoelker** [comment]
dann schließe ich hier
