### ISSUE TITLE
Testlinks funktionieren auf mobil-Gerät (S9) nicht mehr

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#42]
mit dem externen Link komme ich auf die Login-Seite, kann einen Tester angeben aber da ist kein >weiter< Button, um zur Befragung zu gelangen.
![grafik](https://user-images.githubusercontent.com/73596957/101766894-be528b80-3ae3-11eb-97d4-ec62e0a4dd88.png)
@andreaschu

**Comment by christian-fr** [comment]
Konnten wir nicht reproduzieren. Bitte nach nächstem Rollout nochmal testen.

**Comment by AliceFoelker** [comment]
ist gefixed bzw. komme ich mit dem Handy wieder rein, aber "Session ist abgelaufen" steht immernoch da?! @andreaschu @christian-fr ist das "normal"?

**Comment by andreaschu** [comment]
Das ist normal, wenn Du automatisch ausgeloggt wirst. 
Beim Smart Phone kann es sein, dass der Browser geschlossen wird, die Seite aber aktiv bleibt und sich beim erneuten Öffnen des Browsers wieder öffnet. In dem Fall bist Du automatisch ausgeloggt worden.
