### ISSUE TITLE
SozDem: msg_09 mobile V. Einblendungen Präfixe fehlen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#43]
Galaxy S9: auf den Seiten wo Ort,PLZ etc. eingegeben werden soll, werden die "Präfixe" nicht in den offenen Kästchen angegeben. Auch in der Desktop-Version muss man mit der Maus drauf gehen um sie zu sehen. In der mobilen version funktioniert das nicht

![grafik](https://user-images.githubusercontent.com/73596957/101775289-87827280-3aef-11eb-8596-8b15da69e9bc.png)

**Comment by dzhwmeisner** [comment]
Im nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
hier hat sich leider noch nichts getan:
![grafik](https://user-images.githubusercontent.com/73596957/103515811-afa38e00-4e6f-11eb-8b07-f34fc71922fb.png)
