### ISSUE TITLE
Studium: stu_07 qt mobiler Vers. ändern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#44]
die mobile Version ist total zerschossen: bitte hier für jedes Item ein Karusell einbauen mit vertikalen ao. Was muss ich dafür im Code ändern?
![grafik](https://user-images.githubusercontent.com/73596957/101784086-57d96780-3afb-11eb-8c00-5432442c09c1.png)

**Comment by andreaschu** [comment]
@AliceFoelker ein Carousel gibt es nur für Matrizen. Das sind hier einzelne Fragen. Wenn sie vertikal dargestellt werden, dann nur untereinander.
Ich setze das mal um und baue die vertikale Variante für width < 768.
@christian-fr ich habe das mit sections gelöst. Bitte schau Dir das mal an.

**Comment by andreaschu** [comment]
#80

**Comment by AliceFoelker** [comment]
@andreaschu @christian-fr hier hat sich leider noch nichts getan

**Comment by andreaschu** [comment]
@AliceFoelker es gibt die Fragen alle zweimal und es wird über Einblendbedingung bestimmt, welche Version gesehen wird (horizontal oder vertikal). Diese basiert auf der Variable width, die auf der Index-Seite erstellt wird. Du musst, um die mobile Version zu sehen, die Befragung mit einem mobilen Gerät (oder der Simulation) betreten und die Index-Seite verlassen. Dann müsstest Du das hier sehen.
![grafik](https://user-images.githubusercontent.com/30111489/102601338-4e19ba80-4120-11eb-99ca-4ec8c65c6d2a.png)
