### ISSUE TITLE
msg_04 Fragetext im code überarbeitet

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#45]
in Modul 7 Seite msg_04 wurde der Fragetext unter q: im Code geändert. Ist es zudem möglich, auf der Seite die Reihenfolge des Ausfüllhinweises unter is: mit dem Fragetext q: zu tauschen? Passt dann besser

https://github.com/dzhw/studienberechtigte_2018.3b/commit/dbd81aadd6a44daf87b81b57c818671b12d98468

**Comment by christian-fr** [comment]
Fragetext ist angepasst, Reihenfolge `q:` und `is:`ist getauscht.
Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@heikQ q und is wurden getauscht, also gefixed ABER jetzt würde ich die >in< in der Schriftgröße schreiben wie die q. Wie siehst du das? Müssten wir dann daraus ein neues Issue machen? @andreaschu @christian-fr 


![grafik](https://user-images.githubusercontent.com/73596957/102079916-d725ae80-3e0d-11eb-9869-c2b1248f8d72.png)

**Comment by heikQ** [comment]
ja, eigenes neues Issue
