### ISSUE TITLE
msg_01 in Modul 7: Code für skalabeschriftung geändert

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#46]
in Modul 7 Seite msg_01 wurden die Bezeichungen der skalenpunkte geändert.

https://github.com/dzhw/studienberechtigte_2018.3b/commit/ac3a02bdf6ea1e5de065f27e2cacecbc362bfba4

**Comment by christian-fr** [comment]
Ist umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@heikQ Änderung der Skalenbeschriftung ist umgesetzt, aber auch hier wieder die Frage zu den Enpunkten
gibt es dafür evtl. eine Lösung? @andreaschu @christian-fr 
![grafik](https://user-images.githubusercontent.com/73596957/102079443-04259180-3e0d-11eb-8000-b91f2ec55164.png)

**Comment by heikQ** [comment]
@AliceFoelker @christian-fr @andreaschu Perfekt wäre es natürlich, wenn die Zahlen in einer Reihe stehen und die Beschriftungen der Pole an den Polen darüber jeweils. Geht das generell? Dann würden wir raussuchen, wo das überall der Fall ist
