### ISSUE TITLE
Modul7, Seite msg_02, ao´s im code geändert

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#47]
In Modul 7, Seite msg_02 wurden die ao´s für die skala beschriftung geändert
https://github.com/dzhw/studienberechtigte_2018.3b/commit/8c70b6bbdd1008846725abaaa383be4195543172

**Comment by christian-fr** [comment]
Ist umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@heikQ die Skalenbeschriftung ist eingefügt ABER wie siehst du das mit den Zahlen und den Beschriftungen der Endpunkte?
Drüber oder so lassen? Das selbe gilt für msg_03
![grafik](https://user-images.githubusercontent.com/73596957/102079147-6e8a0200-3e0c-11eb-93bc-88aa65b5c1d0.png)

**Comment by heikQ** [comment]
gern die Zahlen in einer Reiher und die Beschriftung nur an den Endpunkten drüber, aber glaube das geht nicht
