### ISSUE TITLE
Modul 7, Seite msg_03 ao´s im code geändert

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#48]
In Modul 7 Seite msg_03 wurden im Code die ao´s für die Skalabeschriftung überarbeitet.
https://github.com/dzhw/studienberechtigte_2018.3b/commit/952687a78b9dec03db0e75b58da4af222444271c

**Comment by christian-fr** [comment]
Ist umgesetzt, ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@heikQ die Skalenbeschriftung ist gefixed ABER ist es möglich die Endpunkte einheitlich entweder neben die Zahl oder darüber anzuordnen? @andreaschu @christian-fr 
![grafik](https://user-images.githubusercontent.com/73596957/102078848-e86dbb80-3e0b-11eb-99c7-8a00c685b1a4.png)

**Comment by heikQ** [comment]
generelle Frage, ob es geht, das Zahlen immer in einer Zeile und Text an Polen drüber ist. Schließe hier daher
