### ISSUE TITLE
Episodenmodule importieren

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#49]
Import der Episodenmodule:

- [x] Episoden: Ausbildung
- [x] Episoden: Schule
- [x] Episoden: Andere Tätigkeiten
- [x] Episoden: Arbeitslosigkeit
- [x] Episoden: Studium
- [x] Episoden: nichtselbstst. Erwerbstätigkeit
- [x] Episoden: Selbständige
- [x] Episoden: Weiterbildung
- [x] Episoden: Praktikum

**Comment by andreaschu** [comment]
[Episoden_Ausbildung (questionnaire9)](https://user-images.githubusercontent.com/30111489/102197450-78217180-3ec1-11eb-87e0-74d0773ecab3.png)
[Episoden-Schule questionnaire10)](https://user-images.githubusercontent.com/30111489/102197494-8b344180-3ec1-11eb-9f16-e76dd4b02ee2.png)
[Episoden_andereTätigkeiten (questionnaire11)](https://user-images.githubusercontent.com/30111489/102197483-88d1e780-3ec1-11eb-88ab-2236db408fae.png)
[Episoden_Arbeitslosigkeit (questionnaire12)](https://user-images.githubusercontent.com/30111489/102197491-8a9bab00-3ec1-11eb-89bf-e719c6e0004b.png)
[Episoden_Studium (questionnaire13)](https://user-images.githubusercontent.com/30111489/102197562-9edfa800-3ec1-11eb-99f8-0fa5d665583d.png)

[Episoden_nichtselbständige Erwerbstätigkeit (questionnaire14)]
[Episoden_selbständige Erwerbstätigkeit (questionnaire15)]

[Episoden_Weiterbildung (questionnaire16)](https://user-images.githubusercontent.com/30111489/102197556-9d15e480-3ec1-11eb-8af5-d0b6ef0f4faf.png)
[Episoden_Praktikum (questionnaire17)](https://user-images.githubusercontent.com/30111489/102197559-9dae7b00-3ec1-11eb-8b8f-2d60b1c4b34e.png)

**Comment by jocarstensen** [comment]
Die Seiten sind da, aber wir haben 500er-Fehler auf allen Zwischenseiten. Habt Ihr eine Idee, woran das liegen könnte?

**Comment by jocarstensen** [comment]
Wir haben den Fehler vermutlich gefunden. Sebastian ändert und committed im Code hier im Repository.

**Comment by se-lang** [comment]
Ist erledigt, ich hoffe das waren die einzigen Fehler.

**Comment by andreaschu** [comment]
Ich schließe das Issue mal da die Module alle importiert sind. Bei Fehler bitte ein neues Issue aufmachen.
Die FlowChart sind auch in #1.
