### ISSUE TITLE
Kalendarien

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#5]
**Kalendarien**:
Es werden zwei Kalendarien je nach subsample (Ansteuerung über preload- Variable "wave") mit unterschiedlichen Zeiträumen benötigt. Beide Kalendarien, Kategorien,  Einleitungstext und Befüllung von Hilfsvariablen  etc. sind bis auf die Zeiträume wie in der vorherigen slc-inter Befragung für das Kalendarium mit der prelaod-Variable cohort=2 (für 2018.3a) anzulegen.

Kalendarium A:
Zeitraum: Januar 2020 bis Dezember 2020
Kategorien: siehe slc-inter Befragung für cohort=2 (Kohorte 2018). Bitte auch Farbe/Muster der Kategorien wie in vorheriger Befragung.
Sichtbar für subsample wave=1 (Preload-Variable)

Kalendarium B:
Zeitraum: Januar 2018 bis Dezember 2020
Kategorien: siehe slc-inter Befragung für cohort=2 (Kohorte 2018). Bitte auch Farbe/Muster der Kategorien wie in vorheriger Befragung.
Sichtbar für subsample wave=2 or 3 or 4 or 5 (Preload-Variable)

**edit Alice: Kalendarium B auf Juli 2018 bis Dezember 2020 geändert. Januar bis Juni 2018 ausgegraut**

**Comment by andreaschu** [comment]
@heikQ kannst Du noch die Seiten-Bezeichnungen angeben? 
Und am besten noch, die Position im Fragebogen bzw. welche Seite/n danach kommen soll/en. Das finde ich im Flowchart nicht.

**Comment by heikQ** [comment]
@andreaschu  Klar. Die Kalendarien kommen sind im Flowchart im Block mit dem Episodenmodul mit drin und kommen nach Modul 2 bzw. 3. Im Flowchart steht vor den eine Filterung auf die Zwischenseiten Episoden A und Episoden B. Habe ich falsch bezeichnet. eigentlich sind es die Zwischenseiten für die Kalendarien, also Zwischenseite Kalendarium A und Kalendarium B. Ihr könnt die Zwischenseiten gern zunächst leer anlegen z.B. als zwisch_cal_a und zwisch_cal_b bzw. zwisch_cal_1 und zwisch_cal_2 wenn euch das lieber ist als die Buchstaben. Die jeweils folgenden Seiten mit Kalendarien könnt ihr dann einfach cal_a und cal_b bzw. cal_1 und cal_2 nennen. 
Danke!

**Comment by jocarstensen** [comment]
Für die Programmierung der neuen HV brauchen wir die Kalendarien bzw. müssen die Trigger dafür aus den Kalendarien mit jemandem koordinieren. Wie ist denn hier der Stand?

**Comment by se-lang** [comment]
Ich die transitions von zwischen_epi (Seite mit Fortschrittsbalken vor den Kalendarien) jetzt wie folgt geschrieben:
- `target="zwischen_cal_am" condition="zofar.asNumber(PRELOADwave)==1 and jsCheck2.value and width2.value lt 768"` 
- `target="zwischen_cal_ad" condition="zofar.asNumber(PRELOADwave)==1 and jsCheck2.value and width2.value ge 768"`
- `target="zwischen_cal_bm" condition="zofar.asNumber(PRELOADwave)!=1 and jsCheck2.value and width2.value lt 768"` 
- `target="zwischen_cal_bd" condition="zofar.asNumber(PRELOADwave)!=1 and jsCheck2.value and width2.value ge 768"`
- `target="zwischen_k" condition="!jsCheck2.value"`

**Comment by andreaschu** [comment]
Die Kalendarien sind noch nicht angepasst. Das dauert aber nicht lang.
Sollen wir die Variablennamen nach der bisherigen Logik benennen, also:
               `cohort[KohortenID][Monat][Slot]`

Dabei sind die Slots folgendermaßen definiert: 
```
cohort101studium ---> Slot1
cohort101ausb ---> Slot2
cohort101fortb ---> Slot3
cohort101jobben ---> Slot4
cohort101erwerb ---> Slot5
cohort101praktikum ---> Slot6
cohort101elternz ---> Slot7
cohort101alo ---> Slot8
cohort101sonstiges ---> Slot9
```
Monate sind durchgezählt von 01 (Januar 2018) bis 24 (Dezember 2019).
Die Monate wären wieder von 01 (Januar 2018) bis 36 (Dezember 2020). 
Das wären Variablen : 
von: **cohort201[studium]**
bis: **cohort236[sonstiges]**

Die KohortenID würde ja gleich bleiben, bei beiden Kalendarien (cohort2). Oder sollen die sich nach _wave_ unterscheiden?

**Comment by heikQ** [comment]
@se-lang @ @jocarstensen Gibt es von euch aus Koventionen bei der Bennunng der Variablen aus dem Kalendarium (siehe Andreas Vorschläge), da ja je nach Kalendariumsangabe Epi-Module angezeigt werden, oder ist das egal?

**Comment by se-lang** [comment]
Konventionen von unserer Seite gibt es nicht, da für die Steuerung im Episodenmodul nur die Hilfsvariablen relevant sind, die auf der Zwischenseite nach den Kalendarien gebildet werden.

Mein Vorschlag wäre entsprechend der besseren Verständlichkeit die Variablen und Kalendarien nicht mehr nach _cohort_ zu benennen, sondern eben nach _wave_:
- _wave1..._ für 'wave==1'
- _wave25..._ für 'wave==2 or wave==3 or wave==4 or wave==5'

Wichtig ist nur, dass die Generierung der HVs auf der Zwischenseite nach den Kalendarien entsprechend angepasst bzw. für die fehlenden HVs noch ergänzt werden muss, das muss aber unabhängig von obiger Benennung in jedem Fall getan werden.

**Comment by andreaschu** [comment]
@se-lang ja, die Anpassung der Weiterleitung machen wir noch.
Die Frage der Variablen bezieht sich auch darauf, dass ihr bei getrennter Benennung der Variablen für das Jahr 2020 die doppelte Anzahl von Variablen habt, ihr die Kalendarien auch trennen könnt.
Ich glaube das letzte Mal hatten wir es getrennt, weil zwei getrennte Datensätze dabei rauskommen sollten. Da ich nicht weiß, wie ihr die Datenaufbereitung organisiert, wollte ich vorher fragen was am besten für Euch ist. 
Ein weiteres Argument wäre das Matching mit der vorherigen Welle. Wenn das passieren soll, wäre es ggf. sinnvoll die Namen beizubehalten.

**Comment by heikQ** [comment]
@andreaschu @se-lang @jocarstensen Wenn das technisch okay ist, brauchen wir keine unterschiedliche Benennung und keine doppelten Variablen für 2020. Dann wäre Andreas Vorschlag zur Bennung ja sinnvoll, Also Kohort (immer cohort2)/Monat/Slot. Können wir dann m.E. gern so machen und trennen können wir über wave ja dann eh auch später..

**Comment by andreaschu** [comment]
Die Kalendarien sind erstellt. 
Als Variablen wurden `cohort2[Monat][Slot]` verwendet.
Die Seiten heißen cal1 für `wave==1` und cal25 für `wave!=1`.
@se-lang die Weiterleitung wurde geändert, aber auf der Seite zwischen_epi, die sich in einem anderen XML befindet. Wir laden heute noch alle FlowCharts in das #1.

Für die Texte für die Zwischen-Seiten zwischen_cal_am - zwischen_cal_bd haben wir bisher noch nicht keine Vorlage. Wir haben die Seiten von SLC_IntEr übernommen.

![2020-12-15_17-42_questionnaire8](https://user-images.githubusercontent.com/30111489/102339298-3d890900-3f95-11eb-8fe7-dbc1d012cced.png)

**Comment by se-lang** [comment]
@andreaschu Nur um sicher zu gehen und weil du mich markiert hast: Welche Weiterleitungen meinst du? 
Auf zwischen_epi sind in der Version, die ich geschrieben habe (ohne die Anpassungen aus #64 ), nur Transitions nach zwischen_cal_am, zwischen_cal_ad, zwischen_cal_bm, zwischen_cal_bd und zwischen_k. An den Seitennamen hat sich aber doch nichts geändert, oder?
Was auf jeden Fall angepasst werden muss sind die Trigger auf zwischen_k.

**Comment by andreaschu** [comment]
@se-lang: In dem obigen FlowChart wird nicht klar, wie man auf die Seiten (zwischen_cal_am…) kommt. Das wird in einem anderen FlowChart deutlich, das es aber noch nicht gibt. Ich wollte nur sagen, dass deine Änderungen auch vorgenommen wurden und getestet werden können (ebenfalls noch ohne Anpassung aus #64). 

Die Seiten hießen vorher cal0001 bis cal0004. Das habe ich jetzt geändert. Die Kalendariumsseiten hießen auch anders.

Bei den Triggern hatte ich gestern die condition geändert, siehe: https://github.com/dzhw/studienberechtigte_2018.3b/commit/7f82cbbd8e521310ad25e2f376e471bbe5ff1165

**Comment by se-lang** [comment]
@andreaschu Ach so, dann hatte ich dich nur falsch verstanden.
Dann fehlen nur noch die konkreten Anpassungen der Trigger auf das neue Kalendarium und die neuen HVs, die es in der letzten Befragung noch nicht gab.

**Comment by heikQ** [comment]
Einige Hilfsvariablen müssten noch aus dem Kalendarium und/oder Episodenmodulen befüllt werden. Für die Testung, ob die richtigen Episodenmodule je nach Kalendariumseingabe angezeigt werden, wäre es gut, wenn die Befüllung aus den Kalendarien möglichst bald umgesetzt wird. Nachfolgend nochmal die Liste:

**Hilfsvariable h_studium**
Bedingung: mind. 1 Episode in Kalender
Beschreibung: mind. eine   Studienepisode im Kalender angegeben

**Hilfsvariable h_studever**
Bedingung: mind. 1 Episode jemals in Kalender oder Episodenmodul
Beschreibung: mind. eine   Studienepisode im Kalender oder Episodenmodul angegeben

**Hilfsvariable h_studakt**
Bedingung: mind. 1 aktuelle Episode in Kalender oder Episodenmodul
Beschreibung: mind. eine   Studienepisode im Kalender oder Episodenmodul für letzten Monat angegeben

**Hilfsvariable h_ausb**
Bedingung: mind. 1 Episode in Kalender
Beschreibung: mind. eine  Berufsausbildungsepisode im Kalender angegeben

**Hilfsvariable h_ausbever**
Bedingung: mind. 1 Episode jemals in Kalender oder Episodenmodul
Beschreibung: mind. eine   Berufsausbildungsepisode im Kalender oder Episodenmodul angegeben

**Hilfsvariable h_ausbakt**
Bedingung: mind. 1 aktuelle Episode in Kalender oder Episodenmodul
Beschreibung: mind. eine   Berufsausbildungsepisode im Kalender oder Episodenmodul für letzten Monat angegeben

**Hilfsvariable h_erwerb**
Bedingung: mind. 1 Episode in Kalender
Beschreibung: mind. eine  Erwerbstätigkeitsepisode im Kalender angegeben

**Hilfsvariable h_erwerbever**
Bedingung: mind. 1 Episode jemals in Kalender oder Episodenmodul
Beschreibung: mind. eine   Erwerbstätigkeitsepisode im Kalender oder Episodenmodul angegeben

**Hilfsvariable h_erwerbakt**
Bedingung: mind. 1 aktuelle Episode in Kalender oder Episodenmodul
Beschreibung: mind. eine   Erwerbstätigkeitsepisode im Kalender oder Episodenmodul für letzten Monat angegeben

**Comment by AliceFoelker** [comment]
@jocarstensen zählt das Anerkennungsjahr dann bei den Aktivitäten eigentlich zum "Praktikum"?
![grafik](https://user-images.githubusercontent.com/73596957/103544821-f2ca2500-4ea0-11eb-933c-7d0bc4fa29f0.png)

**Comment by jocarstensen** [comment]
@andreaschu Es gibt eine Änderung in Kalendarium B (Cal25). Können wir hier (wie auch letztes Jahr in IntEr) die Monate Januar-Juni in 2018 ausgrauen und nichtausfüllbar machen?

**Comment by jocarstensen** [comment]
Wird die Änderung (s. mein Kommentar drüber) beim nächsten Rollout auch ausgeführt? Ich brauche dazu eine Rückmeldung, damit ich mich um die Trigger auf zwischen_k kümmern kann.

**Comment by andreaschu** [comment]
@jocarstensen, ja, das sollte klappen. Die Trigger kann ich gleichzeitig ändern. 
@dzhwmeisner kümmerst Du dich darum https://github.com/dzhw/studienberechtigte_2018.3b/issues/5#issuecomment-758629034?

**Comment by dzhwmeisner** [comment]
Im nächsten Rollout verfügbar
