### ISSUE TITLE
SozDem: msg_04 Schriftgröße ändern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#51]
>in< gleiche Schriftgröße wie >q< bitte

![grafik](https://user-images.githubusercontent.com/73596957/102189772-6b981b80-3eb7-11eb-9617-4528c15221a6.png)

**Comment by christian-fr** [comment]
@AliceFoelker 
Wie soll die Schriftgröße geändert werden? 

[In der PV](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul07_SozDem.md#_msg_04_) findet sich derzeit dies hier:

```
msg_04
[...]
in: Die eigenen Entscheidungen werden durch die Persönlichkeitseigenschaften beeinflusst. Inwieweit treffen die folgenden Aussagen auf Sie zu?
q: Ich bin jemand, der...
is: Bitte jeweils den zutreffenden Skalenwert ankreuzen.
```

Soll die erste Zeile (`in:`) auch als Fragetext (`q:`) gesetzt werden?

Falls ja, hier mein Vorschlag für die PV:
``` 
q1: Die eigenen Entscheidungen werden durch die Persönlichkeitseigenschaften beeinflusst. Inwieweit treffen die folgenden Aussagen auf Sie zu?
is: Bitte jeweils den zutreffenden Skalenwert ankreuzen.
q2: Ich bin jemand, der...
```

**Comment by christian-fr** [comment]
Ist umgesetzt. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
