### ISSUE TITLE
Offener Angabenbereich in mobiler Version abgeschnitten z.B. beg_02,stu_23,27,28

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#52]
![grafik](https://user-images.githubusercontent.com/73596957/102191259-75228300-3eb9-11eb-9470-0020b3ce5e86.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#71 ) verfügbar

**Comment by AliceFoelker** [comment]
also bei mir sieht es immernoch so aus: firefox
![grafik](https://user-images.githubusercontent.com/73596957/102500644-d21a6680-407c-11eb-8587-c03e580d6ae6.png)

**Comment by AliceFoelker** [comment]
gefixed, aber entschuldige @vdick ich habe beg_3 vergessen. Das müsste noch Sorry

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#97 ) verfügbar
