### ISSUE TITLE
Studium: stu_28 evtl. einzelne Präfixe?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#55]
@heikQ  Hier evtl. Hochschule und Ort in 2 strings abfragen + jew. Präfixe?

![grafik](https://user-images.githubusercontent.com/73596957/102197330-47d9d300-3ec1-11eb-9cbd-6bc187959bf4.png)

**Comment by heikQ** [comment]
@AliceFoelker Gute idee, könnte einen unterschied zu bisher machen, für kommende wellen ja, für diese nicht, wegen Längsschnitt. zudem intention, da ist ist plz teils schwierig

**Comment by AliceFoelker** [comment]
Das stimmt, aber die PLZ wäre evtl. ja auch nicht nötig aber dann hätte man zumindest hinterher in der Aufbereitung 2 Spalten für Hochschule und Ort. Vielleicht würde die Trennung einen technischen Unterschied für die Aufbereitung, bzw. Vereinfachung machen?! Vielleicht sinnvoll das als Kommi in PV festzuhalten? Sonst erinnert sich nächstes mal kein Mensch dran.
