### ISSUE TITLE
Modul 1; Seite beg_04 layout Fehler bei Antworten

### ISSUE THREAD

**Issue by heikQ** [dzhw/studienberechtigte_2018.3b#59]
Browser chrome auf Notebook:
Die Antwortendarstellung ist noch/wieder zerschossen
![beg_04t](https://user-images.githubusercontent.com/52539440/102242973-f0585900-3efa-11eb-80dd-21be1b29f3ed.PNG)

**Comment by christian-fr** [comment]
Ist umgesetzt. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
