### ISSUE TITLE
Studium: stu_19 is Schriftgröße und Position ändern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#60]
Ist es möglich die >is< auf der Seite so dick wie >q< zu machen und weiter unten zu plazieren?

![grafik](https://user-images.githubusercontent.com/73596957/102328285-27744c00-3f87-11eb-84f0-08610927a456.png)

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
