### ISSUE TITLE
SozDem: msg_02, 03, 20 Skalenendpunkte mit Zahl vertauscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#62]
Wir werden jetzt nach und nach bei manchen vertikalen Einzelskalen die Zahlen und Enpunkte vertauschen damit es optisch ein einheitlicheres Bild ergibt.
![grafik](https://user-images.githubusercontent.com/73596957/102331357-0a417c80-3f8b-11eb-87e4-b4cdbd3e4e6f.png)

**Comment by andreaschu** [comment]
ab nächstem Roll-Out verfügbar

**Comment by AliceFoelker** [comment]
fixed
