### ISSUE TITLE
Fortschrittsbalken und Zwischenseiten sehr klein

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#63]
Die Fortschrittsbalken und Zwischenseiten sind sehr klein dargestellt (Desktop und Mobil). Ist es möglich diese ein wenig größer einzublenden?

![grafik](https://user-images.githubusercontent.com/73596957/102333320-8c32a500-3f8d-11eb-9411-5b16ec40b8d2.png)

![grafik](https://user-images.githubusercontent.com/73596957/102333055-2c3bfe80-3f8d-11eb-8f0b-b71472f78821.png)

**Comment by andreaschu** [comment]
@christian-fr ich fürchte, hier müssen wir noch mal ran. Die Bilder sind sehr klein, egal wie groß ich den Rest skaliere.

![grafik](https://user-images.githubusercontent.com/30111489/102380522-4e9f3d80-3fc8-11eb-8009-a97d9d967d41.png)

![grafik](https://user-images.githubusercontent.com/30111489/102380629-6d9dcf80-3fc8-11eb-9347-000ee87a41a1.png)

**Comment by AliceFoelker** [comment]
@andreaschu @christian-fr 
ich fürchte in der mobilen Version, wenn ich es auf meinem Handy S9 durchklicke stimmt etwas nicht siehe Screenshot

![grafik](https://user-images.githubusercontent.com/73596957/102388497-21578d00-3fd2-11eb-8c66-6de5baf9815e.png)

**Comment by andreaschu** [comment]
@AliceFoelker siehe meinen vorherigen Kommentar. Hier müssen wir noch mal ran.

**Comment by andreaschu** [comment]
@AliceFoelker mach mal bitte strg+umschalt+r und schau es dir noch mal an. Bei mir funktioniert.

**Comment by AliceFoelker** [comment]
ja, das sieht jetzt besser aus:
@andreaschu wird die Größe der Zwischenseite dann eigentlich an den Bildschirm angepasst wenn die Roten Infos raus kommen?

![grafik](https://user-images.githubusercontent.com/73596957/102485289-b22c7800-4067-11eb-9b3d-900458ba1356.png)
