### ISSUE TITLE
transition aus Modul 3 - Schulabschluss

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#64]
Laut [Gesamtablauf](https://github.com/dzhw/studienberechtigte_2018.3b/files/5623914/flowchart_FB_01-Dez.pdf) sollen alle aus dem Modul 3 auf die Kalendarien und dann in die Episoden laufen. Laut [Programmiervorlage](https://github.com/dzhw/studienberechtigte_2018.3b/blob/main/Modul03_Schulabschluss.md#_reife_04_), geht es aus dem Modul aber in das Modul Ausbildung.

@AliceFoelker und @heikQ könnt Ihr Euch das mal ansehen und ggf. korrigieren?

**Comment by AliceFoelker** [comment]
@andreaschu das stimmt. Das hatten wir bewusst überfiltert, damit man nicht manuell ansteuern musste solange die Episoden noch nicht programmiert sind. Jetzt muss ich nur checken auf welche Seite ich die Befragten aus Modul03 leite damit diese auch die Ausfüllhinweise bekommen.

**Comment by andreaschu** [comment]
ah, okay. 
Ich denke, das ist `zwischen_epi`. Von da aus wird auf die Seiten `zwischen_cal_am `bis `zwischen_cal_bd `gefiltert.

**Comment by AliceFoelker** [comment]
vermutlich befindet sich hier meine Antwort 

https://github.com/dzhw/studienberechtigte_2018.3b/issues/5#issuecomment-746109733

ja für wave1-3 trifft das mit zwischen_epi zu. Da aber wave 4 und 5 diese Zwischenseite vorgezogen angezeigt bekommen (auf reife_00) damit sie nicht gesondert für dieses Modul03 einen Fortschritt brauchen, muss ich zwischen_epi überfiltern und ich vermute auf zwischen_cal_bd.

**Comment by andreaschu** [comment]
@AliceFoelker ja, zum Teil. Nur das hier die zwischen_epi nicht enthalten ist.
Die Transition von da ist z.T. abhängig vom verwendeten Gerät. Die findest Du hier: 
https://github.com/dzhw/studienberechtigte_2018.3b/blob/d22f7ac757e2f6434ee077a0823d608c33f7a643/9_zwischenseiten.xml#L5421

m steht für _Mobil_ und d für _Desktop_.

**Comment by AliceFoelker** [comment]
@andreaschu sehe ich da richtig, dass auf zwischen_epi eine Filterung stattfindet, sodass eine Überfilterung eher blöd wäre?!

**Comment by andreaschu** [comment]
Auf zwischen_epi findet eine Filterung zu dem Kalendariums-Modul statt. Da werden aber die Wellen anders behandelt, nämlich 1 anders als 2-5. Ich weiß nicht, wie sich das mit dem was Du vor hast verhält.

> ja für wave1-3 trifft das mit zwischen_epi zu. Da aber wave 4 und 5 diese Zwischenseite vorgezogen angezeigt bekommen (auf reife_00) damit sie nicht gesondert für dieses Modul03 einen Fortschritt brauchen, muss ich zwischen_epi überfiltern und ich vermute auf zwischen_cal_bd.

**Comment by se-lang** [comment]
In Absprache mit Alice hier die Transitions für einen Lösungsvorschlag. Bitte erst tätig werden, wenn @AliceFoelker ein entsprechendes Zeichen gibt.

letzte Seite Modul 2:
```
<zofar:transitions>
	<zofar:transition target="zwischen_epi"/>
</zofar:transitions>
```

zwischen_epi:
```
<zofar:transitions>
	<zofar:transition target="reife_01"
		condition="	zofar.asNumber(PRELOADwave)==4
				or
				zofar.asNumber(PRELOADwave)==5" />
	<zofar:transition target="zwischen_cal_am"
		condition="	zofar.asNumber(PRELOADwave)==1
				and
				jsCheck2.value 
				and 
				width2.value lt 768" />
	<zofar:transition target="zwischen_cal_ad"
		condition="	zofar.asNumber(PRELOADwave)==1
				and
				jsCheck2.value 
				and 
				width2.value ge 768
				" />
	<zofar:transition target="zwischen_cal_bm"
		condition="	zofar.asNumber(PRELOADwave)!=1
				and
				jsCheck2.value 
				and 
				width2.value lt 768" />
	<zofar:transition target="zwischen_cal_bd"
		condition="	zofar.asNumber(PRELOADwave)!=1
				and
				jsCheck2.value 
				and 
				width2.value ge 768" />
	<zofar:transition target="zwischen_k" 
		condition=" !jsCheck2.value"/>
</zofar:transitions>
```

letzte Seite Modul 3:
```
<zofar:transitions>
	<zofar:transition target="zwischen_cal_bm"
		condition="	jsCheck2.value 
				and 
				width2.value lt 768" />
	<zofar:transition target="zwischen_cal_bd"
		condition="	jsCheck2.value 
				and 
				width2.value ge 768" />
	<zofar:transition target="zwischen_k" 
		condition="	 !jsCheck2.value"/>
</zofar:transitions>
```

**Comment by AliceFoelker** [comment]
@andreaschu von meiner Seite kann das gerne so übernommen werden. Gibt es eine Möglichkeit das auch in die Codes zu übernehmen zwecks Nachvollziehbarkeit?

**Comment by andreaschu** [comment]
@AliceFoelker okay und ja, das sollte im Code geändert werden.

**Comment by AliceFoelker** [comment]
@andreaschu dann würde ich die Codes noch ändern, bräuchte da aber ein bisschen Hilfe: 
-Die Änderung der Transition in Modul02 habe ich gemacht.
-wie ich die Änderungen auf zwischen_epi mache weiß ich nicht - finde den Code dazu gar nicht erst
-wie würde eine Anpassung dann für Modul03 aussehen. in etwa so? Send help

![grafik](https://user-images.githubusercontent.com/73596957/102359030-93b77580-3fb0-11eb-895f-4082c9759b5a.png)

**Comment by andreaschu** [comment]
das ist in dem code für die Zwischenseiten. Ich habe es eingefügt und committed: 
https://github.com/dzhw/studienberechtigte_2018.3b/commit/95cabda19d3a23ec33a3449ad56f87720ac5e063

**Comment by andreaschu** [comment]
Ja, genau so

> -wie würde eine Anpassung dann für Modul03 aussehen. in etwa so? Send help
> 
> ![grafik](https://user-images.githubusercontent.com/73596957/102359030-93b77580-3fb0-11eb-895f-4082c9759b5a.png)

**Comment by AliceFoelker** [comment]
@andreaschu Oh ich habe es jetzt quasi "falsch" verbessert, kann man eigentlich eine Änderung, also einen commit noch mal ändern?
Und reicht es jetzt eigentlich, dass ich das commit gereferenced hab oder müsste ich da noch mal anders darauf aufmerksam machen?
> 
> Ja, genau so
> edit: Na ja, fast: es muss `width2.value<768` heißen. Das können wir aber richtig übersetzen.
> 
> > -wie würde eine Anpassung dann für Modul03 aussehen. in etwa so? Send help
> > ![grafik](https://user-images.githubusercontent.com/73596957/102359030-93b77580-3fb0-11eb-895f-4082c9759b5a.png)

**Comment by andreaschu** [comment]
> Und reicht es jetzt eigentlich, dass ich das commit gereferenced hab oder müsste ich da noch mal anders darauf aufmerksam machen?

Das reicht.
Ich habe alle drei Transitions geändert. Ist ab Roll Out #61

**Comment by AliceFoelker** [comment]
nach dem Modul03 (Schulabschluss) lande ich auf zwischen_k

**Comment by se-lang** [comment]
@andreaschu Gleiche Vermutung wie in #68. Fehlen vllt. noch jsCheck2 und width2 auf einer der vorherigen Seiten (z.B. cor_07). Wenn jsCheck2 nicht gefüllt ist, landet man auf zwischen_k.

**Comment by andreaschu** [comment]
@AliceFoelker  bei mir funktioniert es jetzt. Kann es zu?
