### ISSUE TITLE
Studium: stu_01-06 Skalenendpunkte mit Zahl vertauscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#66]
Wir werden jetzt nach und nach bei manchen vertikalen Einzelskalen die Zahlen und Endpunkte vertauschen damit es optisch ein einheitlicheres Bild ergibt

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
