### ISSUE TITLE
Einstieg: beg_01,06 Zahlen mit Skalenendpunkten vertauscht

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#67]
Wir werden jetzt nach und nach bei manchen vertikalen Einzelskalen die Zahlen und Endpunkte vertauschen damit es optisch ein einheitlicheres Bild ergibt.

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
@andreaschu @christian-fr das hat leider noch nicht geklappt:

![grafik](https://user-images.githubusercontent.com/73596957/102386490-6af2a880-3fcf-11eb-917a-8d9c60c3297f.png)

**Comment by andreaschu** [comment]
Ab nächstem Rollout verfügbar.

**Comment by AliceFoelker** [comment]
fixed
