### ISSUE TITLE
500er-Fehler auf allen Zwischenseiten

### ISSUE THREAD

**Issue by christian-fr** [dzhw/studienberechtigte_2018.3b#68]
[jocarstensen schrieb](https://github.com/dzhw/studienberechtigte_2018.3b/issues/49#issuecomment-746382035) in issue #49 :
> Die Seiten sind da, aber wir haben 500er-Fehler auf allen Zwischenseiten. Habt Ihr eine Idee, woran das liegen könnte?

**Comment by christian-fr** [comment]
Ab nächstem Rollout gefixt.

**Comment by se-lang** [comment]
@andreaschu Könnte das an den noch fehlenden HVs und der Anpassung der HVs an die neuen Kalendarien liegen? Aktuell werden die ja vermutlich alle nicht befüllt und entsprechend könnte es gut sein, dass keine der Bedingungen zutrifft.

**Comment by andreaschu** [comment]
@se-lang wir haben es gerade ausgerollt. Bitte versuche es noch mal.

**Comment by se-lang** [comment]
@AliceFoelker testet das und gibt Rückmeldung.

**Comment by AliceFoelker** [comment]
m.E. klappt das
