### ISSUE TITLE
Preloads für Kohorte

### ISSUE THREAD

**Issue by andreaschu** [dzhw/studienberechtigte_2018.3b#69]
Wir benötigen nun Preloads für cohort, sonst können einige Bedingungen und Trigger nicht getestet werden. 
Allerdings bekommen alle denselben Wert: PRELOADcohort==2
Kannst Du das einbauen?

**Comment by vdick** [comment]
@andreaschu ist überhaupt kein Problem, nur müsste ich dafür kurz die Datanbank leeren. Soll ich?

**Comment by andreaschu** [comment]
@vdick ja, bitte.

**Comment by vdick** [comment]
@andreaschu FERTIG
