### ISSUE TITLE
Transition zwischen_epi in Kalendarium fehlerhaft

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#70]
tester18 wave 1 
von zwischen_epi werde ich zu zwischen_k weitergeleitet. da müsste ich mit dem PC doch auf zwischen_cal_ad landen oder?

**Comment by andreaschu** [comment]
ich glaube das liegt an jscheck2 und width2, die hier noch nirgendwo gesetzt werden.

**Comment by andreaschu** [comment]
ist so eingebaut. Ab nächstem Roll Out testbar.

**Comment by AliceFoelker** [comment]
m.E. funktioniert das jetzt
