### ISSUE TITLE
mas_02 & mas_03 deutlicher unterstreichen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#73]
Ist es möglich die Unterstreichung deutlicher zu gestalten? @heikQ oder einfach dick? So geht es jedenfalls unter.

![grafik](https://user-images.githubusercontent.com/73596957/102467741-f06a6d00-4050-11eb-88eb-13afa4ae70d4.png)

**Comment by christian-fr** [comment]
Eine andere Unterstreichung steht nicht zur Verfügung.
Der Text kann noch dicker oder bspw. kursiv gesetzt werden.

**Comment by andreaschu** [comment]
Ab nächstem Roll-Out verfügbar.
