### ISSUE TITLE
Aktivitätenauswahl in Kalendarium letzter Punkt anders

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#74]
Kann man den letzten Punkt auch neben das farbige Kästchen setzen?
![grafik](https://user-images.githubusercontent.com/73596957/102476270-34fb0600-405b-11eb-843a-468830e47698.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#71 ) verfügbar

**Comment by AliceFoelker** [comment]
fixed
