### ISSUE TITLE
Fortschrittsbalken im Episodenmodul fehlen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#75]

**Comment by christian-fr** [comment]
Fortschrittsbalken ist für folgende pages hinzugefügt:

`
v0001, vaa01, vaa05, vaa06, vaa07, vaa08, vaa10, vaa20, vaa21, vab06, vab07, vab08, vab10, vab20, vab21, vac06, vac07, vac08, vac10, vac20, vac21, vad06, vad07, vad08, vad10, vad20, vad21, vae06, vae07, vae08, vae10, vae20, vae21, vaz06, vaz10, vaa23, vaa24, vaa25, vaa29, vaa30, vba01, vba05, vba06, vba07, vba08, vba10, vba20, vba21, vbb06, vbb07, vbb08, vbb10, vbb20, vbb21, vbc06, vbc07, vbc08, vbc10, vbc20, vbc21, vbd06, vbd07, vbd08, vbd10, vbd20, vbd21, vbz06, vbz10, vba23, vba24, vba25, vba29, vba30, vca01, vca05, vca06, vca07, vca08, vca10, vca20, vca21, vcb06, vcb07, vcb08, vcb10, vcb20, vcb21, vcc06, vcc07, vcc08, vcc10, vcc20, vcc21, vcz06, vcz10, vca23, vca24, vca25, vca29, vca30, vda01, vda05, vda06, vda07, vda08, vda10, vda20, vda21, vdb06, vdb07, vdb08, vdb10, vdb20, vdb21, vdz06, vdz10, vda23, vda24, vda25, vda29, vda30, vea01, vea05, vea06, vea07, vea08, vea10, vea20, vea21, vez06, vez10, vea23, vea24, vea25, vea29, vea30, v0002, vza01, vza05, vza06, vza10, vza23, vza24, vza25, vza29, o0001, oaa01, oaa05, oaa07, oaa12, oab01, oab05, oab07, oab12, oca01, oca05, oca10, oda01, oda05, odb01, odb05, oea01, oea05, oeb01, oeb05, u0001, uaa01, uaa05, uaa06, uaa20, uba01, uba05, uba06, uba20, uca01, uca05, uca06, uca20, uda01, uda05, uda06, uda20, st0001, staa01, staa04, staa07, staa09, staa10, staa16, staa17, staa18, staa19, staa21, staa23, staa24, staa25, staa29, staa31, staa33, staa34, staa42, staa43, staa47, stab04, stab07, stab09, stab10, stab16, stab17, stab18, stab19, stab21, stab23, stab24, stab25, stab29, stab31, stab33, stab34, stac04, stac07, stac09, stac10, stac16, stac17, stac18, stac19, stac21, stac23, stac24, stac25, stac29, stac31, stac33, stac34, stad04, stad07, stad09, stad10, stad16, stad17, stad18, stad19, stad21, stad23, stad24, stad25, stad29, stad31, stad33, stad34, stae04, stae07, stae09, stae10, stae16, stae17, stae18, stae19, stae21, stae23, stae24, stae25, stae29, stae31, stae33, stae34, stba01, stba04, stba07, stba09, stba10, stba16, stba17, stba18, stba19, stba21, stba23, stba24, stba25, stba29, stba31, stba33, stba34, stba42, stba43, stba47, stbb04, stbb07, stbb09, stbb10, stbb16, stbb17, stbb18, stbb19, stbb21, stbb23, stbb24, stbb25, stbb29, stbb31, stbb33, stbb34, stbc04, stbc07, stbc09, stbc10, stbc16, stbc17, stbc18, stbc19, stbc21, stbc23, stbc24, stbc25, stbc29, stbc31, stbc33, stbc34, stbd04, stbd07, stbd09, stbd10, stbd16, stbd17, stbd18, stbd19, stbd21, stbd23, stbd24, stbd25, stbd29, stbd31, stbd33, stbd34, stca01, stca04, stca07, stca09, stca10, stca16, stca17, stca18, stca19, stca21, stca23, stca24, stca25, stca29, stca31, stca33, stca34, stca42, stca43, stca47, stcb04, stcb07, stcb09, stcb10, stcb16, stcb17, stcb18, stcb19, stcb21, stcb23, stcb24, stcb25, stcb29, stcb31, stcb33, stcb34, stcc04, stcc07, stcc09, stcc10, stcc16, stcc17, stcc18, stcc19, stcc21, stcc23, stcc24, stcc25, stcc29, stcc31, stcc33, stcc34, stda01, stda04, stda07, stda09, stda10, stda16, stda17, stda18, stda19, stda21, stda23, stda24, stda25, stda29, stda31, stda33, stda34, stda42, stda43, stda47, stdb04, stdb07, stdb09, stdb10, stdb16, stdb17, stdb18, stdb19, stdb21, stdb23, stdb24, stdb25, stdb29, stdb31, stdb33, stdb34, stea01, stea04, stea07, stea09, stea10, stea16, stea17, stea18, stea19, stea21, stea23, stea24, stea25, stea29, stea31, stea33, stea34, stea42, stea43, stea47, st0002, st0005, st0008, st0010, st0011, st0017, st0018, st0019, st0020, st0022, st0024, st0025, st0026, st0030, st0032, em0001, emaa01, emaa06, emaa09, emaa11, emaa12, emaa13, emaa14, emaa16, emaa22, emaa24, emaa26, emaa28, emaa31, emaa33, emaa35, emaa37, emaa38, emaa39, emaa40, emab06, emab09, emab11, emab12, emab13, emab14, emab16, emab22, emab24, emab26, emab28, emab31, emab33, emab35, emab37, emab38, emac06, emac09, emac11, emac12, emac13, emac14, emac16, emac22, emac24, emac26, emac28, emac31, emac33, emac35, emac37, emac38, emad06, emad09, emad11, emad12, emad13, emad14, emad16, emad22, emad24, emad26, emad28, emad31, emad33, emad35, emad37, emad38, emae06, emae09, emae11, emae12, emae13, emae14, emae16, emae22, emae24, emae26, emae28, emae31, emae33, emae35, emae37, emae38, emaf06, emaf09, emaf11, emaf12, emaf13, emaf14, emaf16, emaf22, emaf24, emaf26, emaf28, emaf31, emaf33, emaf35, emaf37, emaf38, emaa42, emaa43, emaa45, emaa46, emaa47, emaa48, emaa50, emaa51, emaa64, emba01, emba06, emba09, emba11, emba12, emba13, emba14, emba16, emba22, emba24, emba26, emba28, emba31, emba33, emba35, emba37, emba38, emba39, emba40, embb06, embb09, embb11, embb12, embb13, embb14, embb16, embb22, embb24, embb26, embb28, embb31, embb33, embb35, embb37, embb38, embc06, embc09, embc11, embc12, embc13, embc14, embc16, embc22, embc24, embc26, embc28, embc31, embc33, embc35, embc37, embc38, embd06, embd09, embd11, embd12, embd13, embd14, embd16, embd22, embd24, embd26, embd28, embd31, embd33, embd35, embd37, embd38, embe06, embe09, embe11, embe12, embe13, embe14, embe16, embe22, embe24, embe26, embe28, embe31, embe33, embe35, embe37, embe38, emba42, emba43, emba45, emba46, emba47, emba48, emba50, emba51, emba64, emca01, emca06, emca09, emca11, emca12, emca13, emca14, emca16, emca22, emca24, emca26, emca28, emca31, emca33, emca35, emca37, emca38, emca39, emca40, emcb06, emcb09, emcb11, emcb12, emcb13, emcb14, emcb16, emcb22, emcb24, emcb26, emcb28, emcb31, emcb33, emcb35, emcb37, emcb38, emcc06, emcc09, emcc11, emcc12, emcc13, emcc14, emcc16, emcc22, emcc24, emcc26, emcc28, emcc31, emcc33, emcc35, emcc37, emcc38, emcd06, emcd09, emcd11, emcd12, emcd13, emcd14, emcd16, emcd22, emcd24, emcd26, emcd28, emcd31, emcd33, emcd35, emcd37, emcd38, emca42, emca43, emca45, emca46, emca47, emca48, emca50, emca51, emca64, emda01, emda06, emda09, emda11, emda12, emda13, emda14, emda16, emda22, emda24, emda26, emda28, emda31, emda33, emda35, emda37, emda38, emda39, emda40, emdb06, emdb09, emdb11, emdb12, emdb13, emdb14, emdb16, emdb22, emdb24, emdb26, emdb28, emdb31, emdb33, emdb35, emdb37, emdb38, emdc06, emdc09, emdc11, emdc12, emdc13, emdc14, emdc16, emdc22, emdc24, emdc26, emdc28, emdc31, emdc33, emdc35, emdc37, emdc38, emda42, emda43, emda45, emda46, emda47, emda48, emda50, emda51, emda64, emea01, emea06, emea09, emea11, emea12, emea13, emea14, emea16, emea22, emea24, emea26, emea28, emea31, emea33, emea35, emea37, emea38, emea39, emea40, emeb06, emeb09, emeb11, emeb12, emeb13, emeb14, emeb16, emeb22, emeb24, emeb26, emeb28, emeb31, emeb33, emeb35, emeb37, emeb38, emea42, emea43, emea45, emea46, emea47, emea48, emea50, emea51, emea64, emfa01, emfa06, emfa09, emfa11, emfa12, emfa13, emfa14, emfa16, emfa22, emfa24, emfa26, emfa28, emfa31, emfa33, emfa35, emfa37, emfa38, emfa39, emfa40, emfa42, emfa43, emfa45, emfa46, emfa47, emfa48, emfa50, emfa51, emfa64, em0002, em0004, em0009, em0011, em0012, em0016, em0024, em0028, em0033, em0037, em0038, em0039, em0040, em0042, em0043, em0045, em0046, em0047, em0048, em0050, em0051, em0065, seaa01, seaa06, seaa09, seaa11, seaa12, seaa15, seaa17, seaa23, seaa25, seaa31, seaa33, seaa39, seaa41, seaa47, seaa49, seab06, seab09, seab11, seab12, seab15, seab17, seab23, seab25, seab31, seab33, seab39, seab41, seab47, seab49, seac06, seac09, seac11, seac12, seac15, seac17, seac23, seac25, seac31, seac33, seac39, seac41, seac47, seac49, sead06, sead09, sead11, sead12, sead15, sead17, sead23, sead25, sead31, sead33, sead39, sead41, sead47, sead49, seae06, seae09, seae11, seae12, seae15, seae17, seae23, seae25, seae31, seae33, seae39, seae41, seae47, seae49, seaa57, seaa61, seaa65, seaa66, seaa68, seaa70, seaa60, seba01, seba06, seba09, seba11, seba12, seba15, seba17, seba23, seba25, seba31, seba33, seba39, seba41, seba47, seba49, sebb06, sebb09, sebb11, sebb12, sebb15, sebb17, sebb23, sebb25, sebb31, sebb33, sebb39, sebb41, sebb47, sebb49, sebc06, sebc09, sebc11, sebc12, sebc15, sebc17, sebc23, sebc25, sebc31, sebc33, sebc39, sebc41, sebc47, sebc49, sebd06, sebd09, sebd11, sebd12, sebd15, sebd17, sebd23, sebd25, sebd31, sebd33, sebd39, sebd41, sebd47, sebd49, seba57, seba61, seba65, seba66, seba68, seba70, seba60, seca01, seca06, seca09, seca11, seca12, seca15, seca17, seca23, seca25, seca31, seca33, seca39, seca41, seca47, seca49, secb06, secb09, secb11, secb12, secb15, secb17, secb23, secb25, secb31, secb33, secb39, secb41, secb47, secb49, secc06, secc09, secc11, secc12, secc15, secc17, secc23, secc25, secc31, secc33, secc39, secc41, secc47, secc49, seca57, seca61, seca65, seca66, seca68, seca70, seca60, seda01, seda06, seda09, seda11, seda12, seda15, seda17, seda23, seda25, seda31, seda33, seda39, seda41, seda47, seda49, sedb06, sedb09, sedb11, sedb12, sedb15, sedb17, sedb23, sedb25, sedb31, sedb33, sedb39, sedb41, sedb47, sedb49, seda57, seda61, seda65, seda66, seda68, seda70, seda60, seea01, seea06, seea09, seea11, seea12, seea15, seea17, seea23, seea25, seea31, seea33, seea39, seea41, seea47, seea49, seea57, seea61, seea65, seea66, seea68, seea70, seea60, se0003, se0002, se0004, sezz01, sezz06, sezz11, sezz12, sezz15, sezz17, sezz57, sezz61, sezz65, sezz66, sezz68, sezz70, t0001, taa01, taa05, taa08, taa20, tba01, tba05, tba08, tba20, tca01, tca05, tca08, tca20, tda01, tda05, tda08, tda20, tea01, tea05, tea08, tea20, i0001, iaa01, iaa05, iaa06, iaa11, iaa12, iaa13, iaa14, iaa15, iaa17, iaa18, iaa20, iaa21, iba01, iba05, iba06, iba11, iba12, iba13, iba14, iba15, iba17, iba18, iba20, iba21, ica01, ica05, ica06, ica11, ica12, ica13, ica14, ica15, ica17, ica18, ica20, ica21, ida01, ida05, ida06, ida11, ida12, ida13, ida14, ida15, ida17, ida18, ida20, ida21, iea01, iea05, iea06, iea11, iea12, iea13, iea14, iea15, iea17, iea18, iea20, iea21, iza01, iza05, iza06, iza11, iza12
`

**Comment by christian-fr** [comment]
Ab nächstem Rollout verfügbar.

**Comment by christian-fr** [comment]
Zur Kennnisnahme: die einzigen pages **ohne Fortschrittsbalken** sind nun (Stand: 17.12.2020 14:57h):

`msg_21, zwischen_k, zwischen_sc, zwischen_st, zwischen_v, zwischen_t, zwischen_i, zwischen_em, zwischen_u, zwischen_o, zwischen_epi, debug, end`
