### ISSUE TITLE
Epi: Studium staa10 strings verschieden groß (m/d)

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#76]
(m/d) = mobil/ desktop
iwie sind mir hier zu viele verschiedene Schriftgrößen/Arten - kann man "Name der Hochschule" evtl. in der Größe machen wie die restlichen aos? Die strings würde ich vermutlich auch in einer Größe wählen. In der mobilen Version sind ebenso die strings und aos verschoben. @jocarstensen wie siehst du das?

![grafik](https://user-images.githubusercontent.com/73596957/102477734-054cfd80-405d-11eb-9401-00c38fb65bf0.png)

![grafik](https://user-images.githubusercontent.com/73596957/102477992-5b21a580-405d-11eb-8337-05f8756588a2.png)

**Comment by jocarstensen** [comment]
Strings würde ich nicht gleich groß machen, da einmal Name der HS und dann Ort/Land/PLZ gefragt sind. Dabei fällt mir aber auf, dass die Prefixes nicht eingeblendet sind. Ich schreibe ein neues Issue dazu.
Zu den unterschiedlichen Schriftgrößen: Sicher, das kann man bestimmt noch hübscher machen.

**Comment by AliceFoelker** [comment]
ja da hatte ich für eine Seite bereits ein Issue erstellt #43 kann man das dann pauschlal für alle Seiten dieser Art einstellen @andreaschu ?

**Comment by jocarstensen** [comment]
Soweit ich weiß kann man das nur pauschal. Ich würde auch stark dafür plädieren, dass hier nur Layout-Anpassungen gemacht werden, die per CSS glibal einstellbar sind. Denn allein diese Seite gibt es glaube ich um die 15 Mal.

**Comment by jocarstensen** [comment]
@andreaschu Dann gibt es jetzt zwei Issues zu den Prefixes, sorry. Meinetwegen kannst Du eins davon schließen, #43 oder #77

**Comment by AliceFoelker** [comment]
@jocarstensen soll da jetzt noch was an der Schrift gemacht werden oder closen?

**Comment by jocarstensen** [comment]
Da das vermutlich global gelöst werden muss, würde ich erstmal nichts weiter unternehmen. Falls es auch noch auf anderen Seiten negativ auffällt, können wir das Thema nochmal angehen.
