### ISSUE TITLE
Einblendung Prefixes in Textfeldern

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/studienberechtigte_2018.3b#77]
Die Prefixes müssen in offenen Textfeldern noch eingeblendet werden.

![grafik](https://user-images.githubusercontent.com/35771616/102479669-7ab9cd80-405f-11eb-9bd9-2e3566bc04a0.png)

**Comment by dzhwmeisner** [comment]
Im nächsten Rollout verfügbar
