### ISSUE TITLE
Epi: emaa12 mobil Version zerschossen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#78]
emba12 etc. em*a12
![grafik](https://user-images.githubusercontent.com/73596957/102480542-b5703580-4060-11eb-91ac-22e195379367.png)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout (#71 ) verfügbar

**Comment by AliceFoelker** [comment]
fixed
