### ISSUE TITLE
Epi: em0043 Skalenpunkte einheitlich möglich?

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#79]
Ist es möglich die Skalenpunkte einheitlicher mit den Zahlen anzuordnen?

![grafik](https://user-images.githubusercontent.com/73596957/102481476-0e8c9900-4062-11eb-935a-1beade595bcf.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#103 ) verfügbar

**Comment by AliceFoelker** [comment]
@heikQ hm jetzt sieht es so aus. @christian-fr also kann man die Zahlen nicht einheitlich auf einer Höhe anordnen? und die Beschriftung pauschal drüber?

![grafik](https://user-images.githubusercontent.com/73596957/103554530-5a876c80-4eaf-11eb-8372-30aa4f3a9359.png)
