### ISSUE TITLE
Studium: stu_07 leere Seite

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#80]
nach stu_00 komme ich zu stu_07 (das ist korrekt) aber die Seite ist leer?

![grafik](https://user-images.githubusercontent.com/73596957/102481894-b013ea80-4062-11eb-9de5-4ed4dc13182d.png)

**Comment by andreaschu** [comment]
ich habe es hoffentlich korrigiert. Ab nächstem Roll-Out verfügbar.

**Comment by AliceFoelker** [comment]
ist wieder da
