### ISSUE TITLE
Studium: stu_10 Einblendung Studienfach leer

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#81]
tester1 wave 4
Hier soll das Studienfach aus dem Episodenmodul eingeblendet werden. (In diesem Fall sollte da jetzt **Soziologie** stehen)
@heikQ ich vermute, dass in der PV an der Stelle die falsche Hilfsvariable eingetragen ist?! (h_staktsfz01)?

![grafik](https://user-images.githubusercontent.com/73596957/102482271-3d573f00-4063-11eb-8870-a2b0aac0cb77.png)

**Comment by andreaschu** [comment]
@heikQ wo kommt diese Hilfsvariable eigentlich her? Ich finde sie weder im Epi-Modul Studium noch im Modul 05.

**Comment by AliceFoelker** [comment]
@andreaschu @heikQ hatte damals das hier genommen. Ich befürchte das ist falsch. Wir wollten das zuletzt angegebene, quasi aktuellste, Studienfach. Geht das überhaupt?
![grafik](https://user-images.githubusercontent.com/73596957/102487511-fc632880-406a-11eb-9999-872a28352fbb.png)

**Comment by andreaschu** [comment]
ich habe es noch mal getestet. Bei mir wird die Hilfsvariable eingeblendet.

![grafik](https://user-images.githubusercontent.com/30111489/102492263-b78ec000-4071-11eb-9f9b-210ced59bf62.png)

![grafik](https://user-images.githubusercontent.com/30111489/102492293-c2e1eb80-4071-11eb-8ac0-d18c44eb37fc.png)

**Comment by andreaschu** [comment]
@AliceFoelker laut FlowChart laufen hier zwar die meisten rein, aber nicht alle. Auf der st0002 (siehe rote Markierung) wird diese Hilfsvariable gefüllt. Rechts und links laufen aber Pfade daran vorbei. 
Ich kann nicht einschäzten, ob das irgendwann mal leer bleiben kann. Da müsstest Du Sebastian oder Johann fragen, die haben den besseren Überblick über die Episodenmodule.

![grafik](https://user-images.githubusercontent.com/30111489/102495721-be6c0180-4076-11eb-884f-c1f56f000c5a.png)

**Comment by AliceFoelker** [comment]
@andreaschu ich glaube ich habe den "Fehler" Ich hatte damals nur den Studiengang: z.B: Soziologie eingetragen, weil dieser bspw. nicht in Hauptfächer eingeteilt ist. was bedeutet, dass diese Lücke frei bleibt. @heikQ wie lösen wir das am besten? Statt dem Fach den Studiengang in stu_10 abfragen? Oder bedingte Formulierungen einfügen? show q2: Was halten Ihre Eltern und Ihre Freunde von Ihrem Studienfach? (ohne EInblendung) IF h_staktsfz01==MISSING iwie so?

**Comment by heikQ** [comment]
@AliceFoelker Lass uns das mit bedingter Formulierung machen, also  q2: Was halten Ihre Eltern und Ihre Freunde von Ihrem Studienfach? (ohne EInblendung) IF h_staktsfz01==MISSING

**Comment by andreaschu** [comment]
Habe es hoffentlich gelöst. Kann ab nächstem Roll-Out getestet werden.
