### ISSUE TITLE
Studium: stu_24 Transitionfehler; kein weiterkommen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#82]
tester1 wave4 
obwohl ich >nein, auf keinen Fall< angekreuzt habe springt die sf rein und ich komme nicht von der Seite.
@andreaschu ich glaube das ist der Klammerfehler auf den du mich zu Anfang mal aufmerksam gemacht hast. Hattest du da nicht eine Anpassung vorgenommen?

**Comment by andreaschu** [comment]
@AliceFoelker technisch gibt es hier keinen Klammerfehler. Logisch eigentlich auch nicht. Aber ich habe den Eindruck, dass die Bedingungen nicht erschöpfend sind. Z. B. fehlt aus meiner Sicht eine Bedingung, wenn:

				((bestwuw_183b)==4 or (bestwuw_183b)==5) 
				and zofar.asNumber(h_studever)==1

Bitte schau noch mal in die Bedingungen oder hier in den programmierten [FlowChart](https://user-images.githubusercontent.com/30111489/102377933-8658b600-3fc5-11eb-8bd4-31bcefc8ae0a.png).
