### ISSUE TITLE
SOzDem: msg_06 bleibt leer keine Einblendung v. items und aos

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#85]
tester1 wave4
Die Einblendbedingungen greifen nicht. Wo liegt der Fehler? m.E. müsste lt. PV hier q3 angezeigt werden
![grafik](https://user-images.githubusercontent.com/73596957/102483988-e4d57100-4065-11eb-9c83-73620c4ad242.png)

**Comment by andreaschu** [comment]
@AliceFoelker die Einblendungen funktionieren bei mir. Die Frage ist eher, ob Du ohne gefüllte Hilfsvariablen (h_studakt und h_ausbakt) auf die Seite kommen solltest. 
Die füllen sich durch Angaben im Episodenmodul (Ausbildung und Studium). Kontrollieren kannst Du das auf Seite zwischen_k.

![grafik](https://user-images.githubusercontent.com/30111489/102486493-67136480-4069-11eb-96bb-9e9ee7728817.png)

**Comment by AliceFoelker** [comment]
@andreaschu was m.E. bedeuten müsste dass it 3 angezeigt werden müsste? Übersehe ich iwas?

![grafik](https://user-images.githubusercontent.com/73596957/102486969-21a36700-406a-11eb-8f94-7da2978b45a8.png)

**Comment by andreaschu** [comment]
Oh, die Bedingung ist falsch programmiert. 
Habe ich korrigiert und ist ab nächstem Roll-Out verfügbar.

**Comment by AliceFoelker** [comment]
fixed
