### ISSUE TITLE
Headline - Schriftgröße und Farbe ändern 

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#89]
bei cor_01 ist die >in< dick geschrieben. Wir hätten die >in< dieser Art gerne in der Schriftgröße wie >q< und in grau wie z.B. >Studium< auf st0001. Möglich? Wenn ja, würde ich vermutlich nach und nach raussuchen, für welche in's das zutreffen würde :-/ 

- [x] cor_01

- [x] stu_13
- [ ] gsh_02

**Comment by andreaschu** [comment]
Ja, das ist möglich. Es sind übrigens Überschriften, die grau gelayoutet sind.
Könntest Du die bitte alle in einem Issue sammeln, also hier?

**Comment by christian-fr** [comment]
@AliceFoelker Ich nehme an, dass bei **stu_13** nur der erste Satz `Im Folgenden geht es um Ihren derzeitigen Studiengang.` so formatiert sein soll?

**Comment by andreaschu** [comment]
gsh_02 kann beim nächsten Roll-Out getestet werden
