### ISSUE TITLE
stu_07: Änderung 5 items jew. 1 Seite

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#9]
stu_07 -  bislang 5 items mit jeweils unterschiedlichen Antwortskalen auf einer Seite. Ändern in jeweils 1 PV-Seite pro Item. Allerdings auf einer FB-Seite abbilden.

**Comment by andreaschu** [comment]
Ich schätze, das Issue kann auch geschlossen werden, oder?

**Comment by AliceFoelker** [comment]
Ich schaue mir die Umsetzung gleich an und wenn es passt kann es raus.

**Comment by AliceFoelker** [comment]
@andreaschu das Issue kann geschlossen werden. Könnte ich das jetzt in diesem Fall machen oder macht ihr das immer?

**Comment by andreaschu** [comment]
@AliceFoelker: wenn Du es getestet hast, kannst und solltest Du es schließen. Jetzt mach ich es eben. :o)
