### ISSUE TITLE
Zwischenseite3 auf zwischen_epi einfügen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#90]
und der Text kann raus

**Comment by andreaschu** [comment]
@dzhwmeisner die Bilder sind im #25 gesammelt. Aber es gibt sie schon im SVN (03_zwischenseite_700.png).

**Comment by dzhwmeisner** [comment]
Im nächsten Rollout verfügbar

**Comment by AliceFoelker** [comment]
@christian-fr @dzhwmeisner Zwischenseite ist eingefügt, allerdings steht unten noch ein Teil des Textes.

ABER die Zwischenseiten müssen leider sowieso noch mal ausgetauscht werden, da wir etwas am Layout verändert haben. Dann kann in diesem Schritt direkt auch der Text entfernt werden oder?

![grafik](https://user-images.githubusercontent.com/73596957/103535264-babae600-4e90-11eb-87e7-c534d47326d4.png)

**Comment by christian-fr** [comment]
Text ist entfernt. Ab nächstem Rollout verfügbar.
