### ISSUE TITLE
Epi: bleibe auf zwischen_t hängen

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#91]
tester3 wave 4
bleibe auf zwischen_t hängen nachdem ich bei t0001 >nein< angegeben habe
![grafik](https://user-images.githubusercontent.com/73596957/102502719-3dfdce80-407f-11eb-8021-e561451385e3.png)

**Comment by andreaschu** [comment]
war noch im debug-Modus. Sollte beim nächsten Roll-Out korrigiert sein.
