### ISSUE TITLE
SozDem: msg_02 ao11 korrigieren

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#93]
bitte wie in PV 
![grafik](https://user-images.githubusercontent.com/73596957/102510580-1101e980-4088-11eb-9e4c-4d9049a59758.png)
![grafik](https://user-images.githubusercontent.com/73596957/102510774-4c9cb380-4088-11eb-9edb-85763346c7a4.png)

**Comment by andreaschu** [comment]
Ups. 
Ist geändert und ab nächstem Roll-Out verfügbar.
