### ISSUE TITLE
Studium: stu_13/14 

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#95]
hier müssen wir noch mal schauen was da nicht richtig ist. Ich habe leider die alten Screenshots dazu nicht gefunden 👎 
![grafik](https://user-images.githubusercontent.com/73596957/102515366-f6cb0a00-408d-11eb-9fff-d77690dc4eea.png)

**Comment by andreaschu** [comment]
@AliceFoelker hier gibt es Einblendbedingungen auf jeder Antwortkategorie. Wenn Die nicht gefüllt sind, wird nur die sonstige und die offene angezeigt. Erscheint mir erst mal plausibel, vielleicht noch nicht ganz rund.

	"ao1" value="1" label="#{zofar.labelOf(h_staktsga)}" visible="h_staktsga.value"
	"ao2" value="2" label="#{zofar.labelOf(h_staktsgb)}" visible="h_staktsgb.value"
	"ao3" value="3" label="#{zofar.labelOf(h_staktsgc)}" visible="h_staktsgc.value"
	"ao4" value="4" label="#{zofar.labelOf(h_staktsgd)}" visible="h_staktsgd.value"
	"ao5" value="5" label="#{zofar.labelOf(h_staktsge)}" visible="h_staktsge.value"
	"ao6" value="6" label="#{zofar.labelOf(h_staktsgz)}" visible="h_staktsgz.value"
	"ao7" value="7" label="ein anderer Studiengang, und zwar " 
	"ao8" value="8" label="" visible="!h_staktsga.value and !h_staktsgb.value and !h_staktsgc.value and 
                                      !h_staktsgd.value and !h_staktsge.value and !h_staktsgz.value"

**Comment by AliceFoelker** [comment]
@christian-fr Hier würde ich gern stu_13 und stu_14 zusammenlegen siehe https://github.com/dzhw/studienberechtigte_2018.3b/commit/683ec6657ffc0823171a845120e4790931492b5e. Außerdem wäre es fein, wenn die "Liste" der im Episodenmodul zuvor angegebenen Studiengänge und Fächer in Form von Drop-Downs aufgeführt werden könnten. Hier besteht allerdings noch ein Problem, da die im code verwendeten Hilfsvariablen nicht gefüllt werden (z.B. auf staa04). Iwas ist da also noch falsch. Geht das überhaupt?

**Comment by andreaschu** [comment]
@AliceFoelker ich habe hier die Einblendbedingungen auch leicht verändert. Mir erscheint es jetzt richtig, aber bitte teste es noch mal.

**Comment by AliceFoelker** [comment]
hier müssen wir noch etwas basteln:
wenn man staa04,stba04 etc. mit Studiengängen und Hauptfächern füllt sieht es so aus:
![grafik](https://user-images.githubusercontent.com/73596957/103774588-1e7a1600-502d-11eb-8496-662454bfd4f8.png)



Wenn man nur einen Studiengang ausfüllt und kein Fach - sieht es so aus:
![grafik](https://user-images.githubusercontent.com/73596957/103774641-318ce600-502d-11eb-8b68-68cfef7b314e.png)



Wenn wir zwar angeben ein Studium absolviert zu haben ABER keine weiteren Angaben dazu erfolgen sieht es so aus:
![grafik](https://user-images.githubusercontent.com/73596957/103774690-46697980-502d-11eb-9df8-e131ad12deec.png)

d.h. iwas stimmt noch nicht mit den Einblendbedingungen, da so oder so sonstiges und zwar immer da stehen soll.

@heikQ auch grundsätzlich weiß ich nicht, ob ich - falls mehrere Angaben gemacht werden - so happy mit der Lösung bin, da so theoretisch unterschiedliche Kombis gewählt werden können UND bei den Haupt und Nebenfächern immer nur eins von beiden ausgewählt werden kann. Ich überlege ob "Pakete" nicht doch eindeutiger wären. Was sagst du?

**Comment by andreaschu** [comment]
@AliceFoelker die AntwortOption 'sonstiges und zwar' erscheint nur, wenn mindestens eine der 6 Hilfsvariablen gefüllt ist. 
Wenn alle Hilfsvariablen leer sind, erscheint das leere Feld. So hatte ich die PV verstanden.

**Comment by andreaschu** [comment]
5d6ff61 und ddb214f  geändert. Beim nächsten Roll-Out (#163) verfügbar.
