### ISSUE TITLE
Studium: stu_06 Einblendung ändern

### ISSUE THREAD

**Issue by AliceFoelker** [dzhw/studienberechtigte_2018.3b#96]
Wenn nur 1 Item angezeigt wird, sieht das m.E. komisch aus, wie siehst du das @heikQ? 
@andreaschu hast du eine Idee wie man das schöner/eleganter lösen könnte,? 

![grafik](https://user-images.githubusercontent.com/73596957/102516073-c172ec00-408e-11eb-9d40-71e125d06159.png)

**Comment by andreaschu** [comment]
@AliceFoelker man könnte höchstens die Items als einzelne SingleChoice bauen und jeweils mit Visible Conditions belegen. Die wären dann aber auch für mobile Geräte wieder nicht im Carousel, sondern horizontal.

**Comment by AliceFoelker** [comment]
@heikQ so lassen oder: 
> @AliceFoelker man könnte höchstens die Items als einzelne SingleChoice bauen und jeweils mit Visible Conditions belegen. Die wären dann aber auch für mobile Geräte wieder nicht im Carousel, sondern horizontal.
> Der Fragetext wäre dann eher:
> 
> > Inwieweit trifft die Aussage auf Ihre finanzielle Situation zu: Die Finanzierung meines Lebensunterhaltes ist bis zu meinem Studienabschluss sichergestellt.

**Comment by AliceFoelker** [comment]
@heikQ dann lassen wir es so wie es ist oder?

**Comment by heikQ** [comment]
so lassen
