### ISSUE TITLE
Erreichbarkeit Feiertage

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/studienberechtigte_2018.3b#98]
Liebes ZOFAR-Team,
könnt Ihr nochmal schreiben, wie es bei Euch mit Erreichbarkeit über die Feiertage aussieht? Gibt es einen Zeitraum, in dem niemand erreichbar ist und wenn ja, von wann bis wann?

**Comment by andreaschu** [comment]
Wir sind nicht erreichbar zwischen 

- andreaschu: 21.12.2020 - 04.01.2021
- christian-fr: 21.12.2020 - 31.12.2020
- vdick: 21.12.2020 - 31.12.2020
- dzhwmeisner: 23.12.2020 - 08.01.2021
